#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\raffles\client\texture.py
import eveicon

def _res(path):
    return 'res:/UI/Texture/{}'.format(path)


def _raffle_res(filename):
    return _res('classes/HyperNet/{}'.format(filename))


bracket = _raffle_res('bracket.png')
create_item_background = _raffle_res('create_item_background.png')
create_item_border = _raffle_res('create_item_border.png')
created_icon = _raffle_res('created_icon.png')
filter_icon = _raffle_res('filter_icon.png')
flag = _raffle_res('flag.png')
tickets_icon = _raffle_res('tickets_icon.png')
triangle = _raffle_res('triangle.png')
check_mark_large = _raffle_res('check_mark_large.png')
details_item_frame = _raffle_res('details_item_frame.png')
hyperlink_icon = _raffle_res('hyperlink_icon.png')
portrait_mask = _raffle_res('portrait_mask.png')
fanfare_winner_frame = _raffle_res('fanfare_winner_frame.png')
fanfare_winner_frame_player = _raffle_res('fanfare_winner_frame_player.png')
fanfare_arrow = _raffle_res('fanfare_arrow.png')
card_sweep_frame = _raffle_res('card_sweep_frame.png')
refresh_icon = _raffle_res('refresh_icon.png')
list_item_shimmer_underlay = _raffle_res('history_entry_underlay.png')
list_item_shimmer_effect = _raffle_res('history_entry_highlight.png')
banner_frame = _raffle_res('banner_frame.png')
banner_frame_stroke = _raffle_res('banner_frame_stroke.png')
infinity = _raffle_res('infinity.png')
panel_1_corner_3px = _raffle_res('panel_1_corner_3px.png')
panel_1_corner_2px = _raffle_res('panel_1_corner_2px.png')
background_triangles = _raffle_res('background_triangles.png')
background_triangles_banner = _raffle_res('background_triangles_banner.png')
background_triangles_banner_lines = _raffle_res('background_triangles_banner_lines.png')
sort_ascending = _raffle_res('sort_ascending.png')
sort_descending = _raffle_res('sort_descending.png')
hyper_cube_outer = _raffle_res('tutorial/hyper_cube_outer.png')
hyper_cube_inner = _raffle_res('tutorial/hyper_cube_inner.png')
logo_left_main = _raffle_res('tutorial/logo/left_main.png')
logo_left_inner = _raffle_res('tutorial/logo/left_inner.png')
logo_right_main = _raffle_res('tutorial/logo/right_main.png')
logo_right_inner = _raffle_res('tutorial/logo/right_inner.png')
logo_star = _raffle_res('tutorial/logo/star.png')
effect_ding = _raffle_res('tutorial/effect_ding.png')
button_hint_bubble = _raffle_res('tutorial/button_hint_bubble.png')
bg_intro = _raffle_res('fanfare/bg_intro.webm')
bg_loop = _raffle_res('fanfare/bg_loop.webm')
bg_outro_win = _raffle_res('fanfare/bg_outro_win.webm')
bg_outro_lose = _raffle_res('fanfare/bg_outro_lose.webm')
hex_base = _raffle_res('fanfare/hex_base.png')
hex_icon_base = _raffle_res('fanfare/hex_icon_base.png')
hex_icon_frame = _raffle_res('fanfare/hex_icon_frame.png')
hex_icon_highlight_top = _raffle_res('fanfare/hex_icon_highlight_top.png')
hex_icon_highlight_bot = _raffle_res('fanfare/hex_icon_highlight_bot.png')
hex_effect_1 = _raffle_res('fanfare/hex_effect_1.png')
hex_effect_2 = _raffle_res('fanfare/hex_effect_2.png')
hex_flare = _raffle_res('fanfare/hex_flare.png')
hex_icon_mask = _raffle_res('fanfare/hex_icon_mask.png')
owned_tickets_frame = _raffle_res('fanfare/owned_tickets_frame.png')
checkmark = _res('Shared/checkMark.png')
corner_triangle_small = _res('Shared/DarkStyle/cornerTriSmall.png')
frame_1_corner = _res('Shared/DarkStyle/panel1Corner_Stroke.png')
frame_2_corner = _res('Shared/DarkStyle/panel2Corner_Stroke.png')
panel_1_corner = _res('Shared/DarkStyle/panel1Corner_Solid.png')
panel_2_corner = _res('Shared/DarkStyle/panel2Corner_Solid.png')
window_close_icon = _res('Shared/DarkStyle/windowClose.png')
button_gradient = _res('Shared/DarkStyle/buttonGradient.png')
sweep_effect = _res('classes/Neocom/buttonBlink.png')
history_back = eveicon.navigate_back
history_forward = eveicon.navigate_forward
add_icon = eveicon.add
delete_saved_filter_icon = _res('Icons/73_16_45.png')
market_icon = _res('WindowIcons/market.png')
new_eden_store_icon = _res('WindowIcons/NES.png')
raffle_window_icon = _res('WindowIcons/hypernet.png')
drag_icon = _res('WindowIcons/hypernet.png')
group_icon = _res('WindowIcons/smallfolder.png')
exclamation_icon = _res('classes/Agency/iconExclamation.png')
isk_16 = _res('Vgs/isk_16.png')
content_frame = _res('classes/agency/hDecoExpand.png')
content_frame_middle = _res('classes/agency/hDecoMiddle.png')
