#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\common\modules\nice\client\_nastyspace\svc.py
from eve.client.script.ui.shared.assets.assetSafetySvc import AssetSafetySvc as assetSafety
from eve.client.script.ui.shared.dockedUI.undockingSvc import UndockingSvc as undocking
from eve.client.script.ui.shared.ledger.ledgerSvc import LedgerSvc as ledger
from eve.client.script.ui.moonmining.schedulingSvc import SchedulingSvc as scheduling
from eve.client.script.ui.structure.structureControllersSvc import StructureControllerSvc as structureControllers
from liveupdates.liveupdatesvc import LiveUpdateSvc
from carbon.common.script.net.WSGIService import WSGIService
from carbon.common.script.net.emailSvc import EmailSvc as emailSvc
from carbon.common.script.net.http2Service import CherryServer as http2
from carbon.common.script.net.httpGate import HttpGate as httpGate
from carbon.common.script.net.httpService import ConnectionService as http
from carbon.common.script.net.machoNet import MachoNetService as machoNet
from carbon.common.script.net.objectCaching import CoreObjectCachingSvc as objectCaching
from carbon.common.script.net.xmlrpcClient import XmlrpcClient as xmlrpcClient
from carbon.common.script.sys.alert import Alert as alert
from carbon.common.script.sys.cfg import DataConfig as dataconfig
from carbon.common.script.sys.counterService import CoreCounterService as counter
from carbon.common.script.sys.debugSvc import debugSvc as debug
from carbon.common.script.sys.loadService import LoadService as loadService
from carbon.common.script.sys.networkLogging import NetworkLogging as networkLogging
from carbon.common.script.sys.processHealthSvc import ProcessHealthSvc as processHealth
from carbon.common.script.sys.sessions import SessionMgr as sessionMgr
from carbon.common.script.util.prioritizedLoadManager import PrioritizedLoadManager as prioritizedLoadManager
from carbon.client.script.environment.audioService import AudioService as audio
from carbon.client.script.graphics.paperDollClient import PaperDollClient as paperDollClient
from carbon.client.script.localization.localizationClient import LocalizationClient as localizationClient
from carbon.client.script.remote.connectionService import ConnectionService as connection
from carbon.client.script.sys.infoGatheringSvc import InformationGatheringSvc as infoGatheringSvc
from carbonui.control.browser.imageCacheSvc import ImageCache as imageCache
from carbonui.control.browser.browserImageSvc import BrowserImage as browserImage
from carbonui.control.browser.sites import SitesSvc as sites
from carbonui.services.command import CommandService as cmd
from carbonui.services.device import DeviceMgr as device
from paperdoll.client import PaperdollSvc as paperdoll
from carbonui.services.settingsSvc import SettingsSvc as settings
from carbonui.modules.monitor import FpsMonitorSvc as fpsMonitorSvc
from carbon.client.script.util.cacheDirectoryLimitSvc import CacheDirectoryLimitService as cacheDirectoryLimit
from carbon.client.script.util.logsvc import LoggingSvc as log
from carbon.client.script.util.monitor import Monitor as monitor
from eve.devtools.script.autobot import AutoBotService as autobot
from eve.devtools.script.uiDebugger import UISnapshotSvc as UISnapshot
from eve.common.script.dogma.baseDogma import BaseDogma as baseDogma
from eve.common.script.dogma.baseDogmaStaticSvc import BaseDogmaStaticSvc as baseDogmaStaticSvc
from eve.common.script.dogma.baseEffectCompiler import BaseEffectCompiler as baseEffectCompiler
from eve.common.script.net.eveEmailSvc import EveEmailSvc as eveEmailSvc
from eve.common.script.net.eveMachoNet import EveMachoNetService as eveMachoNet
from eve.common.script.net.eveObjectCaching import EveObjectCachingSvc as eveObjectCaching
from eve.common.script.sys.eveAlert import Alert as eveAlert
from eve.common.script.sys.eveCfg import EveDataConfig as eveDataconfig
from eve.common.script.sys.eveProcessHealthSvc import EveProcessHealthSvc as eveProcessHealth
from eve.common.script.sys.eveSessions import SessionMgr as eveSessionMgr
from eve.client.script.dogma.clientDogma import ClientDogma as dogma
from eve.client.script.dogma.clientDogmaIM import ClientDogmaInstanceManager as clientDogmaIM
from eve.client.script.dogma.clientDogmaStaticSvc import ClientDogmaStaticSvc as clientDogmaStaticSvc
from eve.client.script.dogma.clientEffectCompiler import ClientEffectCompiler as clientEffectCompiler
from eve.client.script.ui.shared.fittingScreen.ghostFittingEffectCompiler import GhostFittingEffectCompiler as ghostFittingEffectCompiler
from eve.client.script.environment.fittingSvc import fittingSvc
from eve.client.script.environment.godma import Godma as godma
from eve.client.script.environment.invCache import invCache
from eve.client.script.environment.planetSvc import PlanetService as planetSvc
from eve.client.script.environment.sofService import sofService
from eve.client.script.environment.vgsService import VgsService as vgsService
from eve.client.script.environment.nodditestrunner import NoddiTestRunner as noddiTestRunner
from eve.client.script.graphics.paperDollClient import EvePaperDollClient as evePaperDollClient
from eve.client.script.industry.blueprintSvc import BlueprintService as blueprintSvc
from eve.client.script.industry.facilitySvc import FacilityService as facilitySvc
from eve.client.script.industry.industrySvc import IndustryService as industrySvc
from eve.client.script.parklife.autopilot import AutoPilot as autoPilot
from eve.client.script.parklife.bracketMgr import BracketMgr as bracket
from eve.client.script.parklife.consider import ConsiderSvc as consider
from eve.client.script.parklife.cloakingSvc import CloakingSvc as cloaking
from eve.client.script.parklife.cynoTravelSvc import CynoTravelSvc as cynoTravel
from eve.client.script.parklife.damageSvc import DamageService as damage
from eve.client.script.parklife.dungeonTracking import DungeonTracking as dungeonTracking
from eve.client.script.parklife.environmentSvc import EnvironmentService as environment
from eve.client.script.parklife.subwaySvc import SubwayService as subway
from eve.client.script.parklife.fightersSvc import FightersSvc as fighters
from eve.client.script.parklife.fleetSvc import FleetSvc as fleet
from eve.client.script.parklife.fxSequencer import FxSequencer
from eve.client.script.parklife.gameui import GameUI as gameui
from eve.client.script.parklife.moonscan import MoonScanSvc as moonScan
from eve.client.script.parklife.overview.presetservice import OverviewPresetSvc as overviewPresetSvc
from eve.client.script.parklife.ownerprimer import OwnerPrimer as ownerprimer
from eve.client.script.parklife.planetInfoSvc import PlanetInfoSvc as planetInfo
from eve.client.script.parklife.playerOwned import PlayerOwned as pwn
from eve.client.script.parklife.playerOwnedTargetMgr import PlayerOwnedTargetMgr as pwntarget
from eve.client.script.parklife.posAnchorSvc import PosAnchorSvc as posAnchor
from eve.client.script.parklife.recorder import EventRecorder as recorder
from eve.client.script.parklife.scanSvc import ScanSvc as scanSvc
from eve.client.script.parklife.directionalScanSvc import DirectionalScanSvc as directionalScanSvc
from eve.client.script.parklife.scenarioMgr import ScenarioMgr as scenario
from eve.client.script.parklife.sceneManager import SceneManager as sceneManager
from eve.client.script.parklife.sensorSuiteService import SensorSuiteService as sensorSuite
from eve.client.script.parklife.shipcasterSvc import ShipcasterSvc as shipcaster
from eve.client.script.parklife.spaceMgr import SpaceMgr as space
from eve.client.script.parklife.state import StateSvc as stateSvc
from eve.client.script.parklife.surveyscan import SurveyScanSvc as surveyScan
from eve.client.script.parklife.tactical import TacticalSvc as tactical
from eve.client.script.parklife.systemWideEffectSvc import SystemWideEffectSvc as systemWideEffectSvc
from eve.client.script.parklife.targetMgr import TargetMgr as target
from eve.client.script.parklife.transmissionMgr import TransmissionSvc as transmission
from eve.client.script.parklife.triggerMgr import Triggers as trigger
from eve.client.script.parklife.turret import TurretSvc as turret
from eve.client.script.remote.michelle import Michelle as michelle
from publicGateway.publicGatewaySvc import PublicGatewaySvc as publicGatewaySvc
from eve.client.script.sys.clientStatsSvc import ClientStatsSvc as clientStatsSvc
from eve.client.script.ui.clonegrade.cloneGradeSvc import CloneGradeSvc as cloneGradeSvc
from eve.client.script.ui.eveCommands import EveCommandService as eveCmd
from eve.client.script.ui.extras.tourneyUISvc import TourneyUISvc as tourneyUISvc
from eve.client.script.ui.hacking.hackingUISvc import HackingSvc as hackingUI
from eve.client.script.ui.heronotification.service import HeroNotificationService as heroNotification
from eve.client.script.ui.view.dockingHeroNotificationService import DockingHeroNotificationService as dockingHeroNotification
from progression.client.progressionSvc import ProgressionService as progressionSvc
from eve.client.script.ui.services.accountsvc import Account as account
from eve.client.script.ui.services.alliances.all_cso import Alliances as alliance
from eve.client.script.ui.services.bugReporting import BugReportingService as bugReporting
from eve.client.script.ui.services.ccSvc import CCSvc as cc
from eve.client.script.ui.services.certificateSvc import Certificates as certificates
from eve.client.script.ui.services.character import Character as character
from eve.client.script.ui.services.characterEnergySvc import CharacterEnergySvc as characterEnergySvc
from eve.client.script.ui.services.characterSettingsSvc import CharacterSettingsSvc as characterSettings
from eve.client.script.ui.services.clonejumpsvc import CloneJump as clonejump
from eve.client.script.ui.services.corporation.base_corporation import Corporation as corp
from eve.client.script.ui.services.corporation.officeManager import OfficeManager as officeManager
from eve.client.script.ui.services.crimewatchSvc import CrimewatchService as crimewatchSvc
from eve.client.script.ui.services.deathzoneSvc import DeathzoneSvc as deathzoneSvc
from eve.client.script.ui.services.eveCalendarsvc import CalendarSvc as calendar
from eve.client.script.ui.services.evePhotosvc import EvePhoto as photo
from eve.client.script.ui.services.eveSettingsSvc import EveSettingsSvc as eveSettings
from eve.client.script.ui.services.facWarSvc import FactionalWarfare as facwar
from eve.client.script.ui.services.factionsvc import Faction as faction
from eve.client.script.ui.services.fwAdvantageSvc import FwAdvantageSvc as fwAdvantageSvc
from eve.client.script.ui.services.fwEnlistmentSvc import FwEnlistmentSvc as fwEnlistmentSvc
from eve.client.script.ui.services.fwVictoryPointSvc import FwVictoryPointSvc as fwVictoryPointSvc
from eve.client.script.ui.services.fwWarzoneSvc import FwWarzoneSvc as fwWarzoneSvc
from eve.client.script.ui.services.flightControls import FlightControls as flightControls
from eve.client.script.ui.services.flightPredictionSvc import FlightPredictionService as flightPredictionSvc
from eve.client.script.ui.shared.info.infosvc import Info as info
from eve.client.script.ui.services.inventorysvc import InventorySvc as inv
from eve.client.script.ui.services.jumpQueue import JumpQueue as jumpQueue
from eve.client.script.ui.services.mail.mailSvc import mailSvc
from eve.client.script.ui.services.mail.mailingListsSvc import MailingLists as mailinglists
from eve.client.script.ui.services.mail.notificationSvc import notificationSvc
from eve.client.script.ui.services.marketsvc import MarketQuote as marketQuote
from eve.client.script.ui.services.medals import Medals as medals
from eve.client.script.ui.services.menusvc import MenuSvc as menu
from eve.client.script.ui.services.redeemsvc import RedeemService as redeem
from eve.client.script.ui.services.activitiesSvc import ActivitiesService as activities
from eve.client.script.ui.services.reprocessingsvc import ReprocessingSvc as reprocessing
from eve.client.script.ui.services.shipConfigSvc import ShipConfigSvc as shipConfig
from eve.client.script.ui.services.skillQueueSvc import SkillQueueService as skillqueue
from eve.client.script.ui.services.skillsvc import SkillsSvc as skills
from eve.client.script.ui.services.solarsystemInterferenceSvc import SolarsystemInterferenceSvc as solarsystemInterferenceSvc
from eve.client.script.ui.services.sovSvc import SovService as sov
from eve.client.script.ui.services.standingsvc import Standing as standing
from eve.client.script.ui.services.structure.structureControl import StructureControl as structureControl
from eve.client.script.ui.services.structure.structureDeployment import StructureDeployment as structureDeployment
from eve.client.script.ui.services.structure.structureDocking import StructureDocking as structureDocking
from eve.client.script.ui.services.structure.structureDirectory import StructureDirectory as structureDirectory
from eve.client.script.ui.services.structure.structureGuests import StructureGuests as structureGuests
from eve.client.script.ui.services.structure.structureHangarViewSvc import StructureHangarViewSvc as structureHangarViewSvc
from eve.client.script.ui.services.structure.structureProximityTracker import StructureProximityTracker as structureProximityTracker
from eve.client.script.ui.services.structure.structureServices import StructureServices as structureServices
from eve.client.script.ui.services.structure.structureSettings import StructureSettings as structureSettings
from eve.client.script.ui.services.surveySvc import SurveySvc as survey
from eve.client.script.ui.services.uipointersvc import UIPointerSvc as uipointerSvc
from eve.client.script.ui.services.uisvc import UI as ui
from eve.client.script.ui.services.viewStateSvc import ViewStateSvc as viewState
from eve.client.script.ui.services.wars.war_cso import Wars as war
from eve.client.script.ui.services.wars.warPermit import WarPermit as warPermit
from eve.client.script.ui.services.wars.mutualWarInvites import MutualWarInvites as mutualWarInvites
from eve.client.script.ui.services.windowsvc import WindowMgr as window
from eve.client.script.ui.services.uiColorSvc import UIColor as uiColor
from eve.client.script.ui.services.wrecksvc import WreckService as wreck
from eve.client.script.ui.shared.bookmarks.bookmarkSvc import BookmarkSvc as bookmarkSvc
from eve.client.script.ui.shared.bountySvc import BountyService as bountySvc
from eve.client.script.ui.shared.agencyNew.agencySvc import AgencySvc as agencyNew
from eve.client.script.ui.shared.epicArcSvc import EpicArcSvc as epicArc
from eve.client.script.ui.shared.comtool.focus import Focus as focus
from eve.client.script.ui.shared.comtool.onlineStatus import OnlineStatus as onlineStatus
from eve.client.script.ui.shared.incursionSvc import IncursionSvc as incursion
from eve.client.script.ui.shared.infoPanels.infoPanelSvc import InfoPanelSvc as infoPanel
from eve.client.script.ui.shared.inventory.filterSvc import ItemFilterSvc as itemFilter
from eve.client.script.ui.shared.loading import Loading as loading
from eve.client.script.ui.shared.maps.mapSvc import MapSvc as map
from eve.client.script.ui.shared.maps.starMapSvc import StarMapSvc as starmap
from eve.client.script.ui.shared.maps.systemMapSvc import SystemMapSvc as systemmap
from eve.client.script.ui.shared.market.quote import MarketUtils as marketutils
from eve.client.script.ui.shared.marketSvc import Market as market
from eve.client.script.ui.shared.neocom.addressBook.addressbookService import AddressBookSvc as addressbook
from eve.client.script.ui.shared.neocom.assetsinfo import AssetsSvc as assets
from eve.client.script.ui.shared.neocom.charactersheet import CharacterSheet as charactersheet
from eve.client.script.ui.shared.neocom.contracts.contracts import ContractsSvc as contracts
from eve.client.script.ui.shared.neocom.corporation.base_corporation_ui import CorporationUI as corpui
from eve.client.script.ui.shared.neocom.journal import JournalSvc as journal
from eve.client.script.ui.shared.neocom.neocom.neocomSvc import NeocomSvc as neocom
from eve.client.script.ui.shared.neocom.petition import PetitionSvc as petition
from eve.client.script.ui.shared.neocom.wallet.loyaltyPointsWalletSvc import LoyaltyPointsWalletSvc as loyaltyPointsWalletSvc
from eve.client.script.ui.shared.neocom.wallet.walletSvc import WalletSvc as wallet
from eve.client.script.ui.shared.planet.planetUISvc import PlanetUISvc as planetUI
from eve.client.script.ui.shared.preview import Preview as preview
from eve.client.script.ui.shared.radialMenu.radialMenuSvc import RadialMenuSvc as radialmenu
from cosmetics.client.cosmeticsSvc import CosmeticsService as cosmeticsSvc
from cosmetics.client.cosmeticsLicenseSvc import CosmeticsLicenseService as cosmeticsLicenseSvc
from eve.client.script.ui.shared.uilog import Logger as logger
from eve.client.script.ui.station.agents.agents import Agents as agents
from eve.client.script.ui.station.base import StationSvc as station
from eve.client.script.ui.station.insurance.base_insurance import InsuranceSvc as insurance
from eve.client.script.ui.station.loyaltyPointStore.lpStoreSvc import LPStoreSvc as lpstore
from eve.client.script.ui.station.pvptrade.pvptradesvc import PVPTradeService as pvptrade
from eve.client.script.ui.station.repairshop.base_repairshop import RepairSvc as repair
from eve.client.script.ui.station.securityOfficeSvc import SecurityOfficeService as securityOfficeSvc
from eve.client.script.ui.util.form import Form as form
from eve.client.script.util.jumpMonitor import jumpMonitor
from eve.client.script.util.profiling import ProfilingScheduler as profiling
from eve.devtools.script.insider import InsiderService as insider
from eve.devtools.script.menu_charge import ChargeService as charge
from eve.devtools.script.menu_implant import ImplantService as implant
from eve.devtools.script.svc_ballparkExporter import BallparkExporterSvc as ballparkExporter
from eve.devtools.script.svc_console import ConsoleService as console
from eve.devtools.script.svc_copycat2 import CopycatService as copycat
from eve.devtools.script.svc_destroyableitems import destroyableItems
from eve.devtools.script.svc_fittingspawner import FittingSpawner as fittingspawner
from eve.devtools.script.svc_gridload import GridLoadSimulationTool
from eve.devtools.script.svc_gridutils import GridUtilService as gridutils
from eve.devtools.script.svc_invtools import InvTools as invtools
from eve.devtools.script.svc_modtest import ModTest as modtest
from eve.devtools.script.svc_poser import PoserService as poser
from eve.devtools.script.svc_settingsLoader import SettingsLoaderSvc as settingsLoader
from eve.devtools.script.svc_simulator import SimulatorService as capsim
from eve.devtools.script.svc_slash import SlashService as slash
from eve.devtools.script.svc_trainer import TrainerService as trainer
from eve.devtools.script.svc_typebrowser import TypeBrowser as itemdb
from eve.devtools.script.tournamentRefereeTools import AllianceTournamentSvc as allianceTournamentSvc
from eve.client.script.ui.shared.shipTree.shipTreeUISvc import ShipTreeUI as shipTreeUI
from eve.client.script.ui.shared.shipTree.shipTreeSvc import ShipTree as shipTree
from eve.client.script.util.clientPathfinderService import ClientPathfinderService as clientPathfinderService
from eve.client.script.util.publicQaToolsClient import PublicQaToolsClient as publicQaToolsClient
from eve.client.script.ui.podGuide.podGuideService import PodGuideService as podguide
from gatekeeper.client import GatekeeperService as gatekeeper
from homestation.client import Service as home_station
from notifications.client.notificationUI import NotificationUIService as notificationUIService
from achievements.client.achievementSvc import AchievementTrackerClientService as achievementSvc
from eve.client.script.environment.prefetchSvc import PrefetchSvc as prefetchSvc
from eve.client.script.ui.shared.fittingScreen.ghostFittingSvc import GhostFittingSvc as ghostFittingSvc
from abyss.client.abyssal_service import AbyssalService as abyss
from randomJump.client.randomJumpSvc import RandomJumpService as randomJumpSvc
from tacticalNavigation.tacticalNavigationService import TacticalNavigationService as tacticalNavigation
from projectdiscovery.client.projectdiscoveryClientSvc import ProjectDiscoveryClientService as projectDiscoveryClient
from resourcewars.client.rwservice import RWService as rwService
from security.client.securitySvc import SecurityService as securitySvc
from seasons.client.seasonservice import SeasonService as seasonService
from logcontrol.logcontrolsvc import LogControlSvc as logControlSvc
from eve.client.script.parklife.dbuffClient import DbuffClientService as dbuffClient
from eve.client.script.parklife.dotWeaponSvc import DotWeaponSvc as dotWeaponSvc
from uihighlighting.uihighlightingservice import UiHighlightingService as uiHighlightingService
from conversations.conversationswithhighlights.conversationservice import ConversationService as conversationService
from operations.client.eventdirector.eventdirector import OperationsEventDirector as operationsEventDirector
from fastcheckout.client.fastCheckoutClientService import FastCheckoutClientService as fastCheckoutClientService
from eve.client.script.ui.services.corporation.voting import CorporationVotes as corpvotes
from eve.client.script.ui.services.corporation.itemLocking import ItemLocking as lockedItems
from xmppchatclient.xmppchatsvc import XmppChatService as XmppChat
from eve.client.script.dogma.dynamicItemSvc import DynamicItemSvc as dynamicItemSvc
from loginrewards.client.seasonalLoginCampaignService import SeasonalLoginCampaignService as seasonalLoginCampaignService
from loginrewards.client.loginCampaignService import LoginCampaignService as loginCampaignService
from eve.client.script.ui.shared.zhReport.reportSvc import ReportService as reportClientSvc
from serenity.eveguard.client.eveguard_service import EveGuardService as eveGuardSvc
from eve.client.script.ui.services.nonDiminishingInjectionService import NonDiminishingInjection as nonDiminishingInjection
from missions.client.missionObjectivesTracker import MissionObjectivesTracker as missionObjectivesTracker
from bannedwords.client.bannedwords_client import BannedWordsClientService as bannedwords_client
from eve.client.script.ui.services.usure import YouSureBoutThat as usure
from eve.client.script.ui.shared.pointerTool.helpPointerSvc import HelpPointerSvc as helpPointer
from contextualOffers.client.contextualOffersSvc import ContextualOfferService as contextualOfferSvc
from raffles.client import RaffleService as raffleSvc
from evelink.client import LinkService as link
from pvpFilaments.client.pvpFilamentSvc import PVPFilamentService as pvpFilamentSvc
from eve.client.script.ui.shared.dynamicResource import DynamicResourceSvc as dynamicResourceSvc
from eveaudio.musicDebuggerSvc import MusicDebuggerSvc as musicDebugger
from evebannerads.banner_ad_service import BannerAdService as bannerAdService
from expertSystems.client import ExpertSystemService as expertSystemSvc
from eve.client.script.ui.shared.recommendation.recommendationSvc import RecommendationService as recommendationSvc
from milestones.client.milestoneSvc import MilestoneService as milestoneSvc
from uiblinker.service import UiBlinkerService as ui_blinker
from nodegraph.client.service import NodeGraphService as node_graph
from uihider import CommandBlockerService as command_blocker
from uihider.ui_hider_service import UiHiderService as uihider
from voidspace.client.void_space_service import VoidSpaceService as voidSpaceSvc
from stargate.client.gateJumpSvc import GateJumpSvc as gatejump
from assetholding.client.assetholding_svc import AssetHoldingService as assetHoldingSvc
from eve.client.script.ui.services.insurgencyCampaignSvc import InsurgencyCampaignSvc as insurgencyCampaignSvc
from eve.client.script.ui.services.insurgenceDashboardSvc import InsurgencyDashboardSvc as insurgencyDashboardSvc
from eve.client.script.ui.services.corruptionSuppressionSvc import CorruptionSuppressionSvc as corruptionSuppressionSvc
from eve.client.script.ui.services.towGameSvc import TowGameSvc as towGameSvc
from eve.client.script.ui.services.sovereigntyResourceSvc import SovereigntyResourceSvc as sovereigntyResourceSvc
from eve.client.script.ui.services.sovHubSvc import SovHubSvc as sovHubSvc
from moonmining.autoMoonMining.client.auto_moon_miner_service import AutoMoonMinerService as autoMoonMiner
from eve.client.script.ui.services.skyhookSvc import SkyhookSvc as skyhookSvc
from chat.client.chat_service import ChatSvc as chat
from eveaudio.eveMusicService import DynamicMusicService as dynamicMusic
from taleclient.tale_service import TaleService as tale
