#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\skillPlan\skillPlanUISignals.py
from signals import Signal
on_create_new_personal_button = Signal('on_create_new_personal_button')
on_create_new_corp_button = Signal('on_create_new_corp_button')
on_close_new_button = Signal('on_close_new_button')
on_edit_button = Signal('on_edit_button')
on_delete_button = Signal('on_delete_button')
on_selected = Signal('on_selected')
on_close_button = Signal('on_close_button')
on_skill_requirements_changed = Signal('on_skill_requirements_changed')
on_milestone_added = Signal('on_milestone_added')
on_milestone_removed = Signal('on_milestone_removed')
on_milestone_updated = Signal('on_milestone_updated')
on_skill_plan_cleared = Signal('on_skill_plan_cleared')
on_show_multi_training_msg = Signal('on_show_multi_training_msg')
on_show_alpha_training_msg = Signal('on_show_alpha_training_msg')
on_contents_list_started_reconstructing = Signal('on_contents_list_started_reconstructing')
on_contents_list_finished_reconstructing = Signal('on_contents_list_finished_reconstructing')
on_skill_collapse_changing = Signal('on_skill_collapse_changing')
