#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\sensorsuite\overlay\sitetype.py
ANOMALY = 1
SIGNATURE = 2
STATIC_SITE = 3
BOOKMARK = 4
MISSION = 6
STRUCTURE = 7
SHARED_BOOKMARK = 8
PERSONAL_SITE_TYPES = (BOOKMARK, MISSION, SHARED_BOOKMARK)
ALL_SITE_TYPES = {ANOMALY,
 SIGNATURE,
 STATIC_SITE,
 BOOKMARK,
 MISSION,
 STRUCTURE,
 SHARED_BOOKMARK}
STRUCTURE_SITE_TYPES = {STRUCTURE}
NON_STRUCTURE_SITE_TYPES = ALL_SITE_TYPES - STRUCTURE_SITE_TYPES

def IsSiteInstantlyAccessible(siteData):
    return siteData.siteType in PERSONAL_SITE_TYPES
