#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\milestones\common\constants.py
from carbon.common.lib.const import MIN
MILESTONE_REWARD_NUMBER_OF_MINUTES = 120
MILESTONE_REWARD_NUMBER_OF_MINUTES_GRACE_PERIOD = MILESTONE_REWARD_NUMBER_OF_MINUTES - 1
MILESTONE_REWARD_MINUTES = MILESTONE_REWARD_NUMBER_OF_MINUTES * MIN
MILESTONE_REWARD_USER_FIRST_LOGON_HOURS_THRESHOLD = 24
MILESTONE_HUNDRED_AND_TWENTY_MINUTES_ID = 1
MINUTE_MS = 60000
MILESTONE_HUNDRED_AND_TWENTY_MINUTES_REWARD_AMOUNT = 500000
