#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\uihighlighting\uniqueNameConst.py
UNIQUE_UI_PREFIX = 'unique_UI_'
NEOCOM_PREFIX = 'neocom.'
STATION_SERVICE_PREFIX = 'unique_ui_stationSvc_'
AGENCY_TAB_PREFIX = 'unique_ui_agency_tab_'
AGENCY_CARD_PREFIX = 'unique_ui_agency_card_'
AGENCY_PAGE_PREFIX = 'unique_ui_agency_page_'
ALLOWS_POINTER_CLIPPING = 'allowsPointerClipping'
NEOCOM_PANEL_PREFIX = 'unique_panel.'
SKILL_PLAN_PREFIX = 'unique_ui_skill_plan_'
SKILL_PLAN_FACTION_PREFIX = 'unique_ui_skill_faction_'
SKILL_PLAN_CAREER_PREFIX = 'unique_ui_skill_career_'
SKILL_PLAN_BTN_PREFIX = 'unique_ui_skill_btn_'

def GetUniquePointerName(pointerName):
    return '%s%s' % (UNIQUE_UI_PREFIX, pointerName)


def GetUniqueNeocomPointerName(pointerName):
    return '%s%s' % (NEOCOM_PREFIX, pointerName)


def GetUniquePanelPointerName(pointerName):
    return '%s%s' % (NEOCOM_PANEL_PREFIX, pointerName)


def GetUniqueStationServiceName(pointerName):
    return '%s%s' % (STATION_SERVICE_PREFIX, pointerName)


def GetUniqueAgencyTabName(pointerName):
    return '%s%s' % (AGENCY_TAB_PREFIX, pointerName)


def GetUniqueAgencyCardName(pointerName):
    return '%s%s' % (AGENCY_CARD_PREFIX, pointerName)


def GetUniqueAgencyContentPageName(pointerName):
    return '%s%s' % (AGENCY_PAGE_PREFIX, pointerName)


def GetUniqueSkillPlanName(skillPlanID):
    return '%s%s' % (SKILL_PLAN_PREFIX, skillPlanID)


def GetUniqueSkillPlanFactionName(careerPathID, factionID):
    return '%s%s_%s' % (SKILL_PLAN_FACTION_PREFIX, careerPathID, factionID)


def GetUniqueSkillPlanCareerName(careerPathID):
    return '%s%s' % (SKILL_PLAN_CAREER_PREFIX, careerPathID)


def GetUniqueSkillPlanBtn(skillPlanID, BTN_ID):
    return '%s%s_%s' % (SKILL_PLAN_BTN_PREFIX, skillPlanID, BTN_ID)


UNIQUE_NAME_ACP_CLAIM_ALL_BUTTON = GetUniquePointerName('acpClaimAllButton')
UNIQUE_NAME_ACP_REWARDS_CONTAINER = GetUniquePointerName('acpRewardsContainer')
UNIQUE_NAME_ACTIVE_OPPORTUNITIES = GetUniquePointerName('activeOpportunities')
UNIQUE_NAME_FLEET_ACTIVE_RECLONERS_TAB = GetUniquePointerName('activeReclonersTab')
UNIQUE_NAME_AGENCY = GetUniquePointerName('agencyWindow')
UNIQUE_NAME_AGENT_MISSION_INFO_PANEL = GetUniquePointerName('agentMissionInfoPanel')
UNIQUE_NAME_AIR_NPE_INFO_PANEL = GetUniquePointerName('airNpeInfoPanel')
UNIQUE_NAME_ALLIANCE_FIT_FILTER = GetUniquePointerName('allianceFitFilter')
UNIQUE_NAME_APPLY_SP_BTN = GetUniquePointerName('applySkillPointsBtn')
UNIQUE_NAME_AUGMENTATIONS_TAB = GetUniquePointerName('augmentationsTab')
UNIQUE_NAME_AUTOPILOT_SETTINGS = GetUniquePointerName('autopilotSettings')
UNIQUE_NAME_AVAILABLE_CONTRACTS_TAB = GetUniquePointerName('availableContractsTab')
UNIQUE_NAME_BADGE_MASTER = GetUniquePointerName('badgeMaster')
UNIQUE_NAME_BOOKMARKS_TAB = GetUniquePointerName('bookmarkLocations')
UNIQUE_NAME_BROADCAST_ARMOR = GetUniquePointerName('broadcastNeedArmor')
UNIQUE_NAME_BROADCAST_SHIELD = GetUniquePointerName('broadcastNeedShield')
UNIQUE_NAME_EFFECTS_BAR = GetUniquePointerName('buffBarContainer')
UNIQUE_NAME_SHOW_BUY_ALL_BTN = GetUniquePointerName('buyAllBtn')
UNIQUE_NAME_MARKET_BUYER_LIST = GetUniquePointerName('buyersList')
UNIQUE_NAME_CAMERA_ORBIT = GetUniquePointerName('cameraButtonOrbit')
UNIQUE_NAME_CAMERA_POV = GetUniquePointerName('cameraButtonPOV')
UNIQUE_NAME_CAMERA_TACTICAL = GetUniquePointerName('cameraButtonTactical')
UNIQUE_NAME_CAPACITOR = GetUniquePointerName('CapacitorContainer')
UNIQUE_NAME_CAREER_INFO_PANEL = GetUniquePointerName('careerProgramInfoPanel')
UNIQUE_NAME_CHANNEL_WND = GetUniquePointerName('channelWindow')
UNIQUE_NAME_CHARSHEET_CHARACTER_TAB = GetUniquePointerName('charactersheetCharacterTab')
UNIQUE_NAME_EMBLEMS_TAB = GetUniquePointerName('charactersheetEmblemsTab')
UNIQUE_NAME_CHARSHEET_INTERACTION_TAB = GetUniquePointerName('charactersheetInteractionTab')
UNIQUE_NAME_PERSONALIZATION_TAB = GetUniquePointerName('charactersheetPersonalizationTab')
UNIQUE_NAME_SKINS_TAB = GetUniquePointerName('charactersheetSkinsTab')
UNIQUE_NAME_CHAT_STACK = GetUniquePointerName('chatStack')
UNIQUE_NAME_CLOCK_CALENDAR = GetUniquePointerName('clockAndCalendar')
UNIQUE_NAME_COMBAT_LOG_TAB = GetUniquePointerName('combatLogTab')
UNIQUE_NAME_COMMUNITY_FIT_FILTER = GetUniquePointerName('communityFitFilter')
UNIQUE_NAME_CONTRACT_AVAILABILITY_SETTINGS = GetUniquePointerName('contractAvailabilitySetting')
UNIQUE_NAME_CORP_ADMIN_TAB = GetUniquePointerName('corpAdminTab')
UNIQUE_NAME_CORP_ALLIANCES_TAB = GetUniquePointerName('corpAlliancesTab')
UNIQUE_NAME_CORP_ASSETS_TAB = GetUniquePointerName('corpAssetsTab')
UNIQUE_NAME_CORP_BULLETIN_TAB = GetUniquePointerName('corpBulletin')
UNIQUE_NAME_CORP_CHAT = GetUniquePointerName('corpChannelWnd')
UNIQUE_NAME_CORP_CHAT_RELOAD_MOTD = GetUniquePointerName('corpChatReloadMotd')
UNIQUE_NAME_CORP_CHAT_SETTINGS = GetUniquePointerName('corpChatSettings')
UNIQUE_NAME_CORP_CORPORATION_TAB = GetUniquePointerName('corpCorporationTab')
UNIQUE_NAME_CORP_FIT_FILTER = GetUniquePointerName('corpFitFilter')
UNIQUE_NAME_CORP_HOME_TAB = GetUniquePointerName('corpHome')
UNIQUE_NAME_CORP_PROJECTS = GetUniquePointerName('corpProjects')
UNIQUE_NAME_CORVETTE_BTN = GetUniquePointerName('corvetteBtn')
UNIQUE_NAME_CREATE_CHANNEL_BTN = GetUniquePointerName('createChatChannelBtn')
UNIQUE_NAME_CRIMEWATCH_TIMERS = GetUniquePointerName('crimewatchTimers')
UNIQUE_NAME_CURRENT_FIT = GetUniquePointerName('currentFit')
UNIQUE_NAME_DRONE_SETTINGS = GetUniquePointerName('droneSettingIcon')
UNIQUE_NAME_DRONE_WND = GetUniquePointerName('droneView')
UNIQUE_NAME_DIRECTIONAL_SCANNER = GetUniquePointerName('DscanWnd')
UNIQUE_NAME_EVE_MENU_BTN = GetUniquePointerName('eveMenuBtn')
UNIQUE_NAME_EXPAND_CHARSHEET = GetUniquePointerName('expandCharacterSheet')
UNIQUE_NAME_EXPERT_SYSTEMS_TAB = GetUniquePointerName('expertSystemsTab')
UNIQUE_NAME_FIGHTERS_DETACH = GetUniquePointerName('fighterDetach')
UNIQUE_NAME_FIGHTERS_TOGGLE = GetUniquePointerName('fighterToggle')
UNIQUE_NAME_FILTER_SCAN_RESULTS = GetUniquePointerName('filterScanResults')
UNIQUE_NAME_FIND_NEW_CORP = GetUniquePointerName('findNewCorp')
UNIQUE_NAME_MARKET_FIND_IN_BROWSER = GetUniquePointerName('findTypeInBrowser')
UNIQUE_NAME_FITS_IN_FITTING_WND = GetUniquePointerName('fitsInFittingWnd')
UNIQUE_NAME_FITTING_BROWSER = GetUniquePointerName('fittingBrowser')
UNIQUE_NAME_FITTING_CAP = GetUniquePointerName('fittingCap')
UNIQUE_NAME_FITTING_DEFENSE = GetUniquePointerName('fittingDefense')
UNIQUE_NAME_FITTING_DRONES = GetUniquePointerName('fittingDrones')
UNIQUE_NAME_FITTING_EQUIPMENT = GetUniquePointerName('fittingEquipment')
UNIQUE_NAME_FITTING_FIGHTERS = GetUniquePointerName('fittingFighters')
UNIQUE_NAME_FITTING_FUEL = GetUniquePointerName('fittingFuel')
UNIQUE_NAME_FITTING_INVENTORY = GetUniquePointerName('fittingInventoryBrowser')
UNIQUE_NAME_FITTING_NAVIGATION = GetUniquePointerName('fittingNavigation')
UNIQUE_NAME_FITTING_OFFENSE = GetUniquePointerName('fittingOffense')
UNIQUE_NAME_FITTING_PERSONALIZATION = GetUniquePointerName('fittingPersonalization')
UNIQUE_NAME_FITTING_SKIN_BROWSER = GetUniquePointerName('fittingSkins')
UNIQUE_NAME_FITING_STATS = GetUniquePointerName('fittingStats')
UNIQUE_NAME_FITTING_TARGETING = GetUniquePointerName('fittingTargeting')
UNIQUE_NAME_FLEET_BROADCAST_ICONS = GetUniquePointerName('fleetBroadcastIcons')
UNIQUE_NAME_FLEET_BROADCAST_SCOPE = GetUniquePointerName('fleetBroadcastScope')
UNIQUE_NAME_FLEET_CHAT = GetUniquePointerName('fleetChat')
UNIQUE_NAME_FLEET_CHAT_RELOAD_MOTD = GetUniquePointerName('fleetChatReloadMotd')
UNIQUE_NAME_FLEET_CHAT_SETTINGS = GetUniquePointerName('fleetChatSettings')
UNIQUE_NAME_FLEET_FINDER_SETTINGS = GetUniquePointerName('fleetFinderSettings')
UNIQUE_NAME_FLEET_FINDER_TAB = GetUniquePointerName('fleetFinderTab')
UNIQUE_NAME_FLEET_HISTORY_FILTER = GetUniquePointerName('fleetHistoryFilter')
UNIQUE_NAME_FLEET_HISTORY_TAB = GetUniquePointerName('fleetHistoryTab')
UNIQUE_NAME_FLEET_SETTINGS = GetUniquePointerName('fleetSettings')
UNIQUE_NAME_GROUP_WEAPONS = GetUniquePointerName('groupWeapons')
UNIQUE_NAME_FITTING_HARDWARE = GetUniquePointerName('hardwareInFittingWnd')
UNIQUE_NAME_HELP_CENTER_BTN = GetUniquePointerName('helpCenterBtn')
UNIQUE_NAME_CHARSHEET_HOME_TAB = GetUniquePointerName('homeTab')
UNIQUE_NAME_HUD_BUTTONS = GetUniquePointerName('hudButtons')
UNIQUE_NAME_HUD_CENTER = GetUniquePointerName('hudCenter')
UNIQUE_NAME_HUD_CONTAINER = GetUniquePointerName('hudContainer')
UNIQUE_NAME_HUD_READOUT = GetUniquePointerName('hudReadout')
UNIQUE_NAME_HUD_SETTINGS = GetUniquePointerName('hudSettingsMenu')
UNIQUE_NAME_INDUSTRY_BP_BTN = GetUniquePointerName('industryBlueprintsTab')
UNIQUE_NAME_INDUSTRY_COPY_BTN = GetUniquePointerName('industryCopyBtn')
UNIQUE_NAME_INDUSTRY_FACILITIES_TAB = GetUniquePointerName('industryFacilitiesTab')
UNIQUE_NAME_INDUSTRY_INPUT = GetUniquePointerName('industryInputLocation')
UNIQUE_NAME_INDUSTRY_JOBS_TAB = GetUniquePointerName('industryJobsTab')
UNIQUE_NAME_INDUSTRY_OUTPUT = GetUniquePointerName('industryOutputLocation')
UNIQUE_NAME_INDUSTRY_RESEARCH_TAB = GetUniquePointerName('industryResearchTab')
UNIQUE_NAME_AUTOPILOT_BTN = GetUniquePointerName('inFlightAutopilotBtn')
UNIQUE_NAME_HUD_CARGO_BTN = GetUniquePointerName('inFlightCargoBtn')
UNIQUE_NAME_SCANNER_BTN = GetUniquePointerName('inFlightScannerBtn')
UNIQUE_NAME_TACTICAL_BTN = GetUniquePointerName('inFlightTacticalBtn')
UNIQUE_NAME_INFO_PANEL_BTNS = GetUniquePointerName('infoPanelBtns')
UNIQUE_NAME_INFO_PANEL = GetUniquePointerName('infoPanelContainer')
UNIQUE_NAME_INDUSTRY_INVENTION_BTN = GetUniquePointerName('inventionBtn')
UNIQUE_NAME_INVENTORY_VIEW = GetUniquePointerName('inventoryListView')
UNIQUE_NAME_INVENTORY_STACK_ALL = GetUniquePointerName('inventoryStackAll')
UNIQUE_NAME_LOCATION_ITEMS = GetUniquePointerName('itemsInSystem')
UNIQUE_NAME_JUMP_CLONES_TAB = GetUniquePointerName('jumpClonesTab')
UNIQUE_NAME_SHOW_KILL_RIGHTS_TAB = GetUniquePointerName('killRightsTab')
UNIQUE_NAME_LOBBY_WND = GetUniquePointerName('lobbyWnd')
UNIQUE_NAME_LOCAL_CHAT = GetUniquePointerName('localChat')
UNIQUE_NAME_LOCATION_INFO_PANEL = GetUniquePointerName('locationInfoPanel')
UNIQUE_NAME_INDUSTRY_MANUF_BTN = GetUniquePointerName('manufacturingBtn')
UNIQUE_NAME_MAP_COLOR_SETTINGS = GetUniquePointerName('mapColorSettings')
UNIQUE_NAME_MARKET_BROWSE_SETTINGS = GetUniquePointerName('marketBrowseSettings')
UNIQUE_NAME_MARKET_BUYERS_JUMP_COL = GetUniquePointerName('marketBuyersJumpsColumn')
UNIQUE_NAME_MARKET_BUYERS_PRICE_COL = GetUniquePointerName('marketBuyersPriceColumn')
UNIQUE_NAME_MARKET_BUYERS_QTY_COL = GetUniquePointerName('marketBuyersQtyColumn')
UNIQUE_NAME_MARKET_DATA = GetUniquePointerName('marketDataTab')
UNIQUE_NAME_MARKET_DETAILS = GetUniquePointerName('marketDetailsTab')
UNIQUE_NAME_MARKET_PRICE_HISTORY = GetUniquePointerName('marketPriceHistoryTab')
UNIQUE_NAME_MARKET_SELLERS_JUMP_COL = GetUniquePointerName('marketSellersJumpsColumn')
UNIQUE_NAME_MARKET_SELLERS_PRICE_COL = GetUniquePointerName('marketSellersPriceColumn')
UNIQUE_NAME_MARKET_SELLERS_QTY_COL = GetUniquePointerName('marketSellersQtyColumn')
UNIQUE_NAME_INDUSTRY_ME_BTN = GetUniquePointerName('materialEfficiencyBtn')
UNIQUE_NAME_MISSION_INFO_PANEL = GetUniquePointerName('missionInfoPanel')
UNIQUE_NAME_MY_APPLICATIONS = GetUniquePointerName('myApplications')
UNIQUE_NAME_FLEET_MY_FLEET_TAB = GetUniquePointerName('myFleetTab')
UNIQUE_NAME_MY_WALLET_TAB = GetUniquePointerName('myWallet')
UNIQUE_NAME_NEOCOM = GetUniquePointerName('Neocom')
UNIQUE_NAME_NEW_EDEN_STORE_PLEX_AMOUNT = GetUniquePointerName('newEdenStorePlexAmount')
UNIQUE_NAME_NEXT_IN_ROUTE = GetUniquePointerName('nextInRoute')
UNIQUE_NAME_NOTIFICATION_CONTAINER = GetUniquePointerName('notificationContainer')
UNIQUE_NAME_NOTIFICATION_FEED = GetUniquePointerName('notificationFeed')
UNIQUE_NAME_NOTIFICATION_POPUP = GetUniquePointerName('notificationPopup')
UNIQUE_NAME_TUTORIAL_INFO_PANEL = GetUniquePointerName('operationsInfoPanel')
UNIQUE_NAME_OPPORTUNITY_BROWSER = GetUniquePointerName('opportunitiesBrowser')
UNIQUE_NAME_OPPORTUNITY_FILTERS = GetUniquePointerName('opportunityFilters')
UNIQUE_NAME_OPPORTUNITY_REWARDS = GetUniquePointerName('opportunityRewards')
UNIQUE_NAME_MARKET_ORDER_DURATION = GetUniquePointerName('orderDuration')
UNIQUE_NAME_OVERVIEW_SETTINGS = GetUniquePointerName('overviewHeaderIcon')
UNIQUE_NAME_OVERVIEW_WND = GetUniquePointerName('overviewWnd')
UNIQUE_NAME_PILOT_SERVICES_TAB = GetUniquePointerName('pilotServicesTab')
UNIQUE_NAME_PROBE_FORMATIONS = GetUniquePointerName('probeFormationCont')
UNIQUE_NAME_PROBE_SCANNER = GetUniquePointerName('probeScanner')
UNIQUE_NAME_PROBE_REFRESH = GetUniquePointerName('probeScannerRefresh')
UNIQUE_NAME_PROBE_SIZE_MODIFIER = GetUniquePointerName('probeSizeModifier')
UNIQUE_NAME_RECOMMENDATIONS_INFO_PANEL = GetUniquePointerName('recommendationsInfoPanel')
UNIQUE_NAME_RECOVER_PROBES = GetUniquePointerName('recoverProbes')
UNIQUE_NAME_RECRUITEMENT_TAB = GetUniquePointerName('recruitementTab')
UNIQUE_NAME_RELEASE_CONTROL = GetUniquePointerName('releaseControl')
UNIQUE_NAME_REPROCESS_BUTTON = GetUniquePointerName('reprocessButton')
UNIQUE_NAME_START_TRAINING_BTN = GetUniquePointerName('resumePauseTrainingBtn')
UNIQUE_NAME_ROUTE_INCLUDE_JUMP_GATES = GetUniquePointerName('routeIncludeJumpGates')
UNIQUE_NAME_INFO_PANEL_ROUTE = GetUniquePointerName('routeInInfoPanel')
UNIQUE_NAME_ROUTE_SAFER = GetUniquePointerName('routePreferSafer')
UNIQUE_NAME_ROUTE_SHORTER = GetUniquePointerName('routePreferShorter')
UNIQUE_NAME_SAFETY_BUTTON = GetUniquePointerName('SafetyButton')
UNIQUE_NAME_SEARCH_INFO_PANEL = GetUniquePointerName('searchInfoPanel')
UNIQUE_NAME_SEASONS_INFO_PANEL = GetUniquePointerName('seasonsInfoPanel')
UNIQUE_NAME_SECURITY_STATUS_TAB = GetUniquePointerName('securityStatusTab')
UNIQUE_NAME_SELECTED_ITEM_VIEW = GetUniquePointerName('selectedItemView')
UNIQUE_NAME_MARKET_SELLER_LIST = GetUniquePointerName('sellersList')
UNIQUE_NAME_SENSOR_OVERLAY = GetUniquePointerName('sensorOverlay')
UNIQUE_NAME_SENSOR_OVERLAY_SETTING = GetUniquePointerName('sensorOverlaySetting')
UNIQUE_NAME_FULL_SPEED_BTN = GetUniquePointerName('setFullspeed')
UNIQUE_NAME_SHIP_HEALTH = GetUniquePointerName('shipHealth')
UNIQUE_NAME_FLEET_SHOW_BROADCASTS = GetUniquePointerName('showHideBroadcasts')
UNIQUE_NAME_SHOW_CONTRACT_OPTIONS = GetUniquePointerName('showHideContractOptions')
UNIQUE_NAME_SHOW_KILLS_LOSSES = GetUniquePointerName('showKillsLosses')
UNIQUE_NAME_SIMULATE_SHIP = GetUniquePointerName('simulateShip')
UNIQUE_NAME_SKILL_CATALOGUE_TAB = GetUniquePointerName('skill_catalogue_tab')
UNIQUE_NAME_SKILL_PLANS_TAB = GetUniquePointerName('skill_plans_tab')
UNIQUE_NAME_SKILL_PLANS_CERTIFIED_TAB = GetUniquePointerName('skillplans_certified_tab')
UNIQUE_NAME_SKILL_PLANS_CORP_TAB = GetUniquePointerName('skillplans_corp_tab')
UNIQUE_NAME_SKILL_PLANS_PERSONAL_TAB = GetUniquePointerName('skillplans_personal_tab')
UNIQUE_NAME_SKILLQUEUE = GetUniquePointerName('skillqueue')
UNIQUE_NAME_SKINR_COLLECTION = GetUniquePointerName('skinrCollection')
UNIQUE_NAME_SKINR_PARAGON_HUB = GetUniquePointerName('skinrParagonHub')
UNIQUE_NAME_SKINR_STUDIO = GetUniquePointerName('skinrStudio')
UNIQUE_NAME_MODULE_SLOTS = GetUniquePointerName('slotsContainer')
UNIQUE_NAME_CHAR_STANDINGS_TAB = GetUniquePointerName('standingsTabInCharactersheet')
UNIQUE_NAME_AGENTS_TAB = GetUniquePointerName('stationSvcAgents')
UNIQUE_NAME_HANGARS_TAB = GetUniquePointerName('stationSvcHangars')
UNIQUE_NAME_OFFICES_TAB = GetUniquePointerName('stationSvcOffices')
UNIQUE_NAME_STOP_BUTTON = GetUniquePointerName('StopButton')
UNIQUE_NAME_SYSTEM_EFFECTS = GetUniquePointerName('systemEffects')
UNIQUE_NAME_SYSTEM_NAME_BTN = GetUniquePointerName('systemNameLabel')
UNIQUE_NAME_SYSTEM_SECURITY_BTN = GetUniquePointerName('systemSecurityLabel')
UNIQUE_NAME_TARGET_ANCHOR = GetUniquePointerName('targetAnchor')
UNIQUE_NAME_INDUSTRY_TE_BTN = GetUniquePointerName('timeEfficiencyBtn')
UNIQUE_NAME_UNDOCK_BTN = GetUniquePointerName('undockBtn')
UNIQUE_NAME_VARIATION_TAB = GetUniquePointerName('variationTab')
UNIQUE_NAME_WALLET_MARKET_TRANSACTIONS = GetUniquePointerName('walletMarketTransactions')
UNIQUE_NAME_WALLET_TRANSACTIONS_TAB = GetUniquePointerName('walletTransactions')
UNIQUE_NAME_CAREER_AGENT_INTERACTION_BTN = 'Agency_CareerAgents_InteractionButton'
UNIQUE_NAME_INSTRUCTIONS_CONVO = 'InstructionsConversationWindow'
