#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\characterenergy\const.py
DEFAULT_INCREASE_PER_RECHARGE_TICK = 4.4
DEFAULT_RECHARGE_TICK_PERIOD = 3600
DEFAULT_MIN_ENERGY_LEVEL = 0
DEFAULT_QUIESCENT_ENERGY_LEVEL = 100
if DEFAULT_MIN_ENERGY_LEVEL >= DEFAULT_QUIESCENT_ENERGY_LEVEL:
    raise RuntimeError('DEFAULT_MIN_ENERGY_LEVEL must be less than DEFAULT_QUIESCENT_ENERGY_LEVEL')
