#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\factionwarfare\const.py
ADJACENCY_STATE_FRONTLINE = 'FL'
ADJACENCY_STATE_SECONDLINE = 'SL'
ADJACENCY_STATE_BACKLINE = 'BL'
ADJACENCY_STATES = {ADJACENCY_STATE_FRONTLINE, ADJACENCY_STATE_SECONDLINE, ADJACENCY_STATE_BACKLINE}
ADJACENCY_STATE_DEBUG_NAMES = {ADJACENCY_STATE_FRONTLINE: 'Front-line',
 ADJACENCY_STATE_SECONDLINE: 'Second-line',
 ADJACENCY_STATE_BACKLINE: 'Back-line'}
ADJACENCY_STATE_LP_MULTIPLIER = {ADJACENCY_STATE_FRONTLINE: 1.5,
 ADJACENCY_STATE_SECONDLINE: 1.0,
 ADJACENCY_STATE_BACKLINE: 0.01}
MAX_VICTORY_POINTS_OVER_THRESHOLD = 500
VICTORY_POINTS_THRESHOLD = 75000
PIRATE_WIN_VICTORY_POINTS_OVER_THRESHOLD = 100
OBJECTIVE_MODE_SUPPLY_DEPOT = 'SUPPLY_DEPOT'
OBJECTIVE_MODE_SUPPLY_CACHE = 'SUPPLY_CACHE'
OBJECTIVE_MODE_PROPAGANDA = 'PROPAGANDA'
OBJECTIVE_MODE_LISTENING_POST = 'LISTENING_POST'
OBJECTIVE_MODE_RENDEZVOUS_POINT = 'RENDEZVOUS_POINT'
GATE_CONNECTIONS_REQUIRING_OCCUPIER = {}
ENLISTMENT_COOLDOWN_SECONDS = 86400
