#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\cosmetics\client\ships\ship_skin_signals.py
from signals import Signal
on_skin_state_set = Signal('on_skin_state_set')
on_skin_state_reapplied = Signal('on_skin_state_reapplied')
on_skin_sequencing_job_updated = Signal()
on_skin_sequencing_job_failed = Signal()
on_skin_sequencing_job_completed = Signal()
on_skin_sequencing_cache_invalidated = Signal()
on_skin_design_saved = Signal('on_skin_design_saved')
on_skin_design_deleted = Signal('on_skin_design_deleted')
on_skin_license_activated = Signal('on_skin_license_activated')
on_skin_license_added = Signal('on_skin_license_added')
on_skin_license_updated = Signal('on_skin_license_updated')
on_skin_license_deleted = Signal('on_skin_license_deleted')
on_skin_listing_cache_invalidated = Signal('on_skin_listing_cache_invalidated')
on_skin_listing_expired = Signal('on_skin_listing_expired')
on_component_license_granted = Signal('on_component_license_granted')
on_component_license_cache_invalidated = Signal('on_component_license_cache_invalidated')
on_component_listing_cache_invalidated = Signal('on_component_listing_cache_invalidated')
on_ship_skinr_feature_availability_changed = Signal('on_ship_skinr_feature_availability_changed')
on_skin_hub_offers_availability_changed = Signal('on_skin_hub_offers_availability_changed')
on_are_st_patrick_component_listings_available_changed = Signal('on_are_st_patrick_component_listings_available_changed')
on_ship_skin_sequencing_cost_discount_changed = Signal('on_ship_skin_sequencing_cost_discount_changed')
