#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\xmppchatclient\const.py
from chatutil.const import *
ERROR_WRONG_PASSWORD = '401'
ERROR_CHANNEL_UNAVAILABLE = '403'
ERROR_LACKING_CONTROL_RIGHTS = '405'
ERROR_CONSTRAINED = '500'
ERROR_CANT_JOIN_CHANNEL = '407'
UNCLOSABLE_CHAT_WNDS = (CATEGORY_LOCAL,
 CATEGORY_WORMHOLE,
 CATEGORY_NULLSEC,
 CATEGORY_CORP,
 CATEGORY_LOCAL_SUPPRESSED,
 CATEGORY_TRIGLAVIAN)
MESSAGEMODE_TEXTONLY = 0
MESSAGEMODE_SMALLPORTRAIT = 1
MESSAGEMODE_BIGPORTRAIT = 2
CHANNELS_WITH_SPECIAL_PRESENCE_HANDLING = (CATEGORY_LOCAL,)
SINGLE_WND_CATEGORIES = [CATEGORY_FLEET,
 CATEGORY_CORP,
 CATEGORY_ALLIANCE,
 CATEGORY_LOCAL,
 CATEGORY_WORMHOLE,
 CATEGORY_NULLSEC,
 CATEGORY_FACTION,
 CATEGORY_RW,
 CATEGORY_WARFACTION,
 CATEGORY_LOCAL_SUPPRESSED,
 CATEGORY_TRIGLAVIAN]
PROXY_CONTROLLED_CATEGORIES = [CATEGORY_LOCAL,
 CATEGORY_WORMHOLE,
 CATEGORY_NULLSEC,
 CATEGORY_ALLIANCE,
 CATEGORY_CORP,
 CATEGORY_FLEET,
 CATEGORY_FACTION,
 CATEGORY_TRIGLAVIAN]
SYSTEM_CHANNEL_MAX_CHANNELID = 120
CHANNELS_WITH_NO_PRESENCE_BROADCAST = (CATEGORY_ALLIANCE,
 CATEGORY_WORMHOLE,
 CATEGORY_NULLSEC,
 CATEGORY_FACTION,
 CATEGORY_RW,
 CATEGORY_INCURSION,
 CATEGORY_TRIGLAVIAN)
EVENT_PREFIX = 'xmppchatsvc::'
EVENT_LOGIN = EVENT_PREFIX + 'Login'
