#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\spacecomponents\common\componentConst.py
DEPLOY_CLASS = 'deploy'
ACTIVATE_CLASS = 'activate'
DOGMATIC_CLASS = 'dogmatic'
SCOOP_CLASS = 'scoop'
DECAY_CLASS = 'decay'
FITTING_CLASS = 'fitting'
CARGO_BAY = 'cargoBay'
CYNO_INHIBITOR_CLASS = 'cynoInhibitor'
CYNO_BEACON_GENERATOR_CLASS = 'cynoBeaconGenerator'
REINFORCE_CLASS = 'reinforce'
AUTO_TRACTOR_BEAM_CLASS = 'autoTractorBeam'
AUTO_LOOTER_CLASS = 'autoLooter'
BOOKMARK_CLASS = 'bookmark'
SIPHON_CLASS = 'siphon'
PHYSICS_CLASS = 'physics'
SCAN_BLOCKER_CLASS = 'scanBlocker'
MICRO_JUMP_DRIVER_CLASS = 'microJumpDriver'
WARP_DISRUPTION_CLASS = 'warpDisruption'
BEHAVIOR = 'behavior'
NPC_PILOT = 'npcpilot'
TURBO_SHIELD_CLASS = 'turboShield'
SHIP_GROUP_CLASS = 'shipGroup'
PROXIMITY_SENSOR_CLASS = 'proximitySensor'
TARGETING = 'targeting'
ENTOSIS_COMMAND_NODE = 'entosisCommandNode'
ENTOSIS_SOVEREIGNTY_STRUCTURE = 'entosisSovereigntyStructure'
ENTOSIS_LOOT_TARGET = 'entosisLootTarget'
NPC_WARP_BEACON = 'npcWarpBeacon'
ITEM_TRADER = 'itemTrader'
JUMP_POLARIZATION_CLASS = 'jumpPolarization'
FIGHTER_SQUADRON_CLASS = 'fighterSquadron'
BILLBOARD_CLASS = 'billboard'
AUTO_WARP_SCRAMBLER_CLASS = 'autoWarpScrambler'
SOF_OWNER_MAPPER_CLASS = 'sofOwnerMapper'
DYNAMIC_ENTITY_NAME_CLASS = 'dynamicEntityName'
ENTITY_STANDINGS_CLASS = 'entityStandings'
ENTITY_BOUNTY_CLASS = 'entityBounty'
IGNORE_FITTING_RESTRICTIONS_CLASS = 'ignoreFittingRestrictions'
ADDITIONAL_LOOT = 'additionalLoot'
ENFORCE_CRIMINAL_FLAG_CLASS = 'enforceCriminalFlag'
REACTIVE_SPAWNER_CLASS = 'reactiveSpawnComponent'
FIT_MODULES_BY_OWNER = 'fitModulesByOwner'
SKYBOX_CLASS = 'skybox'
PROXIMITY_LOCK_CLASS = 'proximityLock'
CAMERA_LIMITATION_CLASS = 'cameraLimitation'
APPLIED_PROXIMITY_EFFECTS_CLASS = 'appliedProximityEffects'
SYSTEM_WIDE_EFFECTS = 'systemWideEffects'
PROXIMITY_PERSIST_ANCHORED_CONTAINERS = 'proximityPersistAnchoredContainers'
STORE_SLIM_ITEM_FIELD_IN_ITEM_SETTINGS = 'storeSlimItemFieldInItemSettings'
STANDINGS_RESTRICTIONS = 'standingsRestrictionList'
DESTINY_SERVER_BALL_CLASS = 'destinyServerBallClass'
PVP_MATCH_RESULT_CLASS = 'pvpMatchResult'
ESS_REGISTRATION_CLASS = 'essRegistration'
ESS_LINK_CLASS = 'essLink'
VISUAL_PROXIMITY_EFFECT = 'visualProximityEffect'
PROXIMITY_TRAP = 'proximityTrap'
DECLOAK_EMITTER = 'decloakEmitter'
ESS_BRACKET = 'essBracket'
LINK_WITH_SHIP = 'linkWithShip'
HOSTILE_BAITER = 'hostileBaiter'
PROXIMITY_DISPLACEMENT = 'proximityDisplacement'
STELLAR_HARVESTER = 'stellarHarvester'
FW_OBJECTIVE = 'fwObjective'
FW_CAPTURE_POINT = 'fwCapturePoint'
FW_SCOREBOARD = 'fwScoreboard'
BOOMBOX = 'boombox'
UNDER_CONSTRUCTION = 'underConstruction'
BUILT_LANDING_PAD = 'builtLandingPad'
SHIPCASTER_LAUNCHER = 'shipcasterLauncher'
ALIGNMENT_BASED_TOLL = 'alignmentBasedToll'
PROXIMITY_NOTIFIER = 'proximityNotifier'
MULTIEFFECT = 'multiEffect'
GENERICMULTIEFFECT = 'genericMultiEffect'
DEPLOY_BLOCKER = 'deployBlocker'
DEATHZONE_IMMUNITY_GENERATOR = 'deathzoneImmunityGenerator'
DEATHZONE_DAMAGE_GENERATOR = 'deathzoneDamageGenerator'
SYSTEM_DBUFF_EMITTER = 'systemDbuffEmitter'
ROOM_CAPTURE_PROXIMITY_TRIGGER = 'roomCaptureProximityTrigger'
TOW_GAME_OBJECTIVE = 'towGameObjective'
TOW_GAME_GOALPOST = 'towGameGoalpost'
TOW_GAME_OPERATOR = 'towGameOperator'
ORBITAL_SKYHOOK = 'orbitalSkyhook'
SOV_HUB = 'sovHub'
AUTO_MOON_MINER = 'autoMoonMiner'
SKYHOOK_REAGENT_SILO = 'skyhookReagentSilo'
MERCENARY_DEN = 'mercenaryDen'
HACKING_SECURITY_STATE = 'hackingSecurityState'
FILAMENT_SPOOLUP = 'filamentSpoolup'
PILOT_PRESENCE_TRACKER = 'pilotPresenceTracker'
ALL_COMPONENTS = (DEPLOY_CLASS,
 ACTIVATE_CLASS,
 DOGMATIC_CLASS,
 SCOOP_CLASS,
 DECAY_CLASS,
 FITTING_CLASS,
 CARGO_BAY,
 CYNO_INHIBITOR_CLASS,
 CYNO_BEACON_GENERATOR_CLASS,
 REINFORCE_CLASS,
 AUTO_TRACTOR_BEAM_CLASS,
 AUTO_LOOTER_CLASS,
 BOOKMARK_CLASS,
 SIPHON_CLASS,
 PHYSICS_CLASS,
 SCAN_BLOCKER_CLASS,
 MICRO_JUMP_DRIVER_CLASS,
 WARP_DISRUPTION_CLASS,
 BEHAVIOR,
 NPC_PILOT,
 TURBO_SHIELD_CLASS,
 SHIP_GROUP_CLASS,
 PROXIMITY_SENSOR_CLASS,
 TARGETING,
 ENTOSIS_COMMAND_NODE,
 ENTOSIS_SOVEREIGNTY_STRUCTURE,
 ENTOSIS_LOOT_TARGET,
 NPC_WARP_BEACON,
 ITEM_TRADER,
 JUMP_POLARIZATION_CLASS,
 FIGHTER_SQUADRON_CLASS,
 BILLBOARD_CLASS,
 AUTO_WARP_SCRAMBLER_CLASS,
 SOF_OWNER_MAPPER_CLASS,
 DYNAMIC_ENTITY_NAME_CLASS,
 ENTITY_STANDINGS_CLASS,
 ENTITY_BOUNTY_CLASS,
 IGNORE_FITTING_RESTRICTIONS_CLASS,
 ADDITIONAL_LOOT,
 ENFORCE_CRIMINAL_FLAG_CLASS,
 REACTIVE_SPAWNER_CLASS,
 FIT_MODULES_BY_OWNER,
 SKYBOX_CLASS,
 PROXIMITY_LOCK_CLASS,
 CAMERA_LIMITATION_CLASS,
 APPLIED_PROXIMITY_EFFECTS_CLASS,
 SYSTEM_WIDE_EFFECTS,
 PROXIMITY_PERSIST_ANCHORED_CONTAINERS,
 STORE_SLIM_ITEM_FIELD_IN_ITEM_SETTINGS,
 DESTINY_SERVER_BALL_CLASS,
 PVP_MATCH_RESULT_CLASS,
 VISUAL_PROXIMITY_EFFECT,
 PROXIMITY_TRAP,
 DECLOAK_EMITTER,
 ESS_BRACKET,
 LINK_WITH_SHIP,
 HOSTILE_BAITER,
 PROXIMITY_DISPLACEMENT,
 STELLAR_HARVESTER,
 FW_OBJECTIVE,
 FW_CAPTURE_POINT,
 FW_SCOREBOARD,
 BOOMBOX,
 UNDER_CONSTRUCTION,
 BUILT_LANDING_PAD,
 SHIPCASTER_LAUNCHER,
 MULTIEFFECT,
 DEPLOY_BLOCKER,
 ALIGNMENT_BASED_TOLL,
 DEATHZONE_IMMUNITY_GENERATOR,
 DEATHZONE_DAMAGE_GENERATOR,
 SYSTEM_DBUFF_EMITTER,
 ROOM_CAPTURE_PROXIMITY_TRIGGER,
 TOW_GAME_OBJECTIVE,
 TOW_GAME_GOALPOST,
 TOW_GAME_OPERATOR,
 ORBITAL_SKYHOOK,
 SOV_HUB,
 AUTO_MOON_MINER,
 SKYHOOK_REAGENT_SILO,
 MERCENARY_DEN,
 FILAMENT_SPOOLUP,
 PILOT_PRESENCE_TRACKER)
MIN_DISTANCE_FROM_CONTROLTOWER_MAX_VALUE = 30000000
BOOMBOX_MUSIC_TRIGGER_SLIM_ITEM_FIELD = 'component_boombox_music_trigger'
