#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\pvpFilaments\common\constants.py
from carbon.common.lib.const import MIN, SEC
STALEMATE_WALLCLOCK_TIME = 480000
DEFAULT_PVP_CONTENT_DURATION = 15 * MIN
DEFAULT_PVP_CONTENT_DURATION_WITH_JUMP_DELAY = DEFAULT_PVP_CONTENT_DURATION + 18 * SEC
FILAMENT_PROXIMITY_RESTRICTION_RANGE = 1000000
FILAMENT_ANCHOR_RESTRICTION_RANGE = 10000
ACTIVATION_ERROR_DELAY = 4000
AWARDED_REWARDS = 1
UN_REWARDED = 0
