#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\shipcaster\shipcasterConst.py
DEFAULT_MAX_LANDING_PAD_LINKS = 3
LINK_GRACE_TIME_MIN = 5
LINK_UPDATE_INTERVAL = 60
CYCLE_TARGET_DURATION_SECONDS = 60
CYCLE_IDLE_DURATION_SECONDS = 60
LANDING_PAD_MAX_BUILD_VFX_DURATION = 20
LANDING_PAD_SLIM_STATE_ATTRIBUTE = 'component_landingpad_state'
LANDING_PAD_SLIM_STATE_DISRUPTED = 'DISRUPTED'
LANDING_PAD_SLIM_STATE_LINKED = 'LINKED'
LANDING_PAD_SLIM_STATE_UNLINKED = 'UNLINKED'
SHIPCASTER_SLIM_LINKED_TARGETS_ATTRIBUTE = 'component_shipcaster_linked_targets'
SHIPCASTER_PROXIMITY_TO_JUMP = 5000
SHIPCASTER_VFX_POWER_DOWN_DURATION = 24
