#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\charactercreator\client\animparams_const.py
import charactercreator.const as ccconst
PARAMS_PER_AVATAR = {}
CONTROL_PARAM_VALUE_DICT = dict(ccconst.FACE_POSE_CONTROLPARAMS)
CONTROL_PARAM_LIST = ['ControlParameters|BrowLeftCurl',
 'ControlParameters|BrowRightCurl',
 'ControlParameters|BrowLeftUpDown',
 'ControlParameters|BrowRightUpDown',
 'ControlParameters|BrowLeftTighten',
 'ControlParameters|BrowRightTighten',
 'ControlParameters|SquintLeft',
 'ControlParameters|SquintRight',
 'ControlParameters|FrownLeft',
 'ControlParameters|FrownRight',
 'ControlParameters|SmileLeft',
 'ControlParameters|SmileRight',
 'ControlParameters|HeadTilt',
 'ControlParameters|JawSideways',
 'ControlParameters|JawUp',
 'ControlParameters|EyesLookVertical',
 'ControlParameters|EyesLookHorizontal',
 'ControlParameters|EyeClose',
 'ControlParameters|OrientChar',
 'ControlParameters|PortraitPoseNumber',
 'ControlParameters|HeadLookTarget',
 'ControlParameters|NetworkMode',
 'ControlParameters|IsAlive']
FACE_POSE_BROW_LEFT_BONELIST = ['fj_foreheadLower_centerLeft', 'fj_foreheadLower_midLeft', 'fj_foreheadLower_left']
FACE_POSE_BROW_RIGHT_BONELIST = ['fj_foreheadLower_centerRight', 'fj_foreheadLower_midRight', 'fj_foreheadLower_right']
FACE_POSE_EYE_CLOSED_BONELIST = ['fj_leftEye_upperLid_inner',
 'fj_rightEye_lowerLid_outer',
 'fj_leftEye_lowerLid_outer',
 'fj_rightEye_upperLid_outer',
 'fj_leftEye_upperLid_outer',
 'fj_rightEye_upperLid_inner',
 'fj_leftEye_lowerLid_inner',
 'fj_rightEye_lowerLid_inner']
FACE_POSE_EYEBALL_BONELIST = ['fj_eyeballLeft', 'fj_eyeballRight']
FACE_POSE_EYE_LOOK_BONELIST = FACE_POSE_EYE_CLOSED_BONELIST
FACE_POSE_EYE_LOOK_BONELIST.extend(FACE_POSE_EYEBALL_BONELIST)
FACE_POSE_FROWN_LEFT_BONELIST = ['fj_lip_upper_centerLeft',
 'fj_leftCheekInner_upper',
 'fj_lip_lower_centerLeft',
 'fj_lip_upper_center',
 'fj_lip_cornerLeft',
 'fj_nose_left',
 'fj_lip_lower_center',
 'fj_leftCheekInner_middle']
FACE_POSE_FROWN_RIGHT_BONELIST = ['fj_lip_upper_centerRight',
 'fj_lip_cornerRight',
 'fj_lip_lower_centerRight',
 'fj_nose_right',
 'fj_lip_upper_center',
 'fj_lip_lower_center',
 'fj_rightCheekInner_upper',
 'fj_rightCheekInner_middle']
FACE_POSE_JAW_BONELIST = ['fj_lip_upper_centerRight',
 'fj_lip_cornerRight',
 'fj_lip_upper_centerLeft',
 'fj_leftCheekInner_middle',
 'fj_leftCheekInner_upper',
 'fj_jaw',
 'fj_lip_cornerLeft',
 'fj_lip_upper_center',
 'fj_rightCheekInner_upper',
 'fj_rightCheekInner_middle',
 'fj_ear_wiggle']
FACE_POSE_SMILE_LEFT_BONELIST = ['fj_lip_upper_centerRight',
 'fj_lip_cornerRight',
 'fj_lip_lower_center',
 'fj_lip_upper_centerLeft',
 'fj_leftCheekInner_middle',
 'fj_leftCheekInner_upper',
 'fj_leftCheekBone_outer',
 'fj_jaw',
 'fj_lip_lower_centerLeft',
 'fj_leftCheekBone_inner',
 'fj_lip_upper_center',
 'fj_lip_cornerLeft',
 'fj_rightCheekInner_middle',
 'fj_leftCheekBone_middle',
 'fj_rightCheekInner_upper',
 'fj_nose_left']
FACE_POSE_SMILE_RIGHT_BONELIST = ['fj_lip_upper_centerRight',
 'fj_lip_cornerRight',
 'fj_rightCheekBone_middle',
 'fj_rightCheekBone_outer',
 'fj_rightCheekInner_middle',
 'fj_lip_lower_center',
 'fj_leftCheekInner_middle',
 'fj_lip_upper_centerLeft',
 'fj_lip_lower_centerRight',
 'fj_leftCheekInner_upper',
 'fj_jaw',
 'fj_nose_right',
 'fj_rightCheekBone_inner',
 'fj_lip_cornerLeft',
 'fj_lip_upper_center',
 'fj_rightCheekInner_upper']
FACE_POSE_SQUINT_LEFT_BONELIST = ['fj_leftEye_lowerLid_outer',
 'fj_leftCheekBone_inner',
 'fj_leftCheekBone_outer',
 'fj_leftCheekBone_middle',
 'fj_leftEye_lowerLid_inner']
FACE_POSE_SQUINT_RIGHT_BONELIST = ['fj_rightCheekBone_middle',
 'fj_rightEye_lowerLid_outer',
 'fj_rightCheekBone_inner',
 'fj_rightEye_lowerLid_inner',
 'fj_rightCheekBone_outer']
FACE_POSE_TILTHEAD_BONELIST = ['Head', 'Neck']
FACE_POSE_BONELIST = ['fj_foreheadLower_centerLeft',
 'fj_ear_wiggle',
 'fj_eyeballLeft',
 'fj_eyeballRight',
 'fj_foreheadLower_centerRight',
 'fj_foreheadLower_left',
 'fj_foreheadLower_midLeft',
 'fj_foreheadLower_midRight',
 'fj_foreheadLower_right',
 'fj_jaw',
 'fj_leftCheekBone_inner',
 'fj_leftCheekBone_middle',
 'fj_leftCheekBone_outer',
 'fj_leftCheekInner_middle',
 'fj_leftCheekInner_upper',
 'fj_leftEye_lowerLid_inner',
 'fj_leftEye_lowerLid_outer',
 'fj_leftEye_upperLid_inner',
 'fj_leftEye_upperLid_outer',
 'fj_lip_cornerLeft',
 'fj_lip_cornerRight',
 'fj_lip_lower_center',
 'fj_lip_lower_centerLeft',
 'fj_lip_lower_centerRight',
 'fj_lip_upper_center',
 'fj_lip_upper_centerLeft',
 'fj_lip_upper_centerRight',
 'fj_nose_left',
 'fj_nose_right',
 'fj_rightCheekBone_inner',
 'fj_rightCheekBone_middle',
 'fj_rightCheekBone_outer',
 'fj_rightCheekInner_middle',
 'fj_rightCheekInner_upper',
 'fj_rightEye_lowerLid_inner',
 'fj_rightEye_lowerLid_outer',
 'fj_rightEye_upperLid_inner',
 'fj_rightEye_upperLid_outer']
HEAD_LOOK_BONELIST = ['fj_eyeballLeft',
 'fj_eyeballRight',
 'Spine',
 'Spine1',
 'Spine2',
 'Spine3',
 'Neck',
 'Neck1',
 'Head']
IDLE_POSE_BONELIST = ['Hips',
 'LeftUpLeg',
 'LeftLeg',
 'LeftFoot',
 'RightUpLeg',
 'RightLeg',
 'RightFoot',
 'LeftShoulder',
 'LeftArm',
 'LeftHand',
 'LeftForeArm_Roll1',
 'LeftArm_Roll1',
 'RightShoulder',
 'RightArm',
 'RightForeArm',
 'Neck',
 'Head',
 'fj_foreheadLower_centerLeft',
 'fj_ear_wiggle',
 'fj_eyeballLeft',
 'fj_eyeballRight',
 'fj_foreheadLower_centerRight',
 'fj_foreheadLower_left',
 'fj_foreheadLower_midLeft',
 'fj_foreheadLower_midRight',
 'fj_foreheadLower_right',
 'fj_jaw',
 'fj_leftCheekBone_inner',
 'fj_leftCheekBone_middle',
 'fj_leftCheekBone_outer',
 'fj_leftCheekInner_middle',
 'fj_leftCheekInner_upper',
 'fj_leftEye_lowerLid_inner',
 'fj_leftEye_lowerLid_outer',
 'fj_leftEye_upperLid_inner',
 'fj_leftEye_upperLid_outer',
 'fj_lip_cornerLeft',
 'fj_lip_cornerRight',
 'fj_lip_lower_center',
 'fj_lip_lower_centerLeft',
 'fj_lip_lower_centerRight',
 'fj_lip_upper_center',
 'fj_lip_upper_centerLeft',
 'fj_lip_upper_centerRight',
 'fj_nose_left',
 'fj_nose_right',
 'fj_rightCheekBone_inner',
 'fj_rightCheekBone_middle',
 'fj_rightCheekBone_outer',
 'fj_rightCheekInner_middle',
 'fj_rightCheekInner_upper',
 'fj_rightEye_lowerLid_inner',
 'fj_rightEye_lowerLid_outer',
 'fj_rightEye_upperLid_inner',
 'fj_rightEye_upperLid_outer',
 'RightLung',
 'LeftLung']
NETWORKMODE_BASIC = 1
NETWORKMODE_PORTRAIT = 2
