#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\eveuniverse\const.py
STARGATE_STATUS_ENABLED = 0
STARGATE_STATUS_DISABLED_INTERNAL = 1
STARGATE_STATUS_DISABLED_EXTERNAL = 2
STARGATE_STATUS_DISABLED_ALL = 3
STARGATE_STATUS_DESCRIPTION = {STARGATE_STATUS_ENABLED: 'Enabled',
 STARGATE_STATUS_DISABLED_INTERNAL: 'Disabled - Internally',
 STARGATE_STATUS_DISABLED_EXTERNAL: 'Disabled - Externally',
 STARGATE_STATUS_DISABLED_ALL: 'Disabled - All'}
