#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\common\script\util\notificationconst.py
notificationTypeOldLscMessages = 1
notificationTypeCharTerminationMsg = 2
notificationTypeCharMedalMsg = 3
notificationTypeAllMaintenanceBillMsg = 4
notificationTypeAllWarDeclaredMsg = 5
notificationTypeAllWarSurrenderMsg = 6
notificationTypeAllWarRetractedMsg = 7
notificationTypeAllWarInvalidatedMsg = 8
notificationTypeCharBillMsg = 9
notificationTypeCorpAllBillMsg = 10
notificationTypeBillOutOfMoneyMsg = 11
notificationTypeBillPaidCharMsg = 12
notificationTypeBillPaidCorpAllMsg = 13
notificationTypeBountyClaimMsg = 14
notificationTypeCloneActivationMsg = 15
notificationTypeCorpAppNewMsg = 16
notificationTypeCorpAppRejectMsg = 17
notificationTypeCorpAppAcceptMsg = 18
notificationTypeCorpTaxChangeMsg = 19
notificationTypeCorpNewsMsg = 20
notificationTypeCharLeftCorpMsg = 21
notificationTypeCorpNewCEOMsg = 22
notificationTypeCorpDividendMsg = 23
notificationTypeCorpVoteMsg = 25
notificationTypeCorpVoteCEORevokedMsg = 26
notificationTypeCorpWarDeclaredMsg = 27
notificationTypeCorpWarFightingLegalMsg = 28
notificationTypeCorpWarSurrenderMsg = 29
notificationTypeCorpWarRetractedMsg = 30
notificationTypeCorpWarInvalidatedMsg = 31
notificationTypeContainerPasswordMsg = 32
notificationTypeCustomsMsg = 33
notificationTypeInsuranceFirstShipMsg = 34
notificationTypeInsurancePayoutMsg = 35
notificationTypeInsuranceInvalidatedMsg = 36
notificationTypeSovAllClaimFailMsg = 37
notificationTypeSovCorpClaimFailMsg = 38
notificationTypeSovAllBillLateMsg = 39
notificationTypeSovCorpBillLateMsg = 40
notificationTypeSovAllClaimLostMsg = 41
notificationTypeSovCorpClaimLostMsg = 42
notificationTypeSovAllClaimAquiredMsg = 43
notificationTypeSovCorpClaimAquiredMsg = 44
notificationTypeAllAnchoringMsg = 45
notificationTypeAllStructVulnerableMsg = 46
notificationTypeAllStrucInvulnerableMsg = 47
notificationTypeSovDisruptorMsg = 48
notificationTypeCorpStructLostMsg = 49
notificationTypeCorpOfficeExpirationMsg = 50
notificationTypeCloneRevokedMsg1 = 51
notificationTypeCloneMovedMsg = 52
notificationTypeCloneRevokedMsg2 = 53
notificationTypeInsuranceExpirationMsg = 54
notificationTypeInsuranceIssuedMsg = 55
notificationTypeJumpCloneDeletedMsg1 = 56
notificationTypeJumpCloneDeletedMsg2 = 57
notificationTypeFWCorpJoinMsg = 58
notificationTypeFWCorpLeaveMsg = 59
notificationTypeFWCorpKickMsg = 60
notificationTypeFWCharKickMsg = 61
notificationTypeFWCorpWarningMsg = 62
notificationTypeFWCharWarningMsg = 63
notificationTypeFWCharRankLossMsg = 64
notificationTypeFWCharRankGainMsg = 65
notificationTypeAgentMoveMsg = 66
notificationTypeTransactionReversalMsg = 67
notificationTypeReimbursementMsg = 68
notificationTypeLocateCharMsg = 69
notificationTypeResearchMissionAvailableMsg = 70
notificationTypeMissionOfferExpirationMsg = 71
notificationTypeMissionTimeoutMsg = 72
notificationTypeStoryLineMissionAvailableMsg = 73
notificationTypeTutorialMsg = 74
notificationTypeTowerAlertMsg = 75
notificationTypeTowerResourceAlertMsg = 76
notificationTypeStationAggressionMsg1 = 77
notificationTypeStationStateChangeMsg = 78
notificationTypeStationConquerMsg = 79
notificationTypeStationAggressionMsg2 = 80
notificationTypeFacWarCorpJoinRequestMsg = 81
notificationTypeFacWarCorpLeaveRequestMsg = 82
notificationTypeFacWarCorpJoinWithdrawMsg = 83
notificationTypeFacWarCorpLeaveWithdrawMsg = 84
notificationTypeCorpLiquidationMsg = 85
notificationTypeSovereigntyTCUDamageMsg = 86
notificationTypeSovereigntySBUDamageMsg = 87
notificationTypeSovereigntyIHDamageMsg = 88
notificationTypeContactAdd = 89
notificationTypeContactEdit = 90
notificationTypeIncursionCompletedMsg = 91
notificationTypeCorpKicked = 92
notificationTypeOrbitalAttacked = 93
notificationTypeOrbitalReinforced = 94
notificationTypeOwnershipTransferred = 95
notificationTypeFWAllianceWarningMsg = 96
notificationTypeFWAllianceKickMsg = 97
notificationTypeAllWarCorpJoinedAllianceMsg = 98
notificationTypeAllyJoinedWarDefenderMsg = 99
notificationTypeAllyJoinedWarAggressorMsg = 100
notificationTypeAllyJoinedWarAllyMsg = 101
notificationTypeMercOfferedNegotiationMsg = 102
notificationTypeWarSurrenderOfferMsg = 103
notificationTypeWarSurrenderDeclinedMsg = 104
notificationTypeFacWarLPPayoutKill = 105
notificationTypeFacWarLPPayoutEvent = 106
notificationTypeFacWarLPDisqualifiedEvent = 107
notificationTypeFacWarLPDisqualifiedKill = 108
notificationTypeAllyContractCancelled = 109
notificationTypeWarAllyOfferDeclinedMsg = 110
notificationTypeBountyYourBountyClaimed = 111
notificationTypeBountyPlacedChar = 112
notificationTypeBountyPlacedCorp = 113
notificationTypeBountyPlacedAlliance = 114
notificationTypeKillRightAvailable = 115
notificationTypeKillRightAvailableOpen = 116
notificationTypeKillRightEarned = 117
notificationTypeKillRightUsed = 118
notificationTypeKillRightUnavailable = 119
notificationTypeKillRightUnavailableOpen = 120
notificationTypeDeclareWar = 121
notificationTypeOfferedSurrender = 122
notificationTypeAcceptedSurrender = 123
notificationTypeMadeWarMutual = 124
notificationTypeRetractsWar = 125
notificationTypeOfferedToAlly = 126
notificationTypeAcceptedAlly = 127
notificationTypeCharAppAcceptMsg = 128
notificationTypeCharAppRejectMsg = 129
notificationTypeCharAppWithdrawMsg = 130
notificationTypeDustAppAcceptedMsg = 131
notificationTypeDistrictAttacked = 132
notificationTypeBattlePunishFriendlyFire = 133
notificationTypeIndustryTeamAuctionWon = 136
notificationTypeIndustryTeamAuctionLost = 137
notificationTypeCloneActivationMsg2 = 138
notificationTypeCorpAppInvitedMsg = 139
notificationTypeKillReportVictim = 140
notificationTypeKillReportFinalBlow = 141
notificationTypeCorpAppRejectCustomMsg = 142
notificationTypeCorpFriendlyFireEnableTimerStarted = 143
notificationTypeCorpFriendlyFireDisableTimerStarted = 144
notificationTypeCorpFriendlyFireEnableTimerCompleted = 145
notificationTypeCorpFriendlyFireDisableTimerCompleted = 146
notificationTypeEntosisCaptureStarted = 147
notificationTypeStationServiceEnabled = 148
notificationTypeStationServiceDisabled = 149
notificationTypeStationServiceHalfCaptured = 150
notificationTypeInfrastructureHubBillAboutToExpireDEPRECATED = 151
notificationTypeInfrastructureHubBillAboutToExpire = 152
notificationTypeSovStructureReinforced = 160
notificationTypeSovCommandNodeEventStarted = 161
notificationTypeSovStructureDestroyed = 162
notificationTypeSovStationEnteredFreeport = 163
notificationTypeIHubDestroyedByBillFailure = 164
notificationTypeAllianceCapitalChanged = 165
notificationTypeBuddyConnectContactAdd = 166
notificationTypeSovStructureSelfDestructRequested = 167
notificationTypeSovStructureSelfDestructCancel = 168
notificationTypeSovStructureSelfDestructFinished = 169
notificationTypeCCPDevNews = 170
notificationTypeCCPServerNews = 171
notificationTypeCCPGameNews = 172
notificationTypeCCPOutOfGameNews = 173
notificationTypeTicketReply = 179
notificationTypeServerShutdown = 180
notificationTypeStructureFuelAlert = 181
notificationTypeStructureAnchoring = 182
notificationTypeStructureUnanchoring = 183
notificationTypeStructureUnderAttack = 184
notificationTypeStructureOnline = 185
notificationTypeStructureLostShields = 186
notificationTypeStructureLostArmor = 187
notificationTypeStructureDestroyed = 188
notificationTypeStructureItemsToAssetSafety = 190
notificationTypeStructureItemsNeedAttention = 191
notificationTypeStructureMarketOrdersCancelled = 192
notificationTypeStructureLostDockingAccess = 195
notificationTypeStructureOfficeRentalBill = 196
notificationTypeStructureServicesOffline = 198
notificationTypeStructureItemsDelivered = 199
notificationTypeSeasonalChallengeCompleted = 200
notificationTypeStructureCourierContractChanged = 201
notificationTypeMoonminingExtractionStarted = 202
notificationTypeMoonminingExtractionCancelled = 203
notificationTypeMoonminingExtractionFinished = 204
notificationTypeMoonminingLaserFired = 205
notificationTypeMoonminingAutomaticFracture = 206
notificationTypeStructureWentLowPower = 207
notificationTypeStructureWentHighPower = 208
notificationTypeStructuresReinforcementChanged = 209
notificationTypeStructuresJobsPaused = 210
notificationTypeStructuresJobsCancelled = 211
notificationTypeCorpBecameWarEligible = 221
notificationTypeCorpNotLongerWarEligible = 222
notificationTypeWarHQRemovedFromSpace = 223
notificationTypeCorpWarDeclaredMsg2 = 224
notificationTypeAllWarDeclaredMsg2 = 225
notificationTypeInvasionSystemLogin = 226
notificationTypeInvasionSystemStart = 227
notificationTypeInvasionCompletedMsg = 228
notificationTypeWarMutualWarInviteSent = 229
notificationTypeWarMutualWarInviteRejected = 230
notificationTypeWarMutualWarInviteAccepted = 231
notificationTypeWarDeclared = 232
notificationTypeWarAdopted = 233
notificationTypeWarMutualWarExpired = 234
notificationTypeWarInherited = 235
notificationTypeWarAllyInherited = 236
notificationTypeWarConcordInvalidates = 237
notificationTypeWarRetracted = 238
notificationTypeWarRetractedByConcord = 239
notificationTypeWarInvalid = 240
notificationTypeMercOfferRetractedMsg = 241
notificationTypeOfferToAllyRetracted = 242
notificationTypeRaffleCreated = 243
notificationTypeRaffleExpired = 244
notificationTypeRaffleFinished = 245
notificationTypeWarEndedHqSecurityDrop = 246
notificationTypeMissionCanceledTriglavian = 247
notificationTypeAgentRetiredTriglavian = 248
notificationTypeStructureImpendingAbandonmentAssetsAtRisk = 249
notificationTypeOfficeLeaseCanceledInsufficientStandings = 250
notificationTypeContractRegionChangedToPochven = 251
notificationTypeExpertSystemExpiryImminent = 252
notificationTypeExpertSystemExpired = 253
notificationTypeStructurePaintPurchased = 254
notificationTypeCorpGoalCreated = 260
notificationTypeCorpGoalClosed = 261
notificationTypeCorpGoalCompleted = 262
notificationTypeCorpGoalNameChange = 263
notificationTypeCorpGoalExpired = 264
notificationTypeCorpGoalLimitReached = 265
notificationTypeCorpLeft = 270
corpGoalNotificationTypes = [notificationTypeCorpGoalCreated,
 notificationTypeCorpGoalClosed,
 notificationTypeCorpGoalCompleted,
 notificationTypeCorpGoalNameChange,
 notificationTypeCorpGoalExpired,
 notificationTypeCorpGoalLimitReached]
notificationTypeLPAutoRedeemed = 275
notificationTypeSPAutoRedeemed = 276
notificationTypeSkinSequencingCompleted = 280
notificationTypeSkyhookOnline = 281
notificationTypeSkyhookLostShields = 282
notificationTypeSkyhookUnderAttack = 283
notificationTypeSkyhookDestroyed = 284
notificationTypeSkyhookDeployed = 285
notificationTypeMercenaryDenReinforced = 286
notificationTypeMercDenAttacked = 287
notificationTypeMercDenNewMTO = 288
notificationTypeSkillFinished = 1000
notificationTypeSkillInjected = 1001
notificationTypeSkillEmptyQueue = 1002
notificationTypeSkillsAddedFromSkillPlan = 1033
notificationTypeMailSummary = 1003
notificationTypeNewMailFrom = 1004
notificationTypeUnusedSkillPoints = 1005
notificationTypeContractAssigned = 1006
notificationTypeContractNeedsAttention = 1007
notificationTypeContractAccepted = 1008
notificationTypeAchievementTaskFinished = 1010
notificationTypeOpportunityFinished = 1011
notificationTypeOperationFinished = 1012
notificationTypeCombatOperationFinished = 1013
notificationTypeIndustryOperationFinished = 1014
notificationTypeEssMainBankLink = 1015
notificationTypeEssLinkDisconnected = 1016
notificationTypeEssReserveBankUnlocked = 1017
notificationTypeEssInventoryFull = 1018
notificationTypePlexDeliveryDelay = 1021
notificationTypeGiftReceived = 1022
notificationTypeGameTimeReceived = 1030
notificationTypeGameTimeSent = 1031
notificationTypeGameTimeAdded = 1032
notificationTypeQuestComplete = 1040
notificationTypeCalendarEvent = 1050
notificationTypeAlphaInjectorAvailable = 1060
notificationTypeImplantPluggedIn = 1100
notificationTypeBoosterConsumed = 1101
notificationTypeInsurgencyStarting = 1110
notificationTypeInsurgencyStarted = 1111
notificationTypeInsurgencyEndedPiratesWin = 1112
notificationTypeInsurgencyEndedAntiPiratesWin = 1113
notificationTypeInsurgencyEndedNoOneWins = 1114
notificationTypeInsurgencyStage5Corruption = 1115
notificationTypeInsurgencyStage5Suppression = 1116
notificationTypeContactSignedOn = 2001
notificationTypeContactSignedOff = 2002
notificationTypeNPCStandingsChanged = 3001
notificationTypeNPCStandingsGained = 3002
notificationTypeNewOfferAvailable = 4001
notificationTypeOfferPurchased = 4002
notificationTypeAddictionWarning = 5001
notificationTypeCorpCosmeticLicensePurchased = 6001
notificationTypeAllianceCosmeticLicensePurchased = 6002
notificationTypeDailyGoalCompleted = 6010
notificationTypeDailyMilestoneCompleted = 6011
notificationTypeDailyRewardTrackCompleted = 6012
notificationTypeDailyItemRewardAutoClaimed = 6013
notificationTypeShipGroupUnlocked = 6020
notificationTypeSkyhookLinkStarted = 6030
notificationTypeSkyhookTheftVulnerabilityStarted = 6031
notificationTypeStructureLowReagentsAlert = 6040
notificationTypeStructureNoReagentsAlert = 6041
notificationTypeBountyESSTaken_deprecated = 134
notificationTypeBountyESSShared_deprecated = 135
notificationToSettingDescription = {notificationTypeSovStructureSelfDestructRequested: 'Notifications/NotificationNames/StructureSelfDestructRequested',
 notificationTypeSovStructureSelfDestructCancel: 'Notifications/NotificationNames/StructureSelfDestructCancel',
 notificationTypeSovStructureSelfDestructFinished: 'Notifications/NotificationNames/StructureSelfDestructFinished',
 notificationTypeSovStructureReinforced: 'Notifications/NotificationNames/SovereigntyStructuresReinforced',
 notificationTypeSovCommandNodeEventStarted: 'Notifications/NotificationNames/SovereigntyCommandNodeEventStarted',
 notificationTypeSovStructureDestroyed: 'Notifications/NotificationNames/SovereigntyStructureDestroyed',
 notificationTypeSovStationEnteredFreeport: 'Notifications/NotificationNames/SovereigntyStationEnteredFreeport',
 notificationTypeIHubDestroyedByBillFailure: 'Notifications/NotificationNames/SovereigntyIHubDestroyedByBillFailure',
 notificationTypeAllianceCapitalChanged: 'Notifications/NotificationNames/SovereigntyAllianceCapitalChanged',
 notificationTypeContactSignedOn: 'Notifications/NotificationNames/WatchedContactOnline',
 notificationTypeContactSignedOff: 'Notifications/NotificationNames/WatchedContactOffline',
 notificationTypeSkillFinished: 'Notifications/NotificationNames/SkillTrainingComplete',
 notificationTypeSkillInjected: 'Notifications/NotificationNames/SkillInjected',
 notificationTypeSkillEmptyQueue: 'Notifications/NotificationNames/SkillQueueEmpty',
 notificationTypeSkillsAddedFromSkillPlan: 'Notifications/NotificationNames/SkillsAddedFromSkillPlan',
 notificationTypeOldLscMessages: 'Notifications/NotificationNames/OldNotifications',
 notificationTypeCharTerminationMsg: 'Notifications/NotificationNames/MemberBiomassed',
 notificationTypeCharMedalMsg: 'Notifications/NotificationNames/MedalAwarded',
 notificationTypeAllMaintenanceBillMsg: 'Notifications/NotificationNames/AllianceMaintenanceBill',
 notificationTypeAllWarDeclaredMsg: 'Notifications/NotificationNames/AllianceWarDeclared',
 notificationTypeAllWarDeclaredMsg2: 'Notifications/NotificationNames/AllianceWarDeclared',
 notificationTypeAllWarSurrenderMsg: 'Notifications/NotificationNames/AllianceWarSurrender',
 notificationTypeAllWarRetractedMsg: 'Notifications/NotificationNames/AllianceWarRetracted',
 notificationTypeAllWarInvalidatedMsg: 'Notifications/NotificationNames/AllianceWarInvalidated',
 notificationTypeCharBillMsg: 'Notifications/NotificationNames/PilotBilled',
 notificationTypeCorpAllBillMsg: 'Notifications/NotificationNames/OrganizationBilled',
 notificationTypeBillOutOfMoneyMsg: 'Notifications/NotificationNames/InsufficientFundsToPayBill',
 notificationTypeBillPaidCharMsg: 'Notifications/NotificationNames/BillPaidByPilot',
 notificationTypeBillPaidCorpAllMsg: 'Notifications/NotificationNames/BillPaidByOrganization',
 notificationTypeBountyClaimMsg: 'Notifications/NotificationNames/CapsuleerBountyPayment',
 notificationTypeCloneActivationMsg2: 'Notifications/NotificationNames/CloneActivation',
 notificationTypeCorpAppNewMsg: 'Notifications/NotificationNames/NewApplicationToJoinCorporation',
 notificationTypeCorpAppRejectMsg: 'Notifications/NotificationNames/YourCorporateApplicationRejected',
 notificationTypeCorpAppRejectCustomMsg: 'Notifications/NotificationNames/YourCorporateApplicationRejected',
 notificationTypeCorpAppAcceptMsg: 'Notifications/NotificationNames/YourCorporateApplicationAccepted',
 notificationTypeCorpAppInvitedMsg: 'Notifications/NotificationNames/NewInvitationToJoinCorp',
 notificationTypeCorpTaxChangeMsg: 'Notifications/NotificationNames/CorporationTaxChange',
 notificationTypeCorpNewsMsg: 'Notifications/NotificationNames/CorporationNews',
 notificationTypeCharLeftCorpMsg: 'Notifications/NotificationNames/PilotLeftCorporation',
 notificationTypeCorpNewCEOMsg: 'Notifications/NotificationNames/NewCorporationCEO',
 notificationTypeCorpDividendMsg: 'Notifications/NotificationNames/CorporateDividendPayout',
 notificationTypeCorpVoteMsg: 'Notifications/NotificationNames/CorporateVoteNotification',
 notificationTypeCorpVoteCEORevokedMsg: 'Notifications/NotificationNames/CEORolesRevokedDuringVote',
 notificationTypeCorpWarDeclaredMsg: 'Notifications/NotificationNames/CorporationWarDeclared',
 notificationTypeCorpWarDeclaredMsg2: 'Notifications/NotificationNames/CorporationWarDeclared',
 notificationTypeCorpWarFightingLegalMsg: 'Notifications/NotificationNames/CorporationWarFighting',
 notificationTypeCorpWarSurrenderMsg: 'Notifications/NotificationNames/CorporationWarSurrender',
 notificationTypeCorpWarRetractedMsg: 'Notifications/NotificationNames/CorporationWarRetracted',
 notificationTypeCorpWarInvalidatedMsg: 'Notifications/NotificationNames/CorporationWarInvalidated',
 notificationTypeContainerPasswordMsg: 'Notifications/NotificationNames/ContainerPassword',
 notificationTypeCustomsMsg: 'Notifications/NotificationNames/CustomsNotification',
 notificationTypeInsuranceFirstShipMsg: 'Notifications/NotificationNames/CorvetteReplacement',
 notificationTypeInsurancePayoutMsg: 'Notifications/NotificationNames/InsurancePayment',
 notificationTypeInsuranceInvalidatedMsg: 'Notifications/NotificationNames/InsuranceInvalidated',
 notificationTypeSovAllClaimFailMsg: 'Notifications/NotificationNames/AllianceSovereigntyClaimFailed',
 notificationTypeSovCorpClaimFailMsg: 'Notifications/NotificationNames/CorporateSovereigntyClaimFailed',
 notificationTypeSovAllBillLateMsg: 'Notifications/NotificationNames/AllianceSovereigntyBillDue',
 notificationTypeSovCorpBillLateMsg: 'Notifications/NotificationNames/CorporateAllianceBillDue',
 notificationTypeSovAllClaimLostMsg: 'Notifications/NotificationNames/AllianceSovereigntyClaimLost',
 notificationTypeSovCorpClaimLostMsg: 'Notifications/NotificationNames/CorporateSovereigntyClaimLost',
 notificationTypeSovAllClaimAquiredMsg: 'Notifications/NotificationNames/AllianceSovereigntyClaimAquired',
 notificationTypeSovCorpClaimAquiredMsg: 'Notifications/NotificationNames/CorporateSovereigntyClaimAquired',
 notificationTypeAllAnchoringMsg: 'Notifications/NotificationNames/StructureAnchoring',
 notificationTypeAllStructVulnerableMsg: 'Notifications/NotificationNames/SovereigntyStructuresVulnerable',
 notificationTypeAllStrucInvulnerableMsg: 'Notifications/NotificationNames/SovereigntyStructuresInvulnerable',
 notificationTypeSovDisruptorMsg: 'Notifications/NotificationNames/SovereigntyBlockadeUnitActive',
 notificationTypeCorpStructLostMsg: 'Notifications/NotificationNames/StructureLost',
 notificationTypeCorpOfficeExpirationMsg: 'Notifications/NotificationNames/OfficeLeaseExpiration',
 notificationTypeCloneRevokedMsg1: 'Notifications/NotificationNames/CloneContractRevoked1',
 notificationTypeCloneMovedMsg: 'Notifications/NotificationNames/CloneMoved',
 notificationTypeCloneRevokedMsg2: 'Notifications/NotificationNames/CloneContractRevoked2',
 notificationTypeInsuranceExpirationMsg: 'Notifications/NotificationNames/InsuranceExpired',
 notificationTypeInsuranceIssuedMsg: 'Notifications/NotificationNames/InsuranceIssued',
 notificationTypeJumpCloneDeletedMsg1: 'Notifications/NotificationNames/JumpCloneDeleted',
 notificationTypeJumpCloneDeletedMsg2: 'Notifications/NotificationNames/JumpCloneDistruction',
 notificationTypeFWCorpJoinMsg: 'Notifications/NotificationNames/CorporationHasJoinedFaction',
 notificationTypeFWCorpLeaveMsg: 'Notifications/NotificationNames/CorporationHasLeftFaction',
 notificationTypeFWCorpKickMsg: 'Notifications/NotificationNames/CorporationExpelledFromFaction',
 notificationTypeFWCharKickMsg: 'Notifications/NotificationNames/PilotExpelledFromFaction',
 notificationTypeFWCorpWarningMsg: 'Notifications/NotificationNames/CorporationFactionStandingWarning',
 notificationTypeFWCharWarningMsg: 'Notifications/NotificationNames/PilotFactionStandingWarning',
 notificationTypeFWCharRankLossMsg: 'Notifications/NotificationNames/PilotLosesFactionRank',
 notificationTypeFWCharRankGainMsg: 'Notifications/NotificationNames/PilotGainsFactionRank',
 notificationTypeAgentMoveMsg: 'Notifications/NotificationNames/AgentMovedNotice',
 notificationTypeTransactionReversalMsg: 'Notifications/NotificationNames/TransactionReversal',
 notificationTypeReimbursementMsg: 'Notifications/NotificationNames/Reimbursement',
 notificationTypeLocateCharMsg: 'Notifications/NotificationNames/PilotLocated',
 notificationTypeResearchMissionAvailableMsg: 'Notifications/NotificationNames/ResearchMissionAvailable',
 notificationTypeMissionOfferExpirationMsg: 'Notifications/NotificationNames/MissionOfferExpiration',
 notificationTypeMissionCanceledTriglavian: 'UI/Agents/Triglavian/MissionCanceledHeader',
 notificationTypeAgentRetiredTriglavian: 'UI/Agents/Triglavian/AgentRetiredHeader',
 notificationTypeMissionTimeoutMsg: 'Notifications/NotificationNames/MissionFailure',
 notificationTypeStoryLineMissionAvailableMsg: 'Notifications/NotificationNames/SpecialMissionAvailable',
 notificationTypeTutorialMsg: 'Notifications/NotificationNames/TutorialProgram',
 notificationTypeTowerAlertMsg: 'Notifications/NotificationNames/TowerUnderAttackAlert',
 notificationTypeTowerResourceAlertMsg: 'Notifications/NotificationNames/TowerResourceAlert',
 notificationTypeStationAggressionMsg1: 'Notifications/NotificationNames/StationUnderAttack',
 notificationTypeStationStateChangeMsg: 'Notifications/NotificationNames/StationChanged',
 notificationTypeStationConquerMsg: 'Notifications/NotificationNames/StationConquered',
 notificationTypeStationAggressionMsg2: 'Notifications/NotificationNames/StationAggression',
 notificationTypeFacWarCorpJoinRequestMsg: 'Notifications/NotificationNames/CorporationJoiningFaction',
 notificationTypeFacWarCorpLeaveRequestMsg: 'Notifications/NotificationNames/CorporationLeavingFaction',
 notificationTypeFacWarCorpJoinWithdrawMsg: 'Notifications/NotificationNames/CorporationJoinFactionWithdrawn',
 notificationTypeFacWarCorpLeaveWithdrawMsg: 'Notifications/NotificationNames/CorporationLeaveFactionWithdrawn',
 notificationTypeCorpLiquidationMsg: 'Notifications/NotificationNames/CorporateLiquidationSettlement',
 notificationTypeSovereigntyTCUDamageMsg: 'Notifications/NotificationNames/SovereigntyTCUDamage',
 notificationTypeSovereigntySBUDamageMsg: 'Notifications/NotificationNames/SovereigntySBUDamage',
 notificationTypeSovereigntyIHDamageMsg: 'Notifications/NotificationNames/SovereigntyIHUBDamage',
 notificationTypeContactAdd: 'Notifications/NotificationNames/AddedAsContact',
 notificationTypeBuddyConnectContactAdd: 'Notifications/NotificationNames/AddedAsContactBuddyConnect',
 notificationTypeContactEdit: 'Notifications/NotificationNames/ContactLevelModified',
 notificationTypeIncursionCompletedMsg: 'Notifications/NotificationNames/IncursionCompleted',
 notificationTypeCorpKicked: 'Notifications/NotificationNames/KickedFromCorporation',
 notificationTypeOrbitalAttacked: 'Notifications/NotificationNames/OrbitalStructureAttacked',
 notificationTypeOrbitalReinforced: 'Notifications/NotificationNames/OrbitalStructureReinforced',
 notificationTypeOwnershipTransferred: 'Notifications/NotificationNames/StructureOwnershipTransferred',
 notificationTypeFWAllianceWarningMsg: 'Notifications/NotificationNames/AllianceFactionStandingWarning',
 notificationTypeFWAllianceKickMsg: 'Notifications/NotificationNames/AllianceExpelledFromFaction',
 notificationTypeAllWarCorpJoinedAllianceMsg: 'Notifications/NotificationNames/CorporationJoinedAllianceAtWar',
 notificationTypeAllyJoinedWarDefenderMsg: 'Notifications/NotificationNames/DefenderAllyJoinsWar',
 notificationTypeAllyJoinedWarAggressorMsg: 'Notifications/NotificationNames/AggressorAllyJoinsWar',
 notificationTypeAllyJoinedWarAllyMsg: 'Notifications/NotificationNames/CorporationJoinsWarAsAlly',
 notificationTypeMercOfferedNegotiationMsg: 'Notifications/NotificationNames/WarAllyOfferReceived',
 notificationTypeMercOfferRetractedMsg: 'Notifications/NotificationNames/WarAllyOfferRetracted',
 notificationTypeWarSurrenderOfferMsg: 'Notifications/NotificationNames/SurrenderOfferReceived',
 notificationTypeWarSurrenderDeclinedMsg: 'Notifications/NotificationNames/SurrenderDeclined',
 notificationTypeFacWarLPPayoutKill: 'Notifications/NotificationNames/FactionKillEventLP',
 notificationTypeFacWarLPPayoutEvent: 'Notifications/NotificationNames/FactionStrategicEventLP',
 notificationTypeFacWarLPDisqualifiedEvent: 'Notifications/NotificationNames/StrategicEventLPDisqualification',
 notificationTypeFacWarLPDisqualifiedKill: 'Notifications/NotificationNames/KillEventLPDisqualification',
 notificationTypeAllyContractCancelled: 'Notifications/NotificationNames/WarAllyAgreementCancelled',
 notificationTypeWarAllyOfferDeclinedMsg: 'Notifications/NotificationNames/WarAllyOfferDeclined',
 notificationTypeBountyYourBountyClaimed: 'Notifications/NotificationNames/BountyOnYouClaimed',
 notificationTypeBountyPlacedChar: 'Notifications/NotificationNames/BountyPlacedOnYou',
 notificationTypeBountyPlacedCorp: 'Notifications/NotificationNames/BountyPlacedOnCorporation',
 notificationTypeBountyPlacedAlliance: 'Notifications/NotificationNames/BountyPlacedOnAlliance',
 notificationTypeKillRightAvailable: 'Notifications/NotificationNames/KillRightAvailable',
 notificationTypeKillRightAvailableOpen: 'Notifications/NotificationNames/KillRightAvailableToAll',
 notificationTypeKillRightEarned: 'Notifications/NotificationNames/KillRightEarned',
 notificationTypeKillRightUsed: 'Notifications/NotificationNames/KillRightUsed',
 notificationTypeKillRightUnavailable: 'Notifications/NotificationNames/KillRightUnavailable',
 notificationTypeKillRightUnavailableOpen: 'Notifications/NotificationNames/KillRightUnavailableToAll',
 notificationTypeDeclareWar: 'Notifications/NotificationNames/WarDeclaration',
 notificationTypeOfferedSurrender: 'Notifications/NotificationNames/SurrenderOffered',
 notificationTypeAcceptedSurrender: 'Notifications/NotificationNames/SurrenderAccepted',
 notificationTypeMadeWarMutual: 'Notifications/NotificationNames/WarMadeMutual',
 notificationTypeRetractsWar: 'Notifications/NotificationNames/WarRetracted',
 notificationTypeOfferedToAlly: 'Notifications/NotificationNames/YouOfferedWarAlly',
 notificationTypeOfferToAllyRetracted: 'Notifications/NotificationNames/YouRetractedAllyOffer',
 notificationTypeAcceptedAlly: 'Notifications/NotificationNames/YouAcceptedWarAlly',
 notificationTypeCharAppAcceptMsg: 'Notifications/NotificationNames/MercenaryInvitationAccepted',
 notificationTypeCharAppRejectMsg: 'Notifications/NotificationNames/MercenaryInvitationRejected',
 notificationTypeCharAppWithdrawMsg: 'Notifications/NotificationNames/MercenaryApplicationWithdrawn',
 notificationTypeDustAppAcceptedMsg: 'Notifications/NotificationNames/MercenaryApplicationAccepted',
 notificationTypeDistrictAttacked: 'Notifications/NotificationNames/CorporationDistrictAttacked',
 notificationTypeBattlePunishFriendlyFire: 'Notifications/NotificationNames/FriendlyFireStandingsLoss',
 notificationTypeMailSummary: 'Notifications/NotificationNames/NewMailSummary',
 notificationTypeNewMailFrom: 'Notifications/NotificationNames/NewMail',
 notificationTypeUnusedSkillPoints: 'Notifications/NotificationNames/UnusedSkillPoints',
 notificationTypeContractAssigned: 'Notifications/NotificationNames/ContractAssigned',
 notificationTypeContractAccepted: 'Notifications/NotificationNames/ContractAccepted',
 notificationTypeContractNeedsAttention: 'Notifications/NotificationNames/ContractNeedsAttention',
 notificationTypeKillReportVictim: 'Notifications/NotificationNames/KillReportYouDied',
 notificationTypeKillReportFinalBlow: 'Notifications/NotificationNames/KillReportFinalBlow',
 notificationTypeCorpFriendlyFireEnableTimerStarted: 'Notifications/NotificationNames/CorpFriendlyFireEnableTimerStarted',
 notificationTypeCorpFriendlyFireDisableTimerStarted: 'Notifications/NotificationNames/CorpFriendlyFireDisableTimerStarted',
 notificationTypeCorpFriendlyFireEnableTimerCompleted: 'Notifications/NotificationNames/CorpFriendlyFireEnableTimerCompleted',
 notificationTypeCorpFriendlyFireDisableTimerCompleted: 'Notifications/NotificationNames/CorpFriendlyFireDisableTimerCompleted',
 notificationTypePlexDeliveryDelay: 'Notifications/NotificationNames/PlexDeliveryDelay',
 notificationTypeGiftReceived: 'Notifications/NotificationNames/GiftReceived',
 notificationTypeGameTimeReceived: 'Notifications/NotificationNames/PlexDonationReceived',
 notificationTypeGameTimeSent: 'Notifications/NotificationNames/PlexDonationSent',
 notificationTypeGameTimeAdded: 'Notifications/NotificationNames/GameTimeAdded',
 notificationTypeEntosisCaptureStarted: 'Notifications/NotificationNames/SovereigntyCaptureStarted',
 notificationTypeStationServiceEnabled: 'Notifications/NotificationNames/SovereigntyServiceEnabled',
 notificationTypeStationServiceDisabled: 'Notifications/NotificationNames/SovereigntyServiceDisabled',
 notificationTypeStationServiceHalfCaptured: 'Notifications/NotificationNames/SovereigntyServiceHalfCaptured',
 notificationTypeInfrastructureHubBillAboutToExpire: 'Notifications/NotificationNames/SovereigntyIHubBillAboutToExpire',
 notificationTypeCCPDevNews: 'Notifications/NotificationNames/CCPDevNews',
 notificationTypeCCPServerNews: 'Notifications/NotificationNames/CCPServerNews',
 notificationTypeCCPGameNews: 'Notifications/NotificationNames/CCPGameNews',
 notificationTypeCCPOutOfGameNews: 'Notifications/NotificationNames/CCPOutOfGameNews',
 notificationTypeStructureFuelAlert: 'Notifications/NotificationNames/StructureFuelAlert',
 notificationTypeStructureAnchoring: 'Notifications/NotificationNames/StructureAnchoring',
 notificationTypeStructureUnanchoring: 'Notifications/NotificationNames/StructureUnanchoring',
 notificationTypeStructureUnderAttack: 'Notifications/NotificationNames/StructureUnderAttack',
 notificationTypeStructureOnline: 'Notifications/NotificationNames/StructureOnline',
 notificationTypeStructureLostShields: 'Notifications/NotificationNames/StructureLostShields',
 notificationTypeStructureLostArmor: 'Notifications/NotificationNames/StructureLostArmor',
 notificationTypeStructureDestroyed: 'Notifications/NotificationNames/StructureDestroyed',
 notificationTypeStructureItemsToAssetSafety: 'Notifications/NotificationNames/StructureItemsToAssetSafety',
 notificationTypeStructureItemsNeedAttention: 'Notifications/NotificationNames/StructureItemsNeedAttention',
 notificationTypeStructureMarketOrdersCancelled: 'Notifications/NotificationNames/StructureMarketOrdersCancelled',
 notificationTypeStructureLostDockingAccess: 'Notifications/NotificationNames/StructureLostDockingAccess',
 notificationTypeStructureServicesOffline: 'Notifications/NotificationNames/StructureServicesOffline',
 notificationTypeStructureItemsDelivered: 'Notifications/NotificationNames/StructureItemsDelivered',
 notificationTypeStructureCourierContractChanged: 'Notifications/NotificationNames/ContractDestinationChanged',
 notificationTypeStructureWentLowPower: 'Notifications/NotificationNames/StructureWentLowPower',
 notificationTypeStructureWentHighPower: 'Notifications/NotificationNames/StructureWentHighPower',
 notificationTypeStructuresReinforcementChanged: 'Notifications/NotificationNames/StructuresReinforcementChanged',
 notificationTypeStructuresJobsPaused: 'Notifications/NotificationNames/StructuresJobsPaused',
 notificationTypeStructuresJobsCancelled: 'Notifications/NotificationNames/StructuresJobsCancelled',
 notificationTypeStructureLowReagentsAlert: 'Notifications/NotificationNames/StructuresLowReagentsAlert',
 notificationTypeStructureNoReagentsAlert: 'Notifications/NotificationNames/StructuresNoReagentsAlert',
 notificationTypeSeasonalChallengeCompleted: 'Notifications/NotificationNames/SeasonalChallengeCompleted',
 notificationTypeCalendarEvent: 'Notifications/NotificationNames/CalendarEvent',
 notificationTypeNPCStandingsChanged: 'Notifications/NotificationNames/NPCStandingsChanged',
 notificationTypeMoonminingExtractionStarted: 'Notifications/NotificationNames/MoonminingExtractionStarted',
 notificationTypeMoonminingExtractionCancelled: 'Notifications/NotificationNames/MoonminingExtractionCancelled',
 notificationTypeMoonminingExtractionFinished: 'Notifications/NotificationNames/MoonminingExtractionFinished',
 notificationTypeMoonminingLaserFired: 'Notifications/NotificationNames/MoonminingLaserFired',
 notificationTypeMoonminingAutomaticFracture: 'Notifications/NotificationNames/MoonminingAutomaticFracture',
 notificationTypeAlphaInjectorAvailable: 'Notifications/NotificationNames/AlphaInjectorAvailable',
 notificationTypeImplantPluggedIn: 'Notifications/NotificationNames/ImplantPluggedIn',
 notificationTypeBoosterConsumed: 'Notifications/NotificationNames/BoosterConsumed',
 notificationTypeCorpBecameWarEligible: 'Notifications/NotificationNames/CorpBecameWarEligible',
 notificationTypeCorpNotLongerWarEligible: 'Notifications/NotificationNames/CorpNoLongerWarEligible',
 notificationTypeWarHQRemovedFromSpace: 'Notifications/NotificationNames/WarHQLost',
 notificationTypeWarMutualWarInviteSent: 'Notifications/NotificationNames/WarMutualWarInviteSent',
 notificationTypeWarMutualWarInviteRejected: 'Notifications/NotificationNames/WarMutualWarInviteRejected',
 notificationTypeWarMutualWarInviteAccepted: 'Notifications/NotificationNames/WarMutualWarInviteAccepted',
 notificationTypeInvasionSystemLogin: 'Notifications/NotificationNames/InvasionSystem',
 notificationTypeInvasionSystemStart: 'Notifications/NotificationNames/InvasionSystem',
 notificationTypeInvasionCompletedMsg: 'Notifications/NotificationNames/InvasionComplete',
 notificationTypeWarDeclared: 'Notifications/NotificationNames/WarDeclared',
 notificationTypeWarAdopted: 'Notifications/NotificationNames/WarAdopted',
 notificationTypeWarMutualWarExpired: 'Notifications/NotificationNames/WarMutualWarExpired',
 notificationTypeWarInherited: 'Notifications/NotificationNames/WarInherited',
 notificationTypeWarAllyInherited: 'Notifications/NotificationNames/WarAllyInherited',
 notificationTypeWarConcordInvalidates: 'Notifications/NotificationNames/WarConcordInvalidates',
 notificationTypeWarRetracted: 'Notifications/NotificationNames/WarRetracted',
 notificationTypeWarRetractedByConcord: 'Notifications/NotificationNames/WarRetractedByConcord',
 notificationTypeWarInvalid: 'Notifications/NotificationNames/WarInvalid',
 notificationTypeNewOfferAvailable: 'Notifications/NotificationNames/NewOfferAvailable',
 notificationTypeOfferPurchased: 'Notifications/NotificationNames/NewOfferAvailable',
 notificationTypeAddictionWarning: 'Notifications/NotificationNames/AddictionWarning',
 notificationTypeRaffleCreated: 'Notifications/NotificationNames/HyperNetOfferCreated',
 notificationTypeRaffleExpired: 'Notifications/NotificationNames/HyperNetOfferExpired',
 notificationTypeRaffleFinished: 'Notifications/NotificationNames/HyperNetOfferFinished',
 notificationTypeWarEndedHqSecurityDrop: 'Notifications/NotificationNames/WarEndedHqSecurityDrop',
 notificationTypeStructureImpendingAbandonmentAssetsAtRisk: 'Notifications/NotificationNames/StructureImpendingAbandonmentAssetsAtRisk',
 notificationTypeOfficeLeaseCanceledInsufficientStandings: 'Notifications/NotificationNames/OfficeLeaseCanceledInsufficientStandings',
 notificationTypeContractRegionChangedToPochven: 'Notifications/NotificationNames/ContractRegionChangedToPochven',
 notificationTypeEssMainBankLink: 'Notifications/NotificationNames/EssMainBankLink',
 notificationTypeEssLinkDisconnected: 'Notifications/NotificationNames/EssLinkDisconnected',
 notificationTypeEssReserveBankUnlocked: 'Notifications/NotificationNames/EssReserveBankUnlock',
 notificationTypeEssInventoryFull: 'Notifications/NotificationNames/EssInventoryFull',
 notificationTypeCorpCosmeticLicensePurchased: 'Notifications/NotificationNames/CosmeticLicenseGranted',
 notificationTypeAllianceCosmeticLicensePurchased: 'Notifications/NotificationNames/CosmeticLicenseGranted',
 notificationTypeDailyGoalCompleted: 'Notifications/NotificationNames/DailyGoalCompleted',
 notificationTypeDailyMilestoneCompleted: 'Notifications/NotificationNames/DailyGoalCompleted',
 notificationTypeDailyRewardTrackCompleted: 'Notifications/NotificationNames/DailyGoalCompleted',
 notificationTypeCorpGoalCreated: 'Notifications/Corporations/CorporationGoalCreatedTitle',
 notificationTypeCorpGoalClosed: 'Notifications/Corporations/CorporationGoalClosedTitle',
 notificationTypeCorpGoalCompleted: 'Notifications/Corporations/CorporationGoalCompletedTitle',
 notificationTypeInsurgencyStarting: 'Notifications/NotificationNames/InsurgencyForecasting',
 notificationTypeInsurgencyStarted: 'Notifications/NotificationNames/InsurgencyStarted',
 notificationTypeInsurgencyEndedPiratesWin: 'Notifications/NotificationNames/InsurgencyEndedPiratesWin',
 notificationTypeInsurgencyEndedAntiPiratesWin: 'Notifications/NotificationNames/InsurgencyEndedAntiPiratesWin',
 notificationTypeInsurgencyEndedNoOneWins: 'Notifications/NotificationNames/InsurgencyEndedNoOneWins',
 notificationTypeInsurgencyStage5Corruption: 'Notifications/NotificationNames/InsurgencyFullyCorruptedSystem',
 notificationTypeInsurgencyStage5Suppression: 'Notifications/NotificationNames/InsurgencyFullySuppressedSystem',
 notificationTypeCorpGoalNameChange: 'Notifications/Corporations/CorporationGoalNameChangeTitle',
 notificationTypeCorpGoalExpired: 'Notifications/Corporations/GoalExpiredTitle',
 notificationTypeCorpGoalLimitReached: 'Notifications/Corporations/GoalLimitReachedTitle',
 notificationTypeCorpLeft: 'Notifications/Corporations/LeftTitle',
 notificationTypeSkinSequencingCompleted: 'Notifications/Cosmetics/SkinSequencingCompletedTitle',
 notificationTypeShipGroupUnlocked: 'Notifications/ShipTree/NewShipsUnlockedTitle',
 notificationTypeSkyhookLinkStarted: 'UI/OrbitalSkyhook/Notifications/LinkStartedSettingName',
 notificationTypeSkyhookTheftVulnerabilityStarted: 'UI/OrbitalSkyhook/Notifications/TheftVulnerabilityStarted',
 notificationTypeSkyhookDeployed: 'Notifications/NotificationNames/SkyhookDeployed',
 notificationTypeSkyhookOnline: 'Notifications/NotificationNames/SkyhookOnlining',
 notificationTypeSkyhookUnderAttack: 'Notifications/NotificationNames/SkyhookUnderAttack',
 notificationTypeSkyhookLostShields: 'Notifications/NotificationNames/SkyhookLostShields',
 notificationTypeSkyhookDestroyed: 'Notifications/NotificationNames/SkyhookDestroyed',
 notificationTypeStructurePaintPurchased: 'Notifications/NotificationNames/StructurePaintPurchased',
 notificationTypeDailyItemRewardAutoClaimed: 'Notifications/DailyGoals/DailyGoalAutoRedeemedItemTitle',
 notificationTypeMercenaryDenReinforced: 'Notifications/NotificationNames/MercenaryDenReinforced',
 notificationTypeMercDenAttacked: 'Notifications/NotificationNames/MercDenAttacked',
 notificationTypeMercDenNewMTO: 'Notifications/NotificationNames/MercDenNewMTO'}
depricatedNotifications = (notificationTypeOperationFinished,
 notificationTypeCombatOperationFinished,
 notificationTypeIndustryOperationFinished,
 notificationTypeAchievementTaskFinished,
 notificationTypeOpportunityFinished,
 notificationTypeQuestComplete,
 notificationTypeBountyESSTaken_deprecated,
 notificationTypeBountyESSShared_deprecated)
groupUnread = 0
groupAgents = 1
groupBills = 2
groupCorp = 3
groupMisc = 4
groupOld = 5
groupSov = 6
groupStructures = 7
groupWar = 8
groupContacts = 9
groupBounties = 10
groupInsurance = 11
groupSkillTraining = 12
groupCCPNotifications = 14
groupRaffle = 15
groupInsurgencies = 16
groupTypes = {groupSkillTraining: [notificationTypeSkillEmptyQueue,
                      notificationTypeSkillFinished,
                      notificationTypeUnusedSkillPoints,
                      notificationTypeSkillInjected,
                      notificationTypeSkillsAddedFromSkillPlan,
                      notificationTypeShipGroupUnlocked],
 groupAgents: [notificationTypeAgentMoveMsg,
               notificationTypeLocateCharMsg,
               notificationTypeResearchMissionAvailableMsg,
               notificationTypeMissionOfferExpirationMsg,
               notificationTypeMissionTimeoutMsg,
               notificationTypeStoryLineMissionAvailableMsg,
               notificationTypeTutorialMsg,
               notificationTypeMissionCanceledTriglavian,
               notificationTypeAgentRetiredTriglavian],
 groupBills: [notificationTypeAllMaintenanceBillMsg,
              notificationTypeCharBillMsg,
              notificationTypeCorpAllBillMsg,
              notificationTypeBillOutOfMoneyMsg,
              notificationTypeBillPaidCharMsg,
              notificationTypeBillPaidCorpAllMsg,
              notificationTypeCorpOfficeExpirationMsg,
              notificationTypeOfficeLeaseCanceledInsufficientStandings],
 groupContacts: [notificationTypeContactAdd,
                 notificationTypeContactEdit,
                 notificationTypeContactSignedOn,
                 notificationTypeContactSignedOff,
                 notificationTypeBuddyConnectContactAdd,
                 notificationTypeContractRegionChangedToPochven],
 groupCorp: [notificationTypeCharTerminationMsg,
             notificationTypeCharMedalMsg,
             notificationTypeCorpAppNewMsg,
             notificationTypeCorpAppRejectMsg,
             notificationTypeCorpAppRejectCustomMsg,
             notificationTypeCorpAppAcceptMsg,
             notificationTypeCorpAppInvitedMsg,
             notificationTypeCorpTaxChangeMsg,
             notificationTypeCorpNewsMsg,
             notificationTypeCharLeftCorpMsg,
             notificationTypeCorpNewCEOMsg,
             notificationTypeCorpDividendMsg,
             notificationTypeCorpVoteMsg,
             notificationTypeCorpVoteCEORevokedMsg,
             notificationTypeCorpLiquidationMsg,
             notificationTypeCorpKicked,
             notificationTypeCharAppAcceptMsg,
             notificationTypeCharAppRejectMsg,
             notificationTypeCharAppWithdrawMsg,
             notificationTypeDustAppAcceptedMsg,
             notificationTypeCorpFriendlyFireEnableTimerStarted,
             notificationTypeCorpFriendlyFireDisableTimerStarted,
             notificationTypeCorpFriendlyFireEnableTimerCompleted,
             notificationTypeCorpFriendlyFireDisableTimerCompleted,
             notificationTypeCorpGoalCreated,
             notificationTypeCorpGoalCompleted,
             notificationTypeCorpGoalClosed,
             notificationTypeCorpGoalNameChange,
             notificationTypeCorpGoalExpired,
             notificationTypeCorpGoalLimitReached,
             notificationTypeCorpLeft],
 groupInsurance: {notificationTypeInsuranceFirstShipMsg,
                  notificationTypeInsurancePayoutMsg,
                  notificationTypeInsuranceInvalidatedMsg,
                  notificationTypeInsuranceExpirationMsg,
                  notificationTypeInsuranceIssuedMsg},
 groupMisc: [notificationTypeCloneActivationMsg2,
             notificationTypeContainerPasswordMsg,
             notificationTypeCustomsMsg,
             notificationTypeCloneRevokedMsg1,
             notificationTypeCloneMovedMsg,
             notificationTypeCloneRevokedMsg2,
             notificationTypeJumpCloneDeletedMsg1,
             notificationTypeJumpCloneDeletedMsg2,
             notificationTypeTransactionReversalMsg,
             notificationTypeReimbursementMsg,
             notificationTypeIncursionCompletedMsg,
             notificationTypeKillRightAvailable,
             notificationTypeKillRightAvailableOpen,
             notificationTypeKillRightEarned,
             notificationTypeKillRightUsed,
             notificationTypeKillRightUnavailable,
             notificationTypeKillRightUnavailableOpen,
             notificationTypeBattlePunishFriendlyFire,
             notificationTypeMailSummary,
             notificationTypeNewMailFrom,
             notificationTypeContractAssigned,
             notificationTypeContractAccepted,
             notificationTypeContractNeedsAttention,
             notificationTypePlexDeliveryDelay,
             notificationTypeGiftReceived,
             notificationTypeGameTimeReceived,
             notificationTypeGameTimeSent,
             notificationTypeGameTimeAdded,
             notificationTypeSeasonalChallengeCompleted,
             notificationTypeStructureItemsDelivered,
             notificationTypeStructureCourierContractChanged,
             notificationTypeCalendarEvent,
             notificationTypeNPCStandingsChanged,
             notificationTypeAlphaInjectorAvailable,
             notificationTypeImplantPluggedIn,
             notificationTypeBoosterConsumed,
             notificationTypeInvasionSystemLogin,
             notificationTypeInvasionSystemStart,
             notificationTypeInvasionCompletedMsg,
             notificationTypeEssMainBankLink,
             notificationTypeEssLinkDisconnected,
             notificationTypeEssReserveBankUnlocked,
             notificationTypeEssInventoryFull,
             notificationTypeExpertSystemExpired,
             notificationTypeExpertSystemExpiryImminent,
             notificationTypeCorpCosmeticLicensePurchased,
             notificationTypeAllianceCosmeticLicensePurchased,
             notificationTypeDailyGoalCompleted,
             notificationTypeDailyMilestoneCompleted,
             notificationTypeDailyRewardTrackCompleted,
             notificationTypeSPAutoRedeemed,
             notificationTypeLPAutoRedeemed,
             notificationTypeSkinSequencingCompleted,
             notificationTypeDailyItemRewardAutoClaimed],
 groupOld: [notificationTypeOldLscMessages],
 groupSov: [notificationTypeSovAllClaimFailMsg,
            notificationTypeSovCorpClaimFailMsg,
            notificationTypeSovAllBillLateMsg,
            notificationTypeSovCorpBillLateMsg,
            notificationTypeSovAllClaimLostMsg,
            notificationTypeSovCorpClaimLostMsg,
            notificationTypeSovAllClaimAquiredMsg,
            notificationTypeSovCorpClaimAquiredMsg,
            notificationTypeSovDisruptorMsg,
            notificationTypeAllStructVulnerableMsg,
            notificationTypeAllStrucInvulnerableMsg,
            notificationTypeSovereigntyTCUDamageMsg,
            notificationTypeSovereigntySBUDamageMsg,
            notificationTypeSovereigntyIHDamageMsg,
            notificationTypeEntosisCaptureStarted,
            notificationTypeStationServiceEnabled,
            notificationTypeStationServiceDisabled,
            notificationTypeStationServiceHalfCaptured,
            notificationTypeInfrastructureHubBillAboutToExpire,
            notificationTypeSovStructureReinforced,
            notificationTypeSovCommandNodeEventStarted,
            notificationTypeSovStructureDestroyed,
            notificationTypeSovStationEnteredFreeport,
            notificationTypeIHubDestroyedByBillFailure,
            notificationTypeAllianceCapitalChanged,
            notificationTypeSovStructureSelfDestructRequested,
            notificationTypeSovStructureSelfDestructCancel,
            notificationTypeSovStructureSelfDestructFinished],
 groupStructures: [notificationTypeAllAnchoringMsg,
                   notificationTypeCorpStructLostMsg,
                   notificationTypeTowerAlertMsg,
                   notificationTypeTowerResourceAlertMsg,
                   notificationTypeStationAggressionMsg1,
                   notificationTypeStationStateChangeMsg,
                   notificationTypeStationConquerMsg,
                   notificationTypeStationAggressionMsg2,
                   notificationTypeOrbitalAttacked,
                   notificationTypeOrbitalReinforced,
                   notificationTypeOwnershipTransferred,
                   notificationTypeDistrictAttacked,
                   notificationTypeStructureFuelAlert,
                   notificationTypeStructureAnchoring,
                   notificationTypeStructureUnanchoring,
                   notificationTypeStructureUnderAttack,
                   notificationTypeStructureOnline,
                   notificationTypeStructureLostShields,
                   notificationTypeStructureLostArmor,
                   notificationTypeStructureDestroyed,
                   notificationTypeStructureItemsToAssetSafety,
                   notificationTypeStructureItemsNeedAttention,
                   notificationTypeStructureMarketOrdersCancelled,
                   notificationTypeStructureServicesOffline,
                   notificationTypeStructureWentLowPower,
                   notificationTypeStructureWentHighPower,
                   notificationTypeStructuresReinforcementChanged,
                   notificationTypeStructuresJobsPaused,
                   notificationTypeStructuresJobsCancelled,
                   notificationTypeStructureImpendingAbandonmentAssetsAtRisk,
                   notificationTypeMoonminingExtractionStarted,
                   notificationTypeMoonminingExtractionCancelled,
                   notificationTypeMoonminingExtractionFinished,
                   notificationTypeMoonminingLaserFired,
                   notificationTypeMoonminingAutomaticFracture,
                   notificationTypeStructurePaintPurchased,
                   notificationTypeSkyhookLinkStarted,
                   notificationTypeSkyhookTheftVulnerabilityStarted,
                   notificationTypeStructureLowReagentsAlert,
                   notificationTypeStructureNoReagentsAlert,
                   notificationTypeSkyhookOnline,
                   notificationTypeSkyhookLostShields,
                   notificationTypeSkyhookUnderAttack,
                   notificationTypeSkyhookDestroyed,
                   notificationTypeSkyhookDeployed,
                   notificationTypeMercenaryDenReinforced,
                   notificationTypeMercDenAttacked,
                   notificationTypeMercDenNewMTO],
 groupWar: [notificationTypeAllWarDeclaredMsg,
            notificationTypeAllWarDeclaredMsg2,
            notificationTypeAllWarSurrenderMsg,
            notificationTypeAllWarRetractedMsg,
            notificationTypeAllWarInvalidatedMsg,
            notificationTypeCorpWarDeclaredMsg,
            notificationTypeCorpWarDeclaredMsg2,
            notificationTypeCorpWarFightingLegalMsg,
            notificationTypeCorpWarSurrenderMsg,
            notificationTypeCorpWarRetractedMsg,
            notificationTypeCorpWarInvalidatedMsg,
            notificationTypeFWCorpJoinMsg,
            notificationTypeFWCorpLeaveMsg,
            notificationTypeFWCorpKickMsg,
            notificationTypeFWCharKickMsg,
            notificationTypeFWCorpWarningMsg,
            notificationTypeFWCharWarningMsg,
            notificationTypeFWCharRankLossMsg,
            notificationTypeFWCharRankGainMsg,
            notificationTypeFacWarCorpJoinRequestMsg,
            notificationTypeFacWarCorpLeaveRequestMsg,
            notificationTypeFacWarCorpJoinWithdrawMsg,
            notificationTypeFacWarCorpLeaveWithdrawMsg,
            notificationTypeFWAllianceWarningMsg,
            notificationTypeFWAllianceKickMsg,
            notificationTypeAllWarCorpJoinedAllianceMsg,
            notificationTypeAllyJoinedWarDefenderMsg,
            notificationTypeAllyJoinedWarAggressorMsg,
            notificationTypeAllyJoinedWarAllyMsg,
            notificationTypeMercOfferedNegotiationMsg,
            notificationTypeWarSurrenderOfferMsg,
            notificationTypeWarSurrenderDeclinedMsg,
            notificationTypeFacWarLPPayoutKill,
            notificationTypeFacWarLPPayoutEvent,
            notificationTypeFacWarLPDisqualifiedEvent,
            notificationTypeFacWarLPDisqualifiedKill,
            notificationTypeAllyContractCancelled,
            notificationTypeWarAllyOfferDeclinedMsg,
            notificationTypeDeclareWar,
            notificationTypeOfferedSurrender,
            notificationTypeAcceptedSurrender,
            notificationTypeMadeWarMutual,
            notificationTypeRetractsWar,
            notificationTypeOfferedToAlly,
            notificationTypeAcceptedAlly,
            notificationTypeKillReportVictim,
            notificationTypeKillReportFinalBlow,
            notificationTypeCorpBecameWarEligible,
            notificationTypeCorpNotLongerWarEligible,
            notificationTypeWarHQRemovedFromSpace,
            notificationTypeWarMutualWarInviteSent,
            notificationTypeWarMutualWarInviteRejected,
            notificationTypeWarMutualWarInviteAccepted,
            notificationTypeWarDeclared,
            notificationTypeWarAdopted,
            notificationTypeWarMutualWarExpired,
            notificationTypeWarInherited,
            notificationTypeWarAllyInherited,
            notificationTypeWarConcordInvalidates,
            notificationTypeWarRetracted,
            notificationTypeWarRetractedByConcord,
            notificationTypeWarInvalid,
            notificationTypeMercOfferRetractedMsg,
            notificationTypeOfferToAllyRetracted,
            notificationTypeWarEndedHqSecurityDrop],
 groupBounties: [notificationTypeBountyClaimMsg,
                 notificationTypeBountyYourBountyClaimed,
                 notificationTypeBountyPlacedChar,
                 notificationTypeBountyPlacedCorp,
                 notificationTypeBountyPlacedAlliance],
 groupCCPNotifications: [notificationTypeCCPDevNews,
                         notificationTypeCCPServerNews,
                         notificationTypeCCPGameNews,
                         notificationTypeCCPOutOfGameNews,
                         notificationTypeNewOfferAvailable,
                         notificationTypeOfferPurchased],
 groupRaffle: [notificationTypeRaffleCreated, notificationTypeRaffleExpired, notificationTypeRaffleFinished],
 groupInsurgencies: [notificationTypeInsurgencyStarting,
                     notificationTypeInsurgencyStarted,
                     notificationTypeInsurgencyEndedPiratesWin,
                     notificationTypeInsurgencyEndedAntiPiratesWin,
                     notificationTypeInsurgencyEndedNoOneWins,
                     notificationTypeInsurgencyStage5Corruption,
                     notificationTypeInsurgencyStage5Suppression]}
nonCommunicationTypes = [notificationTypeGameTimeAdded,
 notificationTypeContactSignedOn,
 notificationTypeContactSignedOff,
 notificationTypeMailSummary,
 notificationTypeNewMailFrom,
 notificationTypeUnusedSkillPoints,
 notificationTypeContractAssigned,
 notificationTypeContractAccepted,
 notificationTypeContractNeedsAttention,
 notificationTypeKillReportFinalBlow,
 notificationTypeKillReportVictim,
 notificationTypePlexDeliveryDelay,
 notificationTypeServerShutdown,
 notificationTypeCalendarEvent,
 notificationTypeNPCStandingsChanged,
 notificationTypeTicketReply,
 notificationTypeAlphaInjectorAvailable,
 notificationTypeSeasonalChallengeCompleted,
 notificationTypeNewOfferAvailable,
 notificationTypeOfferPurchased] + groupTypes[groupSkillTraining]
groupNamePaths = {groupAgents: 'Notifications/groupAgents',
 groupBills: 'Notifications/groupBills',
 groupContacts: 'Notifications/groupContacts',
 groupCorp: 'Notifications/groupCorporation',
 groupMisc: 'Notifications/groupMisc',
 groupOld: 'Notifications/groupOld',
 groupSov: 'Notifications/groupSovereignty',
 groupStructures: 'Notifications/groupStructures',
 groupWar: 'Notifications/groupWar',
 groupBounties: 'Notifications/groupBounties',
 groupInsurance: 'UI/Station/Insurance',
 groupInsurgencies: 'UI/PirateInsurgencies/dashboardCaption'}
groupNamePathsNewNotifications = {groupAgents: 'Notifications/groupAgents',
 groupBills: 'Notifications/groupBills',
 groupContacts: 'Notifications/groupContacts',
 groupCorp: 'Notifications/groupCorporation',
 groupMisc: 'Notifications/groupMisc',
 groupOld: 'Notifications/groupOld',
 groupSov: 'Notifications/groupSovereignty',
 groupStructures: 'Notifications/groupStructures',
 groupWar: 'Notifications/groupWar',
 groupBounties: 'Notifications/groupBounties',
 groupSkillTraining: 'Notifications/GroupNames/groupSkillTraining',
 groupInsurance: 'UI/Station/Insurance',
 groupCCPNotifications: 'Notifications/GroupNames/groupCCPNotifications',
 groupRaffle: 'Notifications/groupHyperNet',
 groupInsurgencies: 'UI/PirateInsurgencies/dashboardCaption'}
notificationGroupUnread = groupUnread
notificationGroupAgents = groupAgents
notificationGroupBills = groupBills
notificationGroupCorp = groupCorp
notificationGroupMisc = groupMisc
notificationGroupOld = groupOld
notificationGroupSov = groupSov
notificationGroupStructures = groupStructures
notificationGroupWar = groupWar
notificationGroupContacts = groupContacts
notificationGroupBounties = groupBounties
notificationGroupInsurgencies = groupInsurgencies
notificationDisplaySender = [notificationTypeCorpOfficeExpirationMsg,
 notificationTypeSovereigntyTCUDamageMsg,
 notificationTypeSovereigntySBUDamageMsg,
 notificationTypeSovereigntyIHDamageMsg,
 notificationTypeCharTerminationMsg,
 notificationTypeCharMedalMsg,
 notificationTypeNewMailFrom,
 notificationTypeInfrastructureHubBillAboutToExpire,
 notificationTypeSovStructureReinforced,
 notificationTypeSovCommandNodeEventStarted,
 notificationTypeSovStructureDestroyed,
 notificationTypeSovStructureSelfDestructRequested,
 notificationTypeSovStructureSelfDestructCancel,
 notificationTypeSovStructureSelfDestructFinished,
 notificationTypeSovStationEnteredFreeport,
 notificationTypeIHubDestroyedByBillFailure,
 notificationTypeAllianceCapitalChanged,
 notificationTypeEntosisCaptureStarted,
 notificationTypeStationServiceDisabled,
 notificationTypeStationServiceEnabled,
 notificationTypeStationServiceHalfCaptured,
 notificationTypeNPCStandingsChanged] + groupTypes[groupAgents] + groupTypes[groupCorp] + groupTypes[groupContacts]
for notificationType in corpGoalNotificationTypes:
    notificationDisplaySender.remove(notificationType)

notificationShowStanding = [notificationTypeContactSignedOn, notificationTypeContactSignedOff, notificationTypeNewMailFrom]
notificationAlwaysPopup = [notificationTypeAddictionWarning]
MIN_FADE_DELAY_SECONDS = {notificationTypeAddictionWarning: 4}

def GetTypeGroup(typeID):
    for groupID, typeIDs in groupTypes.iteritems():
        if typeID in typeIDs:
            return groupID


def IsTypeInCommunications(typeID):
    if typeID in nonCommunicationTypes:
        return False
    else:
        return True
