#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\shared\loginRewards\rewardUiConst.py
from carbonui.services.setting import UserSettingBool
REWARD_WND_OPEN_ON_LOGIN_SETTING = UserSettingBool('openRewardWindowOnLogin', True)
REWARD_ROOKIE_BTN = 'rookieBtn'
REWARD_SEASONAL_BTN = 'seasonalBtn'
REWARD_EVERGREEN_BTN = 'evergreenBtn'
LOGIN_REWARDS_WINDOW_ID = 'rewardsWnd'
REWARD_WND_WIDTH = 1075
REWARD_WND_HEIGHT = 680
BACKGROUND_WIDTH = 1068
BACKGROUND_HEIGHT = 614
SEASON_BACKGROUND_WIDTH = 1602
SEASON_BACKGROUND_HEIGHT = 614
TOP_SUBTEXT_HEIGHT = 30
TOP_HEIGHT = 190
BOTTOM_BORDER_HEIGHT = 35
DEFAULT_FANFARE_COLOR = (0.7, 0.85, 1, 1)
SCROLL_ANIMATION = 0.1
SCROLL_ANIMATION_AUTO_STEP = 0.5
TODAYS_SIDE_PADDING = 15
TODAYS_HEADER_FILL_COLOR = (0, 0, 0, 0.5)
DEFAULT_BANNER = 'res:/UI/Texture/classes/LoginCampaign/backgrounds/default.png'
CAMPAIGN_STATUS_ONGOING = 1
CAMPAIGN_STATUS_SUCCESSFULLY_COMPLETED = 2
CAMPAIGN_STATUS_ENDING = 3
ONLY_ALPHA_GIFT_REWARDED = 1
ONLY_OMEGA_GIFT_REWARDED = 2
ALPHA_OMEGA_GIFTS_REWARDED = 3
BLUE_TEXT_COLOR = (0.21, 0.62, 0.74, 1.0)
GREEN_CHECKMARK = (58 / 255.0,
 188 / 255.0,
 21 / 255.0,
 1.0)
DLI_ENTRY = 1
ALPHA_SEASONAL_ENTRY = 2
OMEGA_SEASONAL_ENTRY = 3

class BaseRewardPanelConst(object):
    CENTER_TOP_HEIGHT = 24
    CENTER_BOTTOM_HEIGHT = 72
    SIDE_PADDING = 12
    SECTION_DIVIDER = 10
    PROGRESS_BAR_HEIGHT = 32
    DAY_TEXT_BANNER_HEIGHT = 26
    CONGRATS_OFFSET = 0
    SHOW_BROWSE_CONTROLS = True
    SHOW_REWARD_COUNTER = True
    ICON_SIZE = 64
    ICON_SIZE_NEW_ITEM = 64
    DAY_WIDTH = 0
    DAY_HEIGHT = 0
    ENTRY_WIDTH = 0
    ENTRY_HEIGHT = 0
    NUM_VISIBLE_ITEMS = 0
    ALL_VISIBLE_DAYS_WIDTH = 0
    LEFT_WIDTH = 0
    DAY_TEXT_PADDING = (0, 0, 0, 0)
    SELECTED_CELL = 1
    SHOW_DAY_NUM = True
    SHOW_CLAIMED = True
    SHOW_NEXT_GIFT = True
    SELECTED_OFFSET = False
    CRATES_HAVE_INFO = True
    VERTICAL_OFFSET = 0


class RookieRewardPanelConst(BaseRewardPanelConst):
    DAY_WIDTH = 100
    DAY_HEIGHT = 125
    TODAY_HEIGHT = 144
    ENTRY_WIDTH = DAY_WIDTH + 6
    ENTRY_HEIGHT = DAY_HEIGHT + 96
    NUM_VISIBLE_ITEMS = 7
    ALL_VISIBLE_DAYS_WIDTH = NUM_VISIBLE_ITEMS * ENTRY_WIDTH
    LEFT_WIDTH = ALL_VISIBLE_DAYS_WIDTH + 2 * BaseRewardPanelConst.SIDE_PADDING
    DAY_TEXT_PADDING = (0, 24, 0, 0)
    VERTICAL_OFFSET = -12


class EvergreenPanelConst(BaseRewardPanelConst):
    SHOW_BROWSE_CONTROLS = False
    SHOW_REWARD_COUNTER = False
    DAY_WIDTH = 120
    DAY_HEIGHT = 125
    TODAY_HEIGHT = 144
    ENTRY_WIDTH = DAY_WIDTH + 25
    ENTRY_HEIGHT = DAY_HEIGHT + 96
    ICON_SIZE = 74
    SELECTED_CELL = 0
    NUM_VISIBLE_ITEMS = 5
    ALL_VISIBLE_DAYS_WIDTH = NUM_VISIBLE_ITEMS * ENTRY_WIDTH
    LEFT_WIDTH = ALL_VISIBLE_DAYS_WIDTH + 2 * BaseRewardPanelConst.SIDE_PADDING
    DAY_TEXT_PADDING = (0, 24, 0, 0)
    SHOW_DAY_NUM = False
    SHOW_CLAIMED = True
    SHOW_NEXT_GIFT = False
    SELECTED_OFFSET = True
    CRATES_HAVE_INFO = False
    VERTICAL_OFFSET = -8


class SeasonRewardPanelConst(BaseRewardPanelConst):
    SIDE_PADDING = 5
    DAY_WIDTH = 94
    DAY_HEIGHT = 90
    TODAY_HEIGHT = 0
    ENTRY_WIDTH = DAY_WIDTH + 4
    ENTRY_HEIGHT = DAY_HEIGHT + 60
    NUM_VISIBLE_ITEMS = 7
    CLONE_COLUMN_WIDTH = 27
    ALL_VISIBLE_DAYS_WIDTH = NUM_VISIBLE_ITEMS * ENTRY_WIDTH
    TRACK_ARROW_WIDTH = 27
    LEFT_WIDTH = ALL_VISIBLE_DAYS_WIDTH + 1 * SIDE_PADDING + CLONE_COLUMN_WIDTH + TRACK_ARROW_WIDTH
    DAY_TEXT_PADDING = (0, 4, 0, 4)


class ReminderRewardPanelConst(BaseRewardPanelConst):
    DAY_WIDTH = 280
    DAY_HEIGHT = 134
    TODAY_HEIGHT = 134
    CONGRATS_OFFSET = 35
    ENTRY_SIDE_PADDING = 20
    ENTRY_WIDTH = DAY_WIDTH + 2 * ENTRY_SIDE_PADDING
    ENTRY_HEIGHT = DAY_HEIGHT
    NUM_VISIBLE_ITEMS = 1
    ALL_VISIBLE_DAYS_WIDTH = NUM_VISIBLE_ITEMS * ENTRY_WIDTH
    SELECTED_CELL = 0
