#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\pirateinsurgency\const.py
CAMPAIGN_STATE_INITIAL = 1
CAMPAIGN_STATE_FORECASTING = 2
CAMPAIGN_STATE_ACTIVE = 3
CAMPAIGN_STATE_PIRATE_WIN = 4
CAMPAIGN_STATE_ANTIPIRATE_WIN = 5
CAMPAIGN_STATE_NO_WINNER = 6
CAMPAIGN_STATE_CLEANUP = 7
CAMPAIGN_STATE_TERMINAL = 99
ALL_CAMPAIGN_STATES = frozenset([CAMPAIGN_STATE_INITIAL,
 CAMPAIGN_STATE_FORECASTING,
 CAMPAIGN_STATE_ACTIVE,
 CAMPAIGN_STATE_PIRATE_WIN,
 CAMPAIGN_STATE_ANTIPIRATE_WIN,
 CAMPAIGN_STATE_NO_WINNER,
 CAMPAIGN_STATE_CLEANUP,
 CAMPAIGN_STATE_TERMINAL])
CAMPAIGN_STATE_NAMES = {CAMPAIGN_STATE_INITIAL: 'INITIAL',
 CAMPAIGN_STATE_FORECASTING: 'FORECASTING',
 CAMPAIGN_STATE_ACTIVE: 'ACTIVE',
 CAMPAIGN_STATE_PIRATE_WIN: 'PIRATE_WIN',
 CAMPAIGN_STATE_ANTIPIRATE_WIN: 'ANTIPIRATE_WIN',
 CAMPAIGN_STATE_NO_WINNER: 'NO_WINNER',
 CAMPAIGN_STATE_CLEANUP: 'CLEANUP',
 CAMPAIGN_STATE_TERMINAL: 'TERMINAL'}
PIRATE_BADGE = 'res:/UI/Texture/classes/pirateinsurgencies/faction_badges/corruption.png'
ANTIPIRATE_BADGE = 'res:/UI/Texture/classes/pirateinsurgencies/faction_badges/suppression.png'

def get_state_debug_string(stateID):
    return '{0}<{1}>'.format(stateID, CAMPAIGN_STATE_NAMES.get(stateID, 'UNKNOWN_STATE?'))
