#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\cosmetics\client\ships\skins\live_data\current_skin_design_signals.py
from signals import Signal
on_design_reset = Signal('on_new_design_initialized')
on_existing_design_loaded = Signal('on_existing_design_loaded')
on_name_changed = Signal('on_name_changed')
on_line_name_changed = Signal('on_line_name_changed')
on_ship_type_id_changed = Signal('on_ship_type_id_changed')
on_slot_fitting_changed = Signal('on_slot_fitting_changed')
on_tier_level_changed = Signal('on_tier_level_changed')
on_component_instance_license_to_use_changed = Signal('on_component_instance_license_to_use_changed')
on_snapshot_changed = Signal('on_snapshot_changed')
on_pattern_blend_mode_changed = Signal('on_pattern_blend_mode_changed')
on_component_attribute_changed = Signal('on_component_attribute_changed(slot_id, attribute_id, value')
on_undo_history_change = Signal('on_undo_history_change')
on_slot_selected = Signal('on_slot_selected')
