#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\shared\neocom\neocom\neocomConst.py
from carbonui import const as uiconst
import neocom2.btnIDs as btnIDs
ICONPATH_DEFAULT = 'res:/ui/Texture/WindowIcons/other.png'
ICONPATH_GROUP = 'res:/ui/Texture/WindowIcons/folder.png'
ICONPATH_CHAT = 'res:/ui/Texture/WindowIcons/chatchannel.png'
ICONPATH_BOOKMARKS = 'res:/ui/Texture/WindowIcons/browser.png'
BTNTYPE_CMD = 1
BTNTYPE_WINDOW = 2
BTNTYPE_GROUP = 3
BTNTYPE_INVENTORY = 4
BTNTYPE_CHAT = 10
BTNTYPE_BOOKMARKS = 11
BTNTYPE_CHATCHANNEL = 12
BTNTYPE_BOOKMARK = 13
BTNTYPE_NOTIFICATION = 14
BTNTYPE_OFFERS = 15
BTNTYPE_REDEEM = 16
BTNTYPE_REWARD = 17
BTNTYPE_SPACER = 18
BTNTYPE_EVENT = 19
BTNTYPE_CAREER_PROGRAM = 21
PANEL_SHOWABOVE = 1
PANEL_SHOWONSIDE = 2
FIXED_PARENT_BTNTYPES = (BTNTYPE_CHAT, BTNTYPE_WINDOW, BTNTYPE_INVENTORY)
COMMAND_BTNTYPES = (BTNTYPE_CMD, BTNTYPE_CAREER_PROGRAM)
BLINK_INTERVAL = 1.0
RAWDATA_NEOCOMDEFAULT = [(BTNTYPE_CAREER_PROGRAM, btnIDs.AIR_CAREER_PROGRAM_ID, None),
 (BTNTYPE_CMD, btnIDs.AGENCY_ID, None),
 (BTNTYPE_CMD, btnIDs.JOB_BOARD_ID, None),
 (BTNTYPE_CMD, btnIDs.MAIL_ID, None),
 (BTNTYPE_INVENTORY, btnIDs.INVENTORY_ID, None),
 (BTNTYPE_CMD, btnIDs.ASSETS_ID, None),
 (BTNTYPE_CMD, btnIDs.WALLET_ID, None),
 (BTNTYPE_CMD, btnIDs.MARKET_ID, None),
 (BTNTYPE_CMD, btnIDs.SHIP_TREE_ID, None),
 (BTNTYPE_CMD, btnIDs.FITTING_ID, None),
 (BTNTYPE_CMD, btnIDs.MAP_BETA_ID, None),
 (BTNTYPE_CMD, btnIDs.PROJECT_DISCOVERY_ID, None),
 (BTNTYPE_CMD, btnIDs.HELP_ID, None),
 (BTNTYPE_CHAT, btnIDs.CHAT_ID, None)]
RAWDATA_EVEMENU_GROUP_ACTIVITIES = (BTNTYPE_GROUP, btnIDs.GROUP_ACTIVITIES_ID, [(BTNTYPE_CMD, btnIDs.JOB_BOARD_ID, None),
  (BTNTYPE_CAREER_PROGRAM, btnIDs.AIR_CAREER_PROGRAM_ID, None),
  (BTNTYPE_CMD, btnIDs.AGENCY_ID, None),
  (BTNTYPE_CMD, btnIDs.MAP_BETA_ID, None),
  (BTNTYPE_CMD, btnIDs.PROJECT_DISCOVERY_ID, None),
  (BTNTYPE_CMD, btnIDs.MILITIA_ID, None),
  (BTNTYPE_CMD, btnIDs.FW_ENLISTMENT, None),
  (BTNTYPE_CMD, btnIDs.INSURGENCY_DASHBOARD, None),
  (BTNTYPE_CMD, btnIDs.BOUNTY_OFFICE_ID, None),
  (BTNTYPE_CMD, btnIDs.PVP_FILAMENTS_ID, None)])
RAWDATA_EVEMENU_GROUP_FINANCE = (BTNTYPE_GROUP, btnIDs.GROUP_FINANCE_ID, [(BTNTYPE_CMD, btnIDs.MARKET_ID, None),
  (BTNTYPE_CMD, btnIDs.MARKET_ORDERS_ID, None),
  (BTNTYPE_CMD, btnIDs.WALLET_ID, None),
  (BTNTYPE_CMD, btnIDs.CONTRACTS_ID, None),
  (BTNTYPE_CMD, btnIDs.MULTI_BUY_ID, None),
  (BTNTYPE_CMD, btnIDs.RAFFLE_WINDOW_ID, None)])
RAWDATA_EVEMENU_GROUP_INDUSTRY = (BTNTYPE_GROUP, btnIDs.GROUP_INDUSTRY_ID, [(BTNTYPE_CMD, btnIDs.INDUSTRY_ID, None),
  (BTNTYPE_CMD, btnIDs.PLANETS_ID, None),
  (BTNTYPE_CMD, btnIDs.MERCENARY_DEN, None),
  (BTNTYPE_CMD, btnIDs.LEDGER_ID, None)])
RAWDATA_EVEMENU_GROUP_INVENTORY = (BTNTYPE_GROUP, btnIDs.GROUP_INVENTORY_ID, [(BTNTYPE_INVENTORY, btnIDs.INVENTORY_ID, None), (BTNTYPE_CMD, btnIDs.ASSETS_ID, None)])
RAWDATA_EVEMENU_GROUP_PERSONAL = (BTNTYPE_GROUP, btnIDs.GROUP_PERSONAL_ID, [(BTNTYPE_CMD, btnIDs.CHARACTER_SHEET_ID, None)])
RAWDATA_EVEMENU_GROUP_SHIP = (BTNTYPE_GROUP, btnIDs.GROUP_SHIP_ID, [(BTNTYPE_CMD, btnIDs.FITTING_ID, None), (BTNTYPE_CMD, btnIDs.SHIP_TREE_ID, None), (BTNTYPE_CMD, btnIDs.FITTING_MGMT_ID, None)])
RAWDATA_EVEMENU_GROUP_SOCIAL = (BTNTYPE_GROUP, btnIDs.GROUP_SOCIAL_ID, [(BTNTYPE_CMD, btnIDs.CHAT_CHANNELS_ID, None),
  (BTNTYPE_CMD, btnIDs.FLEET_ID, None),
  (BTNTYPE_CMD, btnIDs.MAIL_ID, None),
  (BTNTYPE_CMD, btnIDs.CORP_ID, None),
  (BTNTYPE_CMD, btnIDs.CALENDAR_ID, None),
  (BTNTYPE_CMD, btnIDs.ACCESS_GROUP_ID, None)])
RAWDATA_EVEMENU_GROUP_PARAGON_SERVICES = (BTNTYPE_GROUP, btnIDs.GROUP_PARAGON_SERVICES_ID, [(BTNTYPE_CMD, btnIDs.SHIP_SKINR, None)])
RAWDATA_EVEMENU_GROUP_UTILITIES = (BTNTYPE_GROUP, btnIDs.GROUP_UTILITIES_ID, [(BTNTYPE_CMD, btnIDs.NOTEPAD_ID, None),
  (BTNTYPE_CMD, btnIDs.COMPARE_ID, None),
  (BTNTYPE_CMD, btnIDs.LOG_ID, None),
  (BTNTYPE_CMD, btnIDs.STRUCTURE_BROWSER_ID, None),
  (BTNTYPE_CMD, btnIDs.CALCULATOR_ID, None),
  (BTNTYPE_CMD, btnIDs.POINTER_WND_ID, None)])
RAWDATA_EVEMENU_BOTTOM_BUTTONS = [(BTNTYPE_CMD, btnIDs.AURUM_STORE_ID, None),
 (BTNTYPE_CMD, btnIDs.PLEX_VAULT_ID, None),
 (BTNTYPE_SPACER, 'settingSpacer', None),
 (BTNTYPE_CMD, btnIDs.HELP_ID, None),
 (BTNTYPE_CMD, btnIDs.SETTINGS_ID, None),
 (BTNTYPE_CMD, btnIDs.LOG_OFF_ID, None),
 (BTNTYPE_CMD, btnIDs.QUIT_GAME_ID, None)]
RAWDATA_SKILLS = ((BTNTYPE_CMD, btnIDs.SKILLS_ID, None),)
RAWDATA_CHARSHEET = ((BTNTYPE_CMD, btnIDs.CHARACTER_SHEET_ID, None),)
NOTPERSISTED_BTNTYPES = (BTNTYPE_WINDOW,)
NEOCOM_DEFAULT_WIDTH = 48
NEOCOM_DEFAULT_ALIGN = uiconst.TOLEFT
NEOCOM_MINSIZE = 32
NEOCOM_MAXSIZE = 72
