#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\login\charSelection\characterSelectionColors.py
from carbonui import TextColor
from carbonui.util.color import GetColor
from eve.client.script.ui import eveColor
BASECOLOR1 = (20 / 255.0, 20 / 255.0, 20 / 255.0)
BASECOLOR1_TEXT = TextColor.NORMAL
BASECOLOR1_HIGHLIGHT = (100 / 255.0, 100 / 255.0, 100 / 255.0)
BASECOLOR1_DARK = (20 / 255.0, 20 / 255.0, 20 / 255.0)
DARKBASE = (0.0, 0.0, 0.0)
BASECOLOR1_FILL = GetColor(BASECOLOR1_DARK, alpha=0.4)
BASECOLOR1_TEXT_ACTIVE = TextColor.HIGHLIGHT
BASECOLOR1_TEXT_INACTIVE = BASECOLOR1_TEXT
BASECOLOR1_FRAME_ACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.3)
BASECOLOR1_FRAME_INACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.2)
FRAME_GLOW_ACTIVE = (1.0, 1.0, 1.0, 1.0)
FRAME_GLOW_INACTIVE = (1.0, 1.0, 1.0, 0.3)
SLOT_BACKGROUND = GetColor(DARKBASE, alpha=0.8)
OUTER_FRAME = GetColor(BASECOLOR1, alpha=0.6)
INNER_FRAME_ACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.6)
INNER_FRAME_INACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.6)
PORTRAIT_INACTIVE = eveColor.WHITE
PORTRAIT_INACTIVE_SATURATION = 0.0
PORTRAIT_INACTIVE_EFFECT_OPACITY = 0.7
AT_WAR_INACTIVE = eveColor.WHITE
AT_WAR_ACTIVE = eveColor.DANGER_RED
PLUS_ACTIVE = BASECOLOR1_TEXT
PLUS_INACTIVE = BASECOLOR1_TEXT_INACTIVE
LINES_ACTIVE = BASECOLOR1_FRAME_ACTIVE
LINES_INACTIVE = BASECOLOR1_FRAME_INACTIVE
LINES_TEXT_ACTIVE = BASECOLOR1_TEXT_ACTIVE
LINES_TEXT_INACTIVE = BASECOLOR1_TEXT_INACTIVE
LINES_ICON_ACTIVE = GetColor(BASECOLOR1, alpha=0.7)
LINES_ICON_INACTIVE = GetColor(BASECOLOR1, alpha=0.5)
NAME_CONT_FILL_ACTIVE = GetColor(BASECOLOR1, alpha=0.8)
NAME_CONT_FILL_INACTIVE = GetColor(BASECOLOR1, alpha=0.8)
NAME_LABEL_ACTIVE = TextColor.NORMAL
NAME_LABEL_INACTIVE = BASECOLOR1_TEXT_INACTIVE
SKILLQUEUE_BACKGROUND_ACTIVE = BASECOLOR1_FILL
SKILLQUEUE_BACKGROUND_INACTIVE = BASECOLOR1_FILL
SKILLQUEUE_FILL_ACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.3)
SKILLQUEUE_FILL_INACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.2)
SKILLQUEUE_BRIGHT_EDGE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.7)
SKILLQUEUE_FRAME_TRAINING_ACTIVE = BASECOLOR1_FRAME_ACTIVE
SKILLQUEUE_FRAME_TRAINING_INACTIVE = BASECOLOR1_FRAME_INACTIVE
SKILLQUEUE_FRAME_NOT_TRAINING_ACTIVE = BASECOLOR1_FRAME_ACTIVE
SKILLQUEUE_FRAME_NOT_TRAINING_INACTIVE = BASECOLOR1_FRAME_INACTIVE
SKILLQUEUE_TEXT_TRAINING_ACTIVE = BASECOLOR1_TEXT_ACTIVE
SKILLQUEUE_TEXT_TRAINING_INACTIVE = BASECOLOR1_TEXT_INACTIVE
SKILLQUEUE_TEXT_NOT_TRAINING_ACTIVE = BASECOLOR1_TEXT_ACTIVE
SKILLQUEUE_TEXT_NOT_TRAINING_INACTIVE = BASECOLOR1_TEXT_INACTIVE
SKILLQUEUE_TEXT2_TRAINING_ACTIVE = BASECOLOR1_TEXT_ACTIVE
SKILLQUEUE_TEXT2_TRAINING_INACTIVE = BASECOLOR1_TEXT_INACTIVE
LOCATION_FILL_ACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.3)
LOCATION_FILL_INACTIVE = BASECOLOR1_FILL
LOCATION_FRAME_ACTIVE = BASECOLOR1_FRAME_ACTIVE
LOCATION_FRAME_INACTIVE = BASECOLOR1_FRAME_INACTIVE
LOCATION_TEXT_ACTIVE = BASECOLOR1_TEXT_ACTIVE
LOCATION_TEXT_INACTIVE = BASECOLOR1_TEXT_INACTIVE
GRID_ACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.1)
GRID_INACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.1)
GRID_SCALE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.3)
SHIP_ICON_ACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=1.0)
SHIP_ICON_INACTIVE = GetColor(BASECOLOR1_HIGHLIGHT, alpha=0.6)
SHIP_NAME_ACTIVE = GetColor(BASECOLOR1_TEXT, alpha=1.0)
SHIP_NAME_INACTIVE = GetColor(BASECOLOR1_TEXT, alpha=0.9)
VIGNETTE_ACTIVE = GetColor(BASECOLOR1_TEXT, alpha=0.2)
VIGNETTE_INACTIVE = GetColor(BASECOLOR1, alpha=0.15)
VIGNETTE_DISABLED = GetColor(BASECOLOR1, alpha=0.1)
SUBSCRIPTION_BORDER_FILL = GetColor(DARKBASE, alpha=0.25)
ADDCHARACTER_TEXT_ACTIVE = BASECOLOR1_TEXT
REDEEM_BORDER = BASECOLOR1_FRAME_ACTIVE
REDEEM_BORDER_FILL = BASECOLOR1_FILL
REDEEM_BORDER_BACKGROUND = GetColor(DARKBASE, alpha=1.0)
REDEEM_PANEL_FILL = GetColor(DARKBASE, alpha=1.0)
REDEEM_PANEL_AVAILABLE_TEXT = BASECOLOR1_TEXT_INACTIVE
BIOMASS_PORTRAIT = (0.1, 0.1, 0.1, 1)
BIOMASS_RED = eveColor.DANGER_RED
BIOMASS_WHITE = (1.0, 1.0, 1.0, 0.75)
