#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\shared\agencyNew\agencyConst.py
from collections import OrderedDict
from eve.common.lib import appConst
from agency.common.content_types import *
from agency.common.reward_types import *
from carbonui.util.color import Color
from dynamicresources.common.ess.const import ESS_AUTOPAY_STATE_LONG, ESS_AUTOPAY_STATE_MEDIUM, ESS_AUTOPAY_STATE_SHORT, ESS_RESERVE_WINDOW_STATE_BEST, ESS_RESERVE_WINDOW_STATE_EARLY, ESS_RESERVE_WINDOW_STATE_INACTIVE, ESS_RESERVE_WINDOW_STATE_LATE
from factionwarfare.const import ADJACENCY_STATE_FRONTLINE, ADJACENCY_STATE_SECONDLINE, ADJACENCY_STATE_BACKLINE
from inventorycommon.const import typeColonyReagentLava, typeColonyReagentIce
from localization import GetByLabel
from orbitalSkyhook.resourceRichness import RICHNESS_NONE, RICHNESS_MODEST, RICHNESS_AVG, RICHNESS_ABUNDANT
CONTENTTYPES = ((CONTENTTYPE_SUGGESTED, GetByLabel('UI/Agency/Suggested')),
 (CONTENTTYPE_COMBAT, GetByLabel('UI/Agency/Combat')),
 (CONTENTTYPE_MINING, GetByLabel('UI/Agency/Mining')),
 (CONTENTTYPE_SPECIFIC, GetByLabel('UI/Agency/Specify')),
 (CONTENTTYPE_AGENCY, GetByLabel('UI/Seasons/InfoPanelChallengesTitle')),
 (CONTENTTYPE_CAREERAGENTS, GetByLabel('Achievements/GroupNameText/career')),
 (CONTENTTYPE_AGENTS, GetByLabel('UI/Common/Agents')),
 (CONTENTTYPE_SITES, GetByLabel('UI/Agency/ContentTypeSites')),
 (CONTENTTYPE_ASTEROIDBELTS, GetByLabel('UI/Common/AsteroidBelts')),
 (CONTENTTYPE_SIGNATURES, GetByLabel('UI/Inflight/Scanner/SignatureSiteFilterLabel')),
 (CONTENTTYPE_EPICARCS, GetByLabel('UI/Agency/ContentTypeEpicArcAgents')),
 (CONTENTTYPE_RESOURCEWARS, GetByLabel('UI/Agency/ContentTypeResourceWars')),
 (CONTENTTYPE_INCURSIONS, GetByLabel('UI/Map/StarMap/Incursions')),
 (CONTENTTYPE_INCURSIONSITE, GetByLabel('UI/Map/StarMap/Incursions')),
 (CONTENTTYPE_FACTIONALWARFARE, GetByLabel('UI/Agents/FactionalWarfare')),
 (CONTENTTYPE_FACTIONALWARFARESYSTEM, GetByLabel('UI/Agency/FactionalWarfareSystem')),
 (CONTENTTYPE_FACTIONALWARFARESITE, GetByLabel('UI/Inflight/Scanner/FactionalWarfareSite')),
 (CONTENTTYPE_PIRATE_STRONGHOLD, GetByLabel('UI/Agency/ContentTypePirateStronghold')),
 (CONTENTTYPE_ESCALATION, GetByLabel('UI/Agency/ContentTypeEscalation')),
 (CONTENTTYPE_ICEBELTS, GetByLabel('UI/Agency/ContentGroups/ContentGroupIceBelts')),
 (CONTENTTYPE_ESS, GetByLabel('UI/Agency/ContentGroups/ContentGroupESS')),
 (CONTENTTYPE_HELP, GetByLabel('UI/Agency/ContentGroups/ContentGroupHelp')),
 (CONTENTTYPE_HERALDRYAGENTS, GetByLabel('UI/Agency/ContentGroups/ContentGroupMissionAgentsHeraldry')))
LABEL_BY_CONTENTTYPE = {contentType:label for contentType, label in CONTENTTYPES}
SITE_NAMES_BY_ARCHETYPE = {appConst.dunArchetypeFactionalWarfareComplexNovice: 'UI/Inflight/Scanner/FactionalWarfareSite',
 appConst.dunArchetypeFactionalWarfareComplexSmall: 'UI/Inflight/Scanner/FactionalWarfareSite',
 appConst.dunArchetypeFactionalWarfareComplexMedium: 'UI/Inflight/Scanner/FactionalWarfareSite',
 appConst.dunArchetypeFactionalWarfareComplexLarge: 'UI/Inflight/Scanner/FactionalWarfareSite',
 appConst.dunArchetypeFactionaWarfareBattlefieldSites: 'UI/Inflight/Scanner/FactionalWarfareBattlefield',
 appConst.dunArchetypeCombatSites: 'UI/Inflight/Scanner/CombatSite',
 appConst.dunArchetypeOreAnomaly: 'UI/Inflight/Scanner/OreSite',
 appConst.dunArchetypeDataSites: 'UI/Inflight/Scanner/DataSite',
 appConst.dunArchetypeRelicSites: 'UI/Inflight/Scanner/RelicSite',
 appConst.dunArchetypeGasClouds: 'UI/Inflight/Scanner/GasSite',
 appConst.dunArchetypeIceBelt: 'UI/Inflight/Scanner/IceSite',
 appConst.dunArchetypeIncursionSites: 'UI/Inflight/Scanner/IncursionSite',
 appConst.dunArchetypeIncursionSitesScout: 'UI/Inflight/Scanner/IncursionSite',
 appConst.dunArchetypeIncursionSitesVanguard: 'UI/Inflight/Scanner/IncursionSite',
 appConst.dunArchetypeIncursionSitesAssult: 'UI/Inflight/Scanner/IncursionSite',
 appConst.dunArchetypeIncursionSitesHeadquarter: 'UI/Inflight/Scanner/IncursionSite',
 appConst.dunArchetypeIncursionSitesBoss: 'UI/Inflight/Scanner/IncursionSite',
 appConst.dunArchetypeGhostSites: 'UI/Inflight/Scanner/GhostSite',
 appConst.dunArchetypeLandmarks: 'UI/Agency/Landmark',
 appConst.dunArchetypeResourceWars: 'UI/Inflight/Scanner/ResourceWarsSite',
 appConst.dunArchetypeEscalatingPathDungeons: 'UI/Agency/EscalationSite',
 appConst.dunArchetypeWormhole: 'UI/Inflight/Scanner/Wormhole',
 appConst.dunArchetypeEventSites: 'UI/Inflight/Scanner/EventSite',
 appConst.dunArchetypeCombatHacking: 'UI/Agency/CombatHacking',
 appConst.dunArchetypeSitesOfInterest: 'UI/Agency/SitesOfInterest',
 appConst.dunArchetypeDrifterSites: 'UI/Agency/DrifterSites',
 appConst.dunArchetypeHomefrontSites: 'UI/Inflight/Scanner/HomefrontOperationSite'}
DISTANCE_CURRSYSTEM = 1
DISTANCE_2JUMPS = 2
DISTANCE_5JUMPS = 5
DISTANCE_10JUMPS = 10
DISTANCE_ANY = 1000
DISTANCE_REGION = -1
CONSTELLATION_ANY = -1
REAGENTS_ALL = 0
REAGENTS_MAGMATIC_GAS = typeColonyReagentLava
REAGENTS_SUPERIONIC_ICE = typeColonyReagentIce
REAGENTS_RICHNESS_ALL = RICHNESS_NONE
REAGENTS_RICHNESS_MODEST = RICHNESS_MODEST
REAGENTS_RICHNESS_AVERAGE = RICHNESS_AVG
REAGENTS_RICHNESS_ABUNDANT = RICHNESS_ABUNDANT
SOVEREIGNTY_ALL = 0
SOVEREIGNTY_CLAIMED = 1
SOVEREIGNTY_UNCLAIMED = 2
SKYHOOKS_THEFT_ANY_STATE = 0
SKYHOOKS_THEFT_VULNERABLE = 1
OPTION_PER_SYSTEM_VALUE = 0
OPTION_PER_PLANET_VALUE = 1
OPTION_PER_SYSTEM = GetByLabel('UI/Agency/ColonyResourcesAgency/PerSystemFilter')
OPTION_PER_SYSTEM_HINT = GetByLabel('UI/Agency/ColonyResourcesAgency/PerSystemHint')
OPTION_PER_PLANET = GetByLabel('UI/Agency/ColonyResourcesAgency/PerPlanetFilter')
OPTION_PER_PLANET_HINT = GetByLabel('UI/Agency/ColonyResourcesAgency/PerPlanetHint')
PER_SYSTEM_PLANET_OPTIONS = (OPTION_PER_SYSTEM_VALUE, OPTION_PER_PLANET_VALUE)
AGENT_STANDARDDIVISIONIDS = (appConst.corpDivisionSecurity,
 appConst.corpDivisionMining,
 appConst.corpDivisionDistribution,
 appConst.npcDivisionRD,
 appConst.corpDivisionHeraldry)
AGENTDIVISION_LOCATOR = -2
AGENTLEVEL_HIGHESTAVAILABLE = -2
FILTERVALUE_ANY = -1
DEFAULT_AGENT_CHECKBOXES = False
FACWAR_ANY = -1
FILTERTYPE_DISTANCE = 3
FILTERTYPE_REGION = 4
FILTERTYPE_CONSTELLATION = 5
FILTERTYPE_SECURITYSTATUS = 6
FILTERTYPE_AGENTFACTION = 20
FILTERTYPE_AGENTCORP = 21
FILTERTYPE_AGENTDIVISION = 22
FILTERTYPE_AGENTLEVEL = 23
FILTERTYPE_AGENTIGNORESTANDINGSREQUIREMENT = 24
FILTERTYPE_AGENTISLOCATOR = 25
FILTERTYPE_FACWARCONTENT = 26
FILTERTYPE_FWSYSTEMS = 27
FILTERTYPE_FWSITES = 28
FILTERTYPE_ORETYPE = 29
FILTERTYPE_SYSTEMFACTION = 31
FILTERTYPE_PLANETTYPES = 32
FILTERTYPE_ESSMINBOUNTY = 33
FILTERTYPE_ESSMAXBOUNTY = 34
FILTERTYPE_ESSBOUNTYFILTERENABLED = 35
FILTERTYPE_ESSMINMAINBANKAMOUNT = 36
FILTERTYPE_ESSMINMAINBANKAMOUNTFILTERENABLED = 37
FILTERTYPE_ESSRESERVEBANKUNLOCKED = 38
FILTERTYPE_ESSMINRESERVEBANKAMOUNT = 39
FILTERTYPE_ESSMINRESERVEBANKAMOUNTFILTERENABLED = 40
FILTERTYPE_FWADJACENCY = 41
FILTERTYPE_CORRUPTION = 42
FILTERTYPE_SUPPRESSION = 43
FILTERTYPE_SOVEREIGNTY = 44
FILTERTYPE_POWEROUTPUT = 45
FILTERTYPE_WORKFORCEOUTPUT = 46
FILTERTYPE_REAGENTS_TYPE = 47
FILTERTYPE_REAGENTS_RICHNESS = 48
FILTERTYPE_ORBITAL_STRUCTURES = 49
FILTERTYPE_PER_SYSTEM_PLANET = 50
FILTERTYPE_REAGENTS_MAGMATIC_GAS_RICHNESS = 51
FILTERTYPE_REAGENTS_SUPERIONIC_ICE_RICHNESS = 52
FILTERTYPE_SKYHOOK_THEFT_VULNERABILITY = 53
SECURITYSTATUS_HIGHSEC = 1
SECURITYSTATUS_LOWSEC = 2
SECURITYSTATUS_NULLSEC = 3
DEFAULT_ESSBANKAMOUNT = 10000000
DEFAULT_ESSMINBOUNTY = 80
DEFAULT_ESSMAXBOUNTY = 100
DEFAULT_ESSFILTERCHECKBOX = False
DEFAULT_REAGENT_TYPE = REAGENTS_ALL
DEFAULT_REAGENT_RICHNESS = RICHNESS_NONE
DEFAULT_REAGENT_MAGMATIC_GAS_RICHNESS = RICHNESS_NONE
DEFAULT_REAGENT_SUPERIONIC_ICE_RICHNESS = RICHNESS_NONE
DEFAULT_SOVEREIGNTY = SOVEREIGNTY_ALL
DEFAULT_POWEROUTPUT = 0
DEFAULT_WORKFORCEOUTPUT = 0
DEFAULT_ORBITALSTRUCTURESCHECKBOX = False
DEFAULT_PER_SYSTEM_PLANET = OPTION_PER_SYSTEM_VALUE
DEFAULT_PLANET_TYPES_FILTER = {appConst.typePlanetSandstorm: True,
 appConst.typePlanetThunderstorm: True,
 appConst.typePlanetEarthlike: True,
 appConst.typePlanetIce: True,
 appConst.typePlanetGas: True,
 appConst.typePlanetPlasma: True,
 appConst.typePlanetOcean: True,
 appConst.typePlanetLava: True}
FILTER_DEFAULTS = {FILTERTYPE_DISTANCE: DISTANCE_ANY,
 FILTERTYPE_AGENTDIVISION: FILTERVALUE_ANY,
 FILTERTYPE_AGENTLEVEL: FILTERVALUE_ANY,
 FILTERTYPE_AGENTFACTION: FILTERVALUE_ANY,
 FILTERTYPE_FACWARCONTENT: FILTERVALUE_ANY,
 FILTERTYPE_FWADJACENCY: FILTERVALUE_ANY,
 FILTERTYPE_ORETYPE: FILTERVALUE_ANY,
 FILTERTYPE_CONSTELLATION: FILTERVALUE_ANY,
 FILTERTYPE_SYSTEMFACTION: FILTERVALUE_ANY,
 FILTERTYPE_PLANETTYPES: DEFAULT_PLANET_TYPES_FILTER,
 FILTERTYPE_SECURITYSTATUS: FILTERVALUE_ANY,
 FILTERTYPE_ESSMINMAINBANKAMOUNT: DEFAULT_ESSBANKAMOUNT,
 FILTERTYPE_ESSMINRESERVEBANKAMOUNT: DEFAULT_ESSBANKAMOUNT,
 FILTERTYPE_ESSMAXBOUNTY: DEFAULT_ESSMAXBOUNTY,
 FILTERTYPE_ESSMINBOUNTY: DEFAULT_ESSMINBOUNTY,
 FILTERTYPE_ESSRESERVEBANKUNLOCKED: DEFAULT_ESSFILTERCHECKBOX,
 FILTERTYPE_ESSBOUNTYFILTERENABLED: DEFAULT_ESSFILTERCHECKBOX,
 FILTERTYPE_ESSMINRESERVEBANKAMOUNTFILTERENABLED: DEFAULT_ESSFILTERCHECKBOX,
 FILTERTYPE_ESSMINMAINBANKAMOUNTFILTERENABLED: DEFAULT_ESSFILTERCHECKBOX,
 FILTERTYPE_AGENTISLOCATOR: DEFAULT_AGENT_CHECKBOXES,
 FILTERTYPE_AGENTIGNORESTANDINGSREQUIREMENT: DEFAULT_AGENT_CHECKBOXES,
 FILTERTYPE_CORRUPTION: FILTERVALUE_ANY,
 FILTERTYPE_SUPPRESSION: FILTERVALUE_ANY,
 FILTERTYPE_SOVEREIGNTY: DEFAULT_SOVEREIGNTY,
 FILTERTYPE_POWEROUTPUT: DEFAULT_POWEROUTPUT,
 FILTERTYPE_WORKFORCEOUTPUT: DEFAULT_WORKFORCEOUTPUT,
 FILTERTYPE_REAGENTS_TYPE: DEFAULT_REAGENT_TYPE,
 FILTERTYPE_REAGENTS_RICHNESS: DEFAULT_REAGENT_RICHNESS,
 FILTERTYPE_ORBITAL_STRUCTURES: DEFAULT_ORBITALSTRUCTURESCHECKBOX,
 FILTERTYPE_PER_SYSTEM_PLANET: DEFAULT_PER_SYSTEM_PLANET,
 FILTERTYPE_REAGENTS_MAGMATIC_GAS_RICHNESS: DEFAULT_REAGENT_MAGMATIC_GAS_RICHNESS,
 FILTERTYPE_REAGENTS_SUPERIONIC_ICE_RICHNESS: DEFAULT_REAGENT_SUPERIONIC_ICE_RICHNESS}
SPECIFY_FILTER_BLACKLIST = (CONTENTTYPE_AGENCY,
 CONTENTTYPE_INCURSIONSITE,
 CONTENTTYPE_FACTIONALWARFARESITE,
 CONTENTTYPE_FACTIONALWARFARESYSTEM)
MISSION_AGENT_CONTENT_TYPES = [CONTENTTYPE_SECURITYAGENTS,
 CONTENTTYPE_DISTRIBUTIONAGENTS,
 CONTENTTYPE_MININGAGENTS,
 CONTENTTYPE_RESEARCHAGENTS,
 CONTENTTYPE_LOCATORAGENTS]
HINT_BY_REWARDTYPE = {REWARDTYPE_ISK1: 'UI/Agency/RewardHintISK',
 REWARDTYPE_ISK2: 'UI/Agency/RewardHintISK',
 REWARDTYPE_ISK3: 'UI/Agency/RewardHintISK',
 REWARDTYPE_LP1: 'UI/Agency/RewardHintLP',
 REWARDTYPE_LP2: 'UI/Agency/RewardHintLP',
 REWARDTYPE_LP3: 'UI/Agency/RewardHintLP',
 REWARDTYPE_LOOT: 'UI/Agency/RewardHintLoot',
 REWARDTYPE_ASTEROID: 'UI/Agency/RewardHintAsteroid',
 REWARDTYPE_GAS: 'UI/Agency/RewardHintGas',
 REWARDTYPE_ICE: 'UI/Agency/RewardHintIce',
 REWARDTYPE_SKILLPOINTS: None,
 REWARDTYPE_SKILLPOINTSCLAIMED: None}
MAX_CONTENT_PIECES_MAX = 30
SECURITY_THRESHOLDS = (0.9, 0.7, 0.4, 0.2, 0.0)
DAYS_UNTIL_AGENCY_IS_AUTO_OPENED = 7
ESS_LOW_PAYOUT_COLOR = Color.HextoRGBA('#f81622')
ESS_MEDIUM_PAYOUT_COLOR = Color.HextoRGBA('#ff8a00')
ESS_HIGH_PAYOUT_COLOR = Color.HextoRGBA('#5ce03f')
ESS_EQUILIBRIUM_PAYOUT_COLOR = Color.WHITE
ESS_TIME_TO_COLOR_MAP = {ESS_AUTOPAY_STATE_SHORT: ESS_LOW_PAYOUT_COLOR,
 ESS_AUTOPAY_STATE_MEDIUM: ESS_MEDIUM_PAYOUT_COLOR,
 ESS_AUTOPAY_STATE_LONG: ESS_HIGH_PAYOUT_COLOR}
ESS_TIME_TO_LABEL_MAP = {ESS_AUTOPAY_STATE_SHORT: 'UI/Agency/ESS/Short',
 ESS_AUTOPAY_STATE_MEDIUM: 'UI/Agency/ESS/Medium',
 ESS_AUTOPAY_STATE_LONG: 'UI/Agency/ESS/Long'}
ESS_PAYOUT_STATE_TO_LABEL_MAP = {ESS_RESERVE_WINDOW_STATE_EARLY: 'UI/Agency/ESS/Increasing',
 ESS_RESERVE_WINDOW_STATE_BEST: 'UI/Agency/ESS/Peak',
 ESS_RESERVE_WINDOW_STATE_LATE: 'UI/Agency/ESS/Decreasing',
 ESS_RESERVE_WINDOW_STATE_INACTIVE: 'UI/Agency/ESS/Inactive'}
ESS_PAYOUT_STATE_TO_COLOR_MAP = {ESS_RESERVE_WINDOW_STATE_EARLY: ESS_LOW_PAYOUT_COLOR,
 ESS_RESERVE_WINDOW_STATE_BEST: ESS_HIGH_PAYOUT_COLOR,
 ESS_RESERVE_WINDOW_STATE_LATE: ESS_MEDIUM_PAYOUT_COLOR,
 ESS_RESERVE_WINDOW_STATE_INACTIVE: Color.GRAY4}
ADJACENCY_FILTERS = OrderedDict()
ADJACENCY_FILTERS[ADJACENCY_STATE_FRONTLINE] = 1
ADJACENCY_FILTERS[ADJACENCY_STATE_SECONDLINE] = 2
ADJACENCY_FILTERS[ADJACENCY_STATE_BACKLINE] = 3
ADJACENCY_BY_FILTER_VALUE = {v:k for k, v in ADJACENCY_FILTERS.iteritems()}
COLONY_RESOURCE_AGENCY_PIECES_MAX = 120
