#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\structures\const.py
from eveuniverse.security import securityClassZeroSec, securityClassLowSec, securityClassHighSec
import inventorycommon.const as invConst
STATE_UNKNOWN = 0
STATE_UNANCHORED = 1
STATE_ANCHORING = 2
STATE_ONLINE_DEPRECATED = 100
STATE_FITTING_INVULNERABLE = 101
STATE_ONLINING_VULNERABLE = 102
STATE_SHIELD_VULNERABLE = 110
STATE_ARMOR_REINFORCE = 111
STATE_ARMOR_VULNERABLE = 112
STATE_HULL_REINFORCE = 113
STATE_HULL_VULNERABLE = 114
STATE_ANCHOR_VULNERABLE = 115
STATE_DEPLOY_VULNERABLE = 116
STATE_FOB_INVULNERABLE = 118
STATES = {STATE_UNKNOWN: 'unknown',
 STATE_UNANCHORED: 'unanchored',
 STATE_ANCHORING: 'anchoring',
 STATE_ONLINE_DEPRECATED: 'online_deprecated',
 STATE_FITTING_INVULNERABLE: 'fitting_invulnerable',
 STATE_ONLINING_VULNERABLE: 'onlining_vulnerable',
 STATE_SHIELD_VULNERABLE: 'shield_vulnerable',
 STATE_ARMOR_REINFORCE: 'armor_reinforce',
 STATE_ARMOR_VULNERABLE: 'armor_vulnerable',
 STATE_HULL_REINFORCE: 'hull_reinforce',
 STATE_HULL_VULNERABLE: 'hull_vulnerable',
 STATE_ANCHOR_VULNERABLE: 'anchor_vulnerable',
 STATE_DEPLOY_VULNERABLE: 'deploy_vulnerable',
 STATE_FOB_INVULNERABLE: 'fob_invulnerable'}
OFFLINE_STATES = {STATE_UNKNOWN,
 STATE_UNANCHORED,
 STATE_ANCHORING,
 STATE_ANCHOR_VULNERABLE,
 STATE_DEPLOY_VULNERABLE}
DISABLED_STATES = {STATE_UNKNOWN,
 STATE_UNANCHORED,
 STATE_ANCHORING,
 STATE_HULL_REINFORCE,
 STATE_HULL_VULNERABLE,
 STATE_ANCHOR_VULNERABLE,
 STATE_ONLINING_VULNERABLE,
 STATE_DEPLOY_VULNERABLE}
OPERATIONAL_STATES = set(STATES.keys()) - OFFLINE_STATES - DISABLED_STATES
TETHER_ENABLED_STATES = {STATE_ONLINING_VULNERABLE,
 STATE_SHIELD_VULNERABLE,
 STATE_ARMOR_REINFORCE,
 STATE_ARMOR_VULNERABLE,
 STATE_HULL_REINFORCE,
 STATE_HULL_VULNERABLE,
 STATE_FOB_INVULNERABLE}
CAN_ACTIVATE_EQUIPMENT_IN_STATE = {STATE_SHIELD_VULNERABLE,
 STATE_ARMOR_REINFORCE,
 STATE_ARMOR_VULNERABLE,
 STATE_HULL_REINFORCE,
 STATE_HULL_VULNERABLE,
 STATE_FOB_INVULNERABLE}
STATE_LABELS = {STATE_UNANCHORED: 'UI/Structures/States/Unanchored',
 STATE_ANCHORING: 'UI/Structures/States/Anchoring',
 STATE_ONLINE_DEPRECATED: 'UI/Structures/States/Online',
 STATE_FITTING_INVULNERABLE: 'UI/Structures/States/Fitting',
 STATE_ONLINING_VULNERABLE: 'UI/Structures/States/Onlining',
 STATE_SHIELD_VULNERABLE: 'UI/Structures/States/Vulnerable',
 STATE_ARMOR_REINFORCE: 'UI/Structures/States/Reinforced',
 STATE_ARMOR_VULNERABLE: 'UI/Structures/States/Vulnerable',
 STATE_HULL_REINFORCE: 'UI/Structures/States/Reinforced',
 STATE_HULL_VULNERABLE: 'UI/Structures/States/Vulnerable',
 STATE_ANCHOR_VULNERABLE: 'UI/Structures/States/Vulnerable',
 STATE_DEPLOY_VULNERABLE: 'UI/Structures/States/Deploying',
 STATE_FOB_INVULNERABLE: 'UI/Structures/States/Invulnerable'}
STATE_SHIELD_ARMOR_HULL = {STATE_UNANCHORED: (1, 1, 1),
 STATE_ANCHORING: (0, 0, 1),
 STATE_ONLINE_DEPRECATED: (1, 1, 1),
 STATE_FITTING_INVULNERABLE: (0, 0, 1),
 STATE_ONLINING_VULNERABLE: (0, 0, 1),
 STATE_SHIELD_VULNERABLE: (1, 1, 1),
 STATE_ARMOR_REINFORCE: (0, 1, 1),
 STATE_ARMOR_VULNERABLE: (0, 1, 1),
 STATE_HULL_REINFORCE: (0, 0, 1),
 STATE_HULL_VULNERABLE: (0, 0, 1),
 STATE_ANCHOR_VULNERABLE: (0, 0, 1),
 STATE_DEPLOY_VULNERABLE: (0, 0, 1),
 STATE_FOB_INVULNERABLE: (1, 1, 1)}
STATE_VULNERABILITY = {STATE_UNANCHORED: False,
 STATE_ANCHORING: False,
 STATE_ONLINE_DEPRECATED: False,
 STATE_FITTING_INVULNERABLE: False,
 STATE_ONLINING_VULNERABLE: True,
 STATE_SHIELD_VULNERABLE: True,
 STATE_ARMOR_REINFORCE: False,
 STATE_ARMOR_VULNERABLE: True,
 STATE_HULL_REINFORCE: False,
 STATE_HULL_VULNERABLE: True,
 STATE_ANCHOR_VULNERABLE: True,
 STATE_DEPLOY_VULNERABLE: True,
 STATE_FOB_INVULNERABLE: False}
STATE_CANCELS_UNANCHOR = {STATE_UNKNOWN: True,
 STATE_UNANCHORED: True,
 STATE_ANCHORING: True,
 STATE_ONLINE_DEPRECATED: False,
 STATE_FITTING_INVULNERABLE: True,
 STATE_ONLINING_VULNERABLE: False,
 STATE_SHIELD_VULNERABLE: False,
 STATE_ARMOR_REINFORCE: True,
 STATE_ARMOR_VULNERABLE: True,
 STATE_HULL_REINFORCE: True,
 STATE_HULL_VULNERABLE: True,
 STATE_ANCHOR_VULNERABLE: True,
 STATE_DEPLOY_VULNERABLE: True}
YELLOW_TIMER_COLOR = (249 / 255.0,
 179 / 255.0,
 56 / 255.0,
 1.0)
BLUE_TIMER_COLOR = (0.0, 1.0, 1.0, 1.0)
STATE_COLOR = {STATE_UNKNOWN: BLUE_TIMER_COLOR,
 STATE_UNANCHORED: BLUE_TIMER_COLOR,
 STATE_ANCHORING: BLUE_TIMER_COLOR,
 STATE_ONLINE_DEPRECATED: BLUE_TIMER_COLOR,
 STATE_FITTING_INVULNERABLE: BLUE_TIMER_COLOR,
 STATE_ONLINING_VULNERABLE: YELLOW_TIMER_COLOR,
 STATE_SHIELD_VULNERABLE: YELLOW_TIMER_COLOR,
 STATE_ARMOR_REINFORCE: BLUE_TIMER_COLOR,
 STATE_ARMOR_VULNERABLE: YELLOW_TIMER_COLOR,
 STATE_HULL_REINFORCE: BLUE_TIMER_COLOR,
 STATE_HULL_VULNERABLE: YELLOW_TIMER_COLOR,
 STATE_ANCHOR_VULNERABLE: YELLOW_TIMER_COLOR,
 STATE_DEPLOY_VULNERABLE: YELLOW_TIMER_COLOR,
 STATE_FOB_INVULNERABLE: BLUE_TIMER_COLOR}
DAY_MONDAY = 0
DAY_TUESDAY = 1
DAY_WEDNESDAY = 2
DAY_THURSDAY = 3
DAY_FRIDAY = 4
DAY_SATURDAY = 5
DAY_SUNDAY = 6
DAYS = (DAY_MONDAY,
 DAY_TUESDAY,
 DAY_WEDNESDAY,
 DAY_THURSDAY,
 DAY_FRIDAY,
 DAY_SATURDAY,
 DAY_SUNDAY)
REINFORCE_DURATION_ARMOR_DEFAULT = 86400
REINFORCE_DURATION_ARMOR_MEDIUM_WORMHOLE = int(216000.0)
REINFORCE_DURATION_ARMOR_MEDIUM_TRIGLAVIAN = int(216000.0)
REINFORCE_DURATION_ARMOR_MEDIUM_BY_SECURITY = {securityClassZeroSec: int(302400.0),
 securityClassLowSec: int(302400.0),
 securityClassHighSec: int(388800.0)}
REINFORCE_DURATION_ARMOR_WAR_HQ = 86400
REINFORCE_DURATION_ARMOR_INSURGENCY_FOB = 86400
REINFORCE_DURATION_HULL_DEFAULT = int(129600.0)
REINFORCE_DURATION_HULL_WORMHOLE = int(129600.0)
REINFORCE_DURATION_HULL_TRIGLAVIAN = int(129600.0)
REINFORCE_DURATION_HULL_BY_SECURITY = {securityClassZeroSec: int(216000.0),
 securityClassLowSec: int(216000.0),
 securityClassHighSec: int(388800.0)}
REINFORCE_DURATION_HULL_WAR_HQ = 86400
FLEX_REINFORCE_DURATION_HULL = 3600
REINFORCE_EXIT_JITTER_DEFAULT_SECONDS = 10800
REINFORCE_EXIT_JITTER_MEDIUM_SECONDS = int(5400.0)
REINFORCE_EXIT_JITTER_FLEX_SECONDS = 1800
DEFAULT_REPAIR_TIMER = 900
STATE_REPAIR_TIME = {STATE_ANCHOR_VULNERABLE: 900,
 STATE_ONLINING_VULNERABLE: 900,
 STATE_SHIELD_VULNERABLE: 900,
 STATE_ARMOR_VULNERABLE: 900,
 STATE_HULL_VULNERABLE: 1800,
 STATE_DEPLOY_VULNERABLE: 900}
ANCHORING_TIME = 86400
FLEX_DEPLOYING_TIME = 2700
UNANCHORING_TIME = 604800
INSURGENCY_FOB_UNANCHORING_TIME = 60
FLEX_UNANCHORING_TIME = 2700
FITTING_INVULNERABLE_TIME = 300
MIN_STRUCTURE_NAME_LEN = 3
DEFAULT_REINFORCE_HOUR = 18
DEFAULT_REINFORCE_WEEKDAY = DAY_SATURDAY
NO_REINFORCEMENT_WEEKDAY = 255
DOCKING_ACCESS_UNKNOWN = -1
MAX_JUMPBRIDGE_RANGE_LIGHTYEARS = 5
ABANDONING_TIME_MIN = 604800
ABANDONING_TIME_MAX = 691200
ABANDONDED_ADVANCE_WARNING_TIME = 259200
UPKEEP_STATE_FULL_POWER = 1
UPKEEP_STATE_LOW_POWER = 2
UPKEEP_STATE_ABANDONED = 3
ALL_UPKEEP_STATES = (UPKEEP_STATE_FULL_POWER, UPKEEP_STATE_LOW_POWER, UPKEEP_STATE_ABANDONED)
TYPES_THAT_NEVER_GO_ABANDONED = (invConst.typeCitadelMoreauFortizar,
 invConst.typeCitadelDraccousFortizar,
 invConst.typeCitadelHorizonFortizar,
 invConst.typeCitadelMarginisFortizar,
 invConst.typeCitadelPrometheusFortizar)
STRUCTURE_SIZE_FLEX = 'STRUCTURE_SIZE_FLEX'
STRUCTURE_SIZE_MEDIUM = 'STRUCTURE_SIZE_MEDIUM'
STRUCTURE_SIZE_LARGE = 'STRUCTURE_SIZE_LARGE'
STRUCTURE_SIZE_EXTRA_LARGE = 'STRUCTURE_SIZE_EXTRA_LARGE'
STRUCTURE_SIZE_UNDEFINED = 'STRUCTURE_SIZE_UNDEFINED'
STRUCTURE_SIZE_BY_TYPE = {invConst.typeUpwellSmallStargate: STRUCTURE_SIZE_FLEX,
 invConst.typeUpwellCynosuralBeacon: STRUCTURE_SIZE_FLEX,
 invConst.typeUpwellCynosuralSystemJammer: STRUCTURE_SIZE_FLEX,
 invConst.typeUpwellAutoMoonMiner: STRUCTURE_SIZE_FLEX,
 invConst.typeCitadelAstrahus: STRUCTURE_SIZE_MEDIUM,
 invConst.typeEngineeringComplexRaitaru: STRUCTURE_SIZE_MEDIUM,
 invConst.typeRefineryAthanor: STRUCTURE_SIZE_MEDIUM,
 invConst.typeCitadelFortizar: STRUCTURE_SIZE_LARGE,
 invConst.typeCitadelMoreauFortizar: STRUCTURE_SIZE_LARGE,
 invConst.typeCitadelDraccousFortizar: STRUCTURE_SIZE_LARGE,
 invConst.typeCitadelHorizonFortizar: STRUCTURE_SIZE_LARGE,
 invConst.typeCitadelMarginisFortizar: STRUCTURE_SIZE_LARGE,
 invConst.typeCitadelPrometheusFortizar: STRUCTURE_SIZE_LARGE,
 invConst.typeEngineeringComplexAzbel: STRUCTURE_SIZE_LARGE,
 invConst.typeRefineryTatara: STRUCTURE_SIZE_LARGE,
 invConst.typeCitadelKeepstar: STRUCTURE_SIZE_EXTRA_LARGE,
 invConst.typeCitadelPalatineKeepstar: STRUCTURE_SIZE_EXTRA_LARGE,
 invConst.typeEngineeringComplexSotiyo: STRUCTURE_SIZE_EXTRA_LARGE}
FLEX_STRUCTURE_TYPES = {typeID for typeID, size in STRUCTURE_SIZE_BY_TYPE.iteritems() if size == STRUCTURE_SIZE_FLEX}
STATES_THAT_REQUIRE_AUTO_REPAIR_TO_REPAIR = (STATE_SHIELD_VULNERABLE, STATE_ARMOR_VULNERABLE, STATE_HULL_VULNERABLE)
