#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\evedungeons\common\triggers.py
dunTriggerAttacked = 1
dunTriggerShipEnteredProximity = 2
dunTriggerExploding = 3
dunTriggerShieldConditionLevel = 4
dunTriggerArmorConditionLevel = 5
dunTriggerStructureConditionLevel = 6
dunTriggerMined = 7
dunTriggerRoomEntered = 8
dunTriggerRoomMinedOut = 9
dunTriggerRoomMined = 10
dunTriggerHackingSuccess = 11
dunTriggerHackingFailure = 12
dunTriggerSalvagingSuccess = 13
dunTriggerSalvagingFailure = 14
dunTriggerArchaeologySuccess = 15
dunTriggerArchaeologyFailure = 16
dunTriggerShipsEnteredRoom = 17
dunTriggerRoomCapturedCorp = 18
dunTriggerRoomCapturedAlliance = 19
dunTriggerRoomCapturedFacWar = 20
dunTriggerFWShipEnteredProximity = 21
dunTriggerItemPlacedInMissionContainer = 23
dunTriggerPlayerKilled = 26
dunTriggerEffectActivated = 27
dunTriggerShipsLeftRoom = 28
dunTriggerShipLeftProximity = 29
dunTriggerFWShipLeftProximity = 30
dunTriggerRoomWipedOut = 31
dunTriggerItemRemovedFromSpawnContainer = 32
dunTriggerItemInCargo = 33
dunTriggerCounterEQ = 34
dunTriggerCounterGT = 35
dunTriggerCounterGE = 36
dunTriggerCounterLT = 37
dunTriggerCounterLE = 38
dunTriggerTimerComplete = 41
dunTriggerHaulerCargoFull = 44
dunTriggerReactiveSpawnerTotalPointsDestroyed = 46
dunTriggerWormholeCollapseImpending = 47
dunTriggerAsteroidDepleted = 48
dunTriggerBlackboardValueEqualsString = 50
dunTriggerBlackboardValueEqualsInteger = 51
dunTriggerShipBoarded = 52
dunTriggerHackingInitialize = 55
dunTriggerOccupierReachedThreshold = 56
dunTriggerAttackerReachedThreshold = 57
dunTriggerScoreboardEqualTo = 58
dunTriggerRoomCapturedInsurgency = 59
dunTriggerTowGameFactionReachedWinThreshold = 60
dunTriggerEventActivateGate = 1
dunTriggerEventSpawnGuards = 2
dunTriggerEventSpawnGuardObject = 3
dunTriggerEventRangedNPCHealing = 4
dunTriggerEventRangedPlayerDamageEM = 5
dunTriggerEventRangedPlayerDamageExplosive = 6
dunTriggerEventRangedPlayerDamageKinetic = 7
dunTriggerEventRangedPlayerDamageThermal = 8
dunTriggerEventMissionCompletion = 9
dunTriggerEventMessage = 10
dunTriggerEventDungeonCompletion = 11
dunTriggerEventEffectBeaconActivate = 13
dunTriggerEventEffectBeaconDeactivate = 14
dunTriggerEventObjectDespawn = 15
dunTriggerEventObjectExplode = 16
dunTriggerEventEntityDespawn = 18
dunTriggerEventEntityExplode = 19
dunTriggerEventGrantFacWarVictoryPoints = 20
dunTriggerEventAgentTalkTo = 22
dunTriggerEventAgentMessage = 23
dunTriggerEventDropLoot = 24
dunTriggerEventRangedPlayerHealing = 25
dunTriggerEventRangedNPCDamageEM = 26
dunTriggerEventRangedNPCDamageExplosive = 27
dunTriggerEventRangedNPCDamageKinetic = 28
dunTriggerEventRangedNPCDamageThermal = 29
dunTriggerEventSpawnItemInCargo = 30
dunTriggerEventMissionFailure = 31
dunTriggerEventCounterAdd = 32
dunTriggerEventCounterSubtract = 33
dunTriggerEventCounterMultiply = 34
dunTriggerEventCounterDivide = 35
dunTriggerEventCounterSet = 36
dunTriggerEventGrantGroupReward = 37
dunTriggerEventGrantDelayedGroupReward = 38
dunTriggerEventAdjustSystemInfluence = 39
dunTriggerEventWarpShipAwayDespawn = 40
dunTriggerEventWarpShipAwayAndComeBack = 41
dunTriggerEventSupressAllRespawn = 42
dunTriggerEventGrantGroupRewardLimitedRestrictions = 45
dunTriggerEventSpawnShip = 47
dunTriggerEventGrantFacWarLoyaltyPoints = 48
dunTriggerEventTimerStart = 49
dunTriggerEventTimerCancel = 52
dunTriggerEventStartTale = 54
dunTriggerEventSpawnEntityByTypeID = 55
dunTriggerEventRangedPlayerDamageExplosivePodIncluded = 56
dunTriggerEventWarpInGuards = 57
dunTriggerEventSetSpawnGuardMinimumDelay = 58
dunTriggerEventEmpireOreRemoval = 59
dunTriggerEventSpawnNpcsDynamicallyUsingBlackboard = 61
dunTriggerEventOpenAbyssGateTriggerEvent = 63
dunTriggerEventRemoveCargoFromShipTriggerEvent = 65
dunTriggerEventSetPose = 67
dunTriggerEventGrantInsurgencyLoyaltyPoints = 68
dunTriggerEventGrantInsurgencyStandingsChange = 69
dunTriggerEventSetDungeonBlackboardIntegerValue = 2068
dunTriggerEventSetDungeonBlackboardStringValue = 2069
dunTriggerEventCameraInterest = 2130
dunTriggerEventApplyFitting = 2132
dunTriggerEventPlayMusic = 2133
dunTriggerEventDeactivateGate = 2135
dunTriggerEventStartConversation = 2134
dunTriggerEventIgnoreTriggers = 2138
dunTriggerEventOpenVoidSpaceExit = 2143
dunTriggerEventPlayAmbientSound = 2144
dunTriggerEventSerenityReservedMin = 2201
dunTriggerEventSerenityReservedMax = 2300
dunTriggerEventSendDungeonMessageToClients = 2346
dunTriggerEventSendMessageToNodeGraph = 2347
dunTriggerEventBlackboardCharacterList = 2348
dunTriggerEventBlackboardList = 2349
dunTriggerEventAddContributionValue = 2351
dunTriggerEventBlackboardRandomInteger = 2354
ALL_TRIGGERS = {val:name for name, val in locals().iteritems() if name.startswith('dunTrigger') and not name.startswith('dunTriggerEvent')}
ALL_TRIGGER_EVENTS = {val:name for name, val in locals().iteritems() if name.startswith('dunTriggerEvent')}
DUNGEON_EVENT_TYPE_AFFECTS_ENTITY = [dunTriggerEventEntityExplode,
 dunTriggerEventEntityDespawn,
 dunTriggerEventSpawnGuards,
 dunTriggerEventWarpShipAwayDespawn,
 dunTriggerEventWarpShipAwayAndComeBack,
 dunTriggerEventWarpInGuards]
DUNGEON_EVENT_TYPE_AFFECTS_OBJECT = [dunTriggerEventSpawnGuardObject,
 dunTriggerEventEffectBeaconActivate,
 dunTriggerEventEffectBeaconDeactivate,
 dunTriggerEventObjectExplode,
 dunTriggerEventObjectDespawn,
 dunTriggerEventActivateGate]
