#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\evegraphics\validation\validators\limits.py
MIN_TURRET_LOCATOR_COUNT = 'min_turret_locator_count'
MAX_DECAL_COUNT = 'decal_count'
KILLMARK_DECAL = 'has_killmark_decal'
TRIANGLE_BUDGET = 'max_mesh_triangles'
DAMAGE_LOCATORS_MIN = 'min_damage_locators'
MIN_CORP_BANNERS = 'min_corp_banners'
MIN_ALLIANCE_BANNERS = 'min_alliance_banners'
MAX_CORP_BANNERS = 'max_corp_banners'
MAX_ALLIANCE_BANNERS = 'max_alliance_banners'
LIMIT_KEYS = [MIN_TURRET_LOCATOR_COUNT,
 MAX_DECAL_COUNT,
 KILLMARK_DECAL,
 TRIANGLE_BUDGET,
 DAMAGE_LOCATORS_MIN,
 MIN_CORP_BANNERS,
 MIN_ALLIANCE_BANNERS,
 MAX_CORP_BANNERS,
 MAX_ALLIANCE_BANNERS]
consts = {'frigate': {MIN_TURRET_LOCATOR_COUNT: 4,
             TRIANGLE_BUDGET: 35000,
             KILLMARK_DECAL: 1,
             MAX_DECAL_COUNT: 18,
             DAMAGE_LOCATORS_MIN: 10,
             MIN_CORP_BANNERS: 0,
             MIN_ALLIANCE_BANNERS: 0,
             MAX_CORP_BANNERS: 2,
             MAX_ALLIANCE_BANNERS: 2},
 'destroyer': {MIN_TURRET_LOCATOR_COUNT: 8,
               TRIANGLE_BUDGET: 65000,
               KILLMARK_DECAL: 1,
               MAX_DECAL_COUNT: 18,
               DAMAGE_LOCATORS_MIN: 12,
               MIN_CORP_BANNERS: 0,
               MIN_ALLIANCE_BANNERS: 0,
               MAX_CORP_BANNERS: 2,
               MAX_ALLIANCE_BANNERS: 2},
 'cruiser': {MIN_TURRET_LOCATOR_COUNT: 6,
             TRIANGLE_BUDGET: 85000,
             KILLMARK_DECAL: 1,
             MAX_DECAL_COUNT: 18,
             DAMAGE_LOCATORS_MIN: 15,
             MIN_CORP_BANNERS: 0,
             MIN_ALLIANCE_BANNERS: 0,
             MAX_CORP_BANNERS: 2,
             MAX_ALLIANCE_BANNERS: 2},
 'industrial': {MIN_TURRET_LOCATOR_COUNT: 3,
                TRIANGLE_BUDGET: 100000,
                KILLMARK_DECAL: 1,
                MAX_DECAL_COUNT: 18,
                DAMAGE_LOCATORS_MIN: 15,
                MIN_CORP_BANNERS: 0,
                MIN_ALLIANCE_BANNERS: 0,
                MAX_CORP_BANNERS: 2,
                MAX_ALLIANCE_BANNERS: 2},
 'industrialcommandship': {MIN_TURRET_LOCATOR_COUNT: 6,
                           TRIANGLE_BUDGET: 140000,
                           KILLMARK_DECAL: 1,
                           MAX_DECAL_COUNT: 20,
                           DAMAGE_LOCATORS_MIN: 42,
                           MIN_CORP_BANNERS: 0,
                           MIN_ALLIANCE_BANNERS: 0,
                           MAX_CORP_BANNERS: 2,
                           MAX_ALLIANCE_BANNERS: 2},
 'barge': {MIN_TURRET_LOCATOR_COUNT: 2,
           TRIANGLE_BUDGET: 100000,
           KILLMARK_DECAL: 1,
           MAX_DECAL_COUNT: 18,
           DAMAGE_LOCATORS_MIN: 15,
           MIN_CORP_BANNERS: 0,
           MIN_ALLIANCE_BANNERS: 0,
           MAX_CORP_BANNERS: 2,
           MAX_ALLIANCE_BANNERS: 2},
 'battlecruiser': {MIN_TURRET_LOCATOR_COUNT: 8,
                   TRIANGLE_BUDGET: 100000,
                   KILLMARK_DECAL: 1,
                   MAX_DECAL_COUNT: 18,
                   DAMAGE_LOCATORS_MIN: 10,
                   MIN_CORP_BANNERS: 0,
                   MIN_ALLIANCE_BANNERS: 0,
                   MAX_CORP_BANNERS: 2,
                   MAX_ALLIANCE_BANNERS: 2},
 'battleship': {MIN_TURRET_LOCATOR_COUNT: 8,
                TRIANGLE_BUDGET: 100000,
                KILLMARK_DECAL: 1,
                MAX_DECAL_COUNT: 18,
                DAMAGE_LOCATORS_MIN: 20,
                MIN_CORP_BANNERS: 0,
                MIN_ALLIANCE_BANNERS: 0,
                MAX_CORP_BANNERS: 2,
                MAX_ALLIANCE_BANNERS: 2},
 'freighter': {MIN_TURRET_LOCATOR_COUNT: 4,
               TRIANGLE_BUDGET: 100000,
               KILLMARK_DECAL: 1,
               MAX_DECAL_COUNT: 20,
               DAMAGE_LOCATORS_MIN: 30,
               MIN_CORP_BANNERS: 0,
               MIN_ALLIANCE_BANNERS: 0,
               MAX_CORP_BANNERS: 2,
               MAX_ALLIANCE_BANNERS: 2},
 'dreadnought': {MIN_TURRET_LOCATOR_COUNT: 8,
                 TRIANGLE_BUDGET: 115000,
                 KILLMARK_DECAL: 1,
                 MAX_DECAL_COUNT: 24,
                 DAMAGE_LOCATORS_MIN: 30,
                 MIN_CORP_BANNERS: 0,
                 MIN_ALLIANCE_BANNERS: 0,
                 MAX_CORP_BANNERS: 2,
                 MAX_ALLIANCE_BANNERS: 3},
 'carrier': {MIN_TURRET_LOCATOR_COUNT: 8,
             TRIANGLE_BUDGET: 150000,
             KILLMARK_DECAL: 1,
             MAX_DECAL_COUNT: 20,
             DAMAGE_LOCATORS_MIN: 42,
             MIN_CORP_BANNERS: 0,
             MIN_ALLIANCE_BANNERS: 0,
             MAX_CORP_BANNERS: 2,
             MAX_ALLIANCE_BANNERS: 3},
 'forceauxillary': {MIN_TURRET_LOCATOR_COUNT: 6,
                    TRIANGLE_BUDGET: 150000,
                    KILLMARK_DECAL: 1,
                    MAX_DECAL_COUNT: 24,
                    DAMAGE_LOCATORS_MIN: 42,
                    MIN_CORP_BANNERS: 0,
                    MIN_ALLIANCE_BANNERS: 0,
                    MAX_CORP_BANNERS: 2,
                    MAX_ALLIANCE_BANNERS: 3},
 'titan': {MIN_TURRET_LOCATOR_COUNT: 8,
           TRIANGLE_BUDGET: 250000,
           KILLMARK_DECAL: 1,
           MAX_DECAL_COUNT: 24,
           DAMAGE_LOCATORS_MIN: 60,
           MIN_CORP_BANNERS: 0,
           MIN_ALLIANCE_BANNERS: 0,
           MAX_CORP_BANNERS: 2,
           MAX_ALLIANCE_BANNERS: 3},
 'vat': {MIN_TURRET_LOCATOR_COUNT: 0,
         TRIANGLE_BUDGET: 50000,
         KILLMARK_DECAL: 0,
         MAX_DECAL_COUNT: 10,
         DAMAGE_LOCATORS_MIN: 5},
 'battlestation': {MIN_TURRET_LOCATOR_COUNT: 0,
                   TRIANGLE_BUDGET: 250000,
                   KILLMARK_DECAL: 0,
                   MAX_DECAL_COUNT: 50,
                   DAMAGE_LOCATORS_MIN: 42},
 'corpse': {TRIANGLE_BUDGET: 15000,
            MAX_DECAL_COUNT: 0,
            DAMAGE_LOCATORS_MIN: 4},
 'station': {MIN_TURRET_LOCATOR_COUNT: 0,
             TRIANGLE_BUDGET: 350000,
             MAX_DECAL_COUNT: 50,
             DAMAGE_LOCATORS_MIN: 42},
 'station4k': {MIN_TURRET_LOCATOR_COUNT: 0,
               TRIANGLE_BUDGET: 350000,
               MAX_DECAL_COUNT: 50,
               DAMAGE_LOCATORS_MIN: 42},
 'nonreflective-4k-object': {MIN_TURRET_LOCATOR_COUNT: 0,
                             TRIANGLE_BUDGET: 350000,
                             MAX_DECAL_COUNT: 50,
                             DAMAGE_LOCATORS_MIN: 42},
 'shuttle': {MIN_TURRET_LOCATOR_COUNT: 0,
             TRIANGLE_BUDGET: 35000,
             KILLMARK_DECAL: 0,
             MAX_DECAL_COUNT: 10,
             DAMAGE_LOCATORS_MIN: 8},
 'fighter': {MIN_TURRET_LOCATOR_COUNT: 1,
             TRIANGLE_BUDGET: 35000,
             KILLMARK_DECAL: 0,
             MAX_DECAL_COUNT: 10,
             DAMAGE_LOCATORS_MIN: 5},
 'strategiccruiser': {MIN_CORP_BANNERS: 0,
                      MIN_ALLIANCE_BANNERS: 0,
                      MAX_CORP_BANNERS: 2,
                      MAX_ALLIANCE_BANNERS: 2,
                      KILLMARK_DECAL: 1,
                      MAX_DECAL_COUNT: 18},
 'wreck': {DAMAGE_LOCATORS_MIN: 20,
           MAX_DECAL_COUNT: 18},
 'structure_wreck': {DAMAGE_LOCATORS_MIN: 20,
                     MAX_DECAL_COUNT: 18},
 'structure_states': {},
 'structure_small': {MIN_TURRET_LOCATOR_COUNT: 0,
                     MAX_DECAL_COUNT: 24,
                     TRIANGLE_BUDGET: 100000,
                     DAMAGE_LOCATORS_MIN: 5,
                     MIN_CORP_BANNERS: 0,
                     MIN_ALLIANCE_BANNERS: 0,
                     MAX_CORP_BANNERS: 20,
                     MAX_ALLIANCE_BANNERS: 20},
 'structure_large': {MIN_TURRET_LOCATOR_COUNT: 8,
                     TRIANGLE_BUDGET: 350000,
                     MAX_DECAL_COUNT: 50,
                     DAMAGE_LOCATORS_MIN: 20,
                     MIN_CORP_BANNERS: 0,
                     MIN_ALLIANCE_BANNERS: 0,
                     MAX_CORP_BANNERS: 20,
                     MAX_ALLIANCE_BANNERS: 20},
 'structure_medium': {MIN_TURRET_LOCATOR_COUNT: 0,
                      TRIANGLE_BUDGET: 200000,
                      MAX_DECAL_COUNT: 50,
                      DAMAGE_LOCATORS_MIN: 42,
                      MIN_CORP_BANNERS: 0,
                      MIN_ALLIANCE_BANNERS: 0,
                      MAX_CORP_BANNERS: 20,
                      MAX_ALLIANCE_BANNERS: 20},
 'structure_xl': {MIN_TURRET_LOCATOR_COUNT: 8,
                  TRIANGLE_BUDGET: 500000,
                  KILLMARK_DECAL: 1,
                  MAX_DECAL_COUNT: 50,
                  DAMAGE_LOCATORS_MIN: 42,
                  MIN_CORP_BANNERS: 0,
                  MIN_ALLIANCE_BANNERS: 0,
                  MAX_CORP_BANNERS: 20,
                  MAX_ALLIANCE_BANNERS: 20},
 'drone': {MIN_TURRET_LOCATOR_COUNT: 1,
           TRIANGLE_BUDGET: 16000,
           MAX_DECAL_COUNT: 10,
           DAMAGE_LOCATORS_MIN: 5},
 'capsule': {MIN_TURRET_LOCATOR_COUNT: 0,
             TRIANGLE_BUDGET: 16000,
             MAX_DECAL_COUNT: 10,
             DAMAGE_LOCATORS_MIN: 5},
 'control_tower': {MAX_DECAL_COUNT: 24},
 'celestial': {MAX_DECAL_COUNT: 24},
 'jumpgate': {MIN_TURRET_LOCATOR_COUNT: 0,
              MAX_DECAL_COUNT: 50,
              DAMAGE_LOCATORS_MIN: 42},
 'container': {MAX_DECAL_COUNT: 10,
               MIN_TURRET_LOCATOR_COUNT: 0,
               TRIANGLE_BUDGET: 4200,
               DAMAGE_LOCATORS_MIN: 10},
 'asteroid': {MIN_TURRET_LOCATOR_COUNT: 0,
              TRIANGLE_BUDGET: 20000,
              DAMAGE_LOCATORS_MIN: 1,
              MAX_DECAL_COUNT: 0},
 'asteroid_field': {MIN_TURRET_LOCATOR_COUNT: 0,
                    TRIANGLE_BUDGET: 65000,
                    DAMAGE_LOCATORS_MIN: 10,
                    MAX_DECAL_COUNT: 0},
 'dummy_turret': {MIN_TURRET_LOCATOR_COUNT: 1,
                  TRIANGLE_BUDGET: 5,
                  DAMAGE_LOCATORS_MIN: 0,
                  MAX_DECAL_COUNT: 0},
 'placeholder': {DAMAGE_LOCATORS_MIN: 0,
                 MAX_DECAL_COUNT: 0},
 'hangar': {KILLMARK_DECAL: 0,
            MAX_DECAL_COUNT: 50,
            DAMAGE_LOCATORS_MIN: 0,
            MIN_CORP_BANNERS: 0,
            MIN_ALLIANCE_BANNERS: 0,
            MAX_CORP_BANNERS: 20,
            MAX_ALLIANCE_BANNERS: 20},
 'drone_traffic': {TRIANGLE_BUDGET: 8000},
 'hangar4k': {KILLMARK_DECAL: 0,
              MAX_DECAL_COUNT: 50,
              DAMAGE_LOCATORS_MIN: 0,
              MIN_CORP_BANNERS: 0,
              MIN_ALLIANCE_BANNERS: 0,
              MAX_CORP_BANNERS: 20,
              MAX_ALLIANCE_BANNERS: 20},
 'structure_wreck4k': {DAMAGE_LOCATORS_MIN: 20,
                       MAX_DECAL_COUNT: 18}}

def GetLimits(context, hullCategory):
    if hullCategory not in consts:
        context.Error(None, 'Could not find category specification for: ' + str(hullCategory))
        return
    return consts[hullCategory]


def GetValue(category, key, default = None):
    if category not in consts:
        return default
    if key not in consts[category]:
        return default
    return consts[category][key]
