#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\evecorporation\corp_ui_recruitment_const.py
from brennivin.itertoolsext import Bundle
MAX_SELECTED_TYPES = 4
MAX_SELECTED_AREAS = 2
MAX_HOURS = 8
AREA_OF_OPERATIONS_GROUPID = 6
TIMEZONE_GROUPID = 8
PLAYSTYLE_GROUPID = 11
LANGUAGE_GROUPID = 10
DEPRECATED_GROUPID = 79
OTHER_GROUPID = 80
JAPANESE_TYPEID = 1
ENGLISH_TYPEID = 7
GERMAN_TYPEID = 8
SPANISH_TYPEID = 9
RUSSIAN_TYPEID = 10
FRENCH_TYPEID = 11
KOREAN_TYPEID = 42
ROLEPLAY_TYPEID = 0
INCURSIONS_TYPEID = 2
PRODUCTION_TYPEID = 13
RESEARCH_TYPEID = 14
BOUNTYHUNTING_TYPEID = 15
ESS_TYPEID = 16
GATECAMPS_TYPEID = 17
ROAMS_TYPEID = 18
BLACKOPS_TYPEID = 19
ABYSSALPVP_TYPEID = 20
CAPITALWARFARE_TYPEID = 21
HAULING_TYPEID = 22
NEWPILOTFOCUSED_TYPEID = 23
TRADE_TYPEID = 24
MISSIONRUNNING_TYPEID = 25
ALLIANCEWARFARE_TYPEID = 26
EXPLORATION_TYPEID = 28
RESOURCEHARVESTING_TYPEID = 29
FACTIONWARFARE_TYPEID = 31
PIRACY_TYPEID = 32
SMALLSCALEGANGS_TYPEID = 33
NEWPILOTFRIENTLY_TYPEID = 34
ABYSSALDEADSPACE_TYPEID = 35
COMBATANOMALIES_TYPEID = 36
TRIGSPACE_TYPEID = 40
CAPITALSITES_TYPEID = 41
PIRATESTRONGHOLD_TYPEID = 43
ESCALATIONS_TYPEID = 44
HIGHSEC_TYPEID = 12
LOWSEC_TYPEID = 37
NULLSEC_TYPEID = 38
WORMHOLESPACE_TYPEID = 39
PVECOMBINED_ID = 100
PVPCOMBINED_ID = 200
TRADECOMBINED_ID = 300
OTHERCOMBINED_ID = 400
PVECOMBINED_TYPEIDS = (EXPLORATION_TYPEID,
 MISSIONRUNNING_TYPEID,
 INCURSIONS_TYPEID,
 PIRATESTRONGHOLD_TYPEID,
 ABYSSALDEADSPACE_TYPEID,
 COMBATANOMALIES_TYPEID,
 ESCALATIONS_TYPEID,
 TRIGSPACE_TYPEID,
 CAPITALSITES_TYPEID)
PVPCOMBINED_TYPEIDS = (ALLIANCEWARFARE_TYPEID,
 FACTIONWARFARE_TYPEID,
 ESS_TYPEID,
 GATECAMPS_TYPEID,
 ROAMS_TYPEID,
 BLACKOPS_TYPEID,
 ABYSSALPVP_TYPEID,
 CAPITALWARFARE_TYPEID)
TRADECOMBINED_TYPEIDS = (TRADE_TYPEID,
 RESOURCEHARVESTING_TYPEID,
 PRODUCTION_TYPEID,
 HAULING_TYPEID)
OTHER_TYPEIDS = (NEWPILOTFRIENTLY_TYPEID, ROLEPLAY_TYPEID, NEWPILOTFOCUSED_TYPEID)
PLAYSTYLE_GROUPS = (PVECOMBINED_ID, PVPCOMBINED_ID, TRADECOMBINED_ID)
COMBINED_GROUPS = {PVECOMBINED_ID: Bundle(playstyleTypeIDs=PVECOMBINED_TYPEIDS, combinedNamePath='UI/Corporations/CorporationWindow/Recruitment/PVE'),
 PVPCOMBINED_ID: Bundle(playstyleTypeIDs=PVPCOMBINED_TYPEIDS, combinedNamePath='UI/Corporations/CorporationWindow/Recruitment/PVP'),
 TRADECOMBINED_ID: Bundle(playstyleTypeIDs=TRADECOMBINED_TYPEIDS, combinedNamePath='UI/Corporations/CorporationWindow/Recruitment/Trade')}
COMBINED_GROUP_BY_TYPEID = {}
for groupID, groupInfo in COMBINED_GROUPS.iteritems():
    for typeID in groupInfo.playstyleTypeIDs:
        COMBINED_GROUP_BY_TYPEID[typeID] = groupID

FILTERSTATE_WANT = 1
SHOWSEARCHMATCH = True
CHECKBOX_ACTIVE_ICON = 'res:/UI/Texture/classes/UtilMenu/checkBoxActive.png'
CHECKBOX_INACTIVE_ICON = 'res:/UI/Texture/classes/UtilMenu/checkBoxInactive.png'
MATCHED_COLOR = '<color=0xbfffffff>'
UNMATCHED_COLOR = '<color=0x2fffffff>'
WHITE_COLOR = '<color=0xffffffff>'
MAX_TIME_RANGE = MAX_HOURS / 24.0
UI_SETTING_MAX_ISK_TAX_RATE = 'corporation_recruitment_max_isk_tax_rate'
UI_SETTING_MAX_LP_TAX_RATE = 'corporation_recruitment_max_lp_tax_rate'
