#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\common\lib\autoexec_client.py


def import_client():
    import stackless
    from carbon.common.lib import autoexec_client_core
    from eve.common.lib import autoexec_evecore
    autoexec_evecore.SetupEveSpecificLogging()
    stackless.getcurrent().block_trap = True
    appCacheDirs = ['Browser',
     'Browser/Img',
     'Map',
     'Pictures',
     'Pictures/Alliances',
     'Pictures/Gids',
     'Pictures/Planets',
     'Pictures/Portraits',
     'Pictures/Characters',
     'Pictures/Characters/Chat',
     'Pictures/Types',
     'Pictures/Blueprints',
     'Temp',
     'Temp/Mapbrowser',
     'Texture',
     'Texture/Planets',
     'Texture/Planets/Visited',
     'Shader',
     'Fonts']
    userCacheDirs = ['/EVE/capture',
     '/EVE/capture/Screenshots',
     '/EVE/capture/Portraits',
     '/EVE/logs',
     '/EVE/logs/Chatlogs',
     '/EVE/logs/Gamelogs',
     '/EVE/logs/Marketlogs',
     '/EVE/logs/Fleetlogs']
    servicesToRun = ['publicGatewaySvc',
     'counter',
     'contracts',
     'sessionMgr',
     'addressbook',
     'clientStatsSvc',
     'dataconfig',
     'godma',
     'photo',
     'machoNet',
     'mailSvc',
     'notificationSvc',
     'objectCaching',
     'chat',
     'XmppChat',
     'inv',
     'pwn',
     'focus',
     'debug',
     'jumpQueue',
     'scanSvc',
     'localizationClient',
     'jumpMonitor',
     'calendar',
     'LiveUpdateSvc',
     'monitor',
     'processHealth',
     'planetInfo',
     'browserImage',
     'sofService',
     'prefetchSvc',
     'projectDiscoveryClient',
     'structureServices',
     'logControlSvc',
     'dbuffClient',
     'operationsEventDirector',
     'conversationService',
     'cosmeticsSvc',
     'cosmeticsLicenseSvc',
     'environment',
     'standing',
     'bannedwords_client',
     'pvptrade',
     'fleet',
     'mutualWarInvites',
     'warPermit',
     'progressionSvc',
     'systemWideEffectSvc',
     'gatekeeper',
     'expertSystemSvc',
     'cloaking',
     'recommendationSvc',
     'cynoTravel',
     'milestoneSvc',
     'characterEnergySvc',
     'solarsystemInterferenceSvc',
     'voidSpaceSvc',
     'noddiTestRunner',
     'structureHangarViewSvc',
     'fwAdvantageSvc',
     'fwEnlistmentSvc',
     'shipcaster',
     'deathzoneSvc',
     'insurgencyCampaignSvc',
     'insurgencyDashboardSvc',
     'towGameSvc',
     'gatejump',
     'tale']
    autoexec_evecore.SetupForChina()
    autoexec_client_core.StartClient(appCacheDirs, userCacheDirs, servicesToRun)


import_client()
