#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\eveclientqatools\sofpreviewer\modelconst.py
import re

class ModelConst(object):
    DEFAULT_FACTION_FOR_T2HULLS = {'ardishapur': ['ac2_t2b',
                    'ai2_t2',
                    'af5_t2',
                    'ab2_t2',
                    'af2_t2',
                    'ac4_t2'],
     'brutor': ['mf1_t2a',
                'mcb1_t2c',
                'mf5_t2a',
                'mc3_t2a',
                'mf7_t2c',
                'mc2_t2a',
                'mbc2_t2',
                'mb2_t2',
                'mf4_t2a',
                'mdh1_t2',
                'mdl1_t2',
                'mdm1_t2',
                'msd1_t2'],
     'creodron': ['gfr1_t2',
                  'gbc2_t2',
                  'gf5_t2',
                  'gf4_t2a',
                  'gc3_t2',
                  'gb1_t2',
                  'gdh1_t2',
                  'gdl1_t2',
                  'gdm1_t2',
                  'gsd1_t2'],
     'development': ['oref1_t2b'],
     'duvolle': ['gc1_t2a',
                 'gbc1_t2a',
                 'gc4_t2a',
                 'gf7_t2',
                 'gb2_t2',
                 'gf3_t2',
                 'gf6_t2b',
                 'gi4_t2'],
     'ishukone': ['cf3_t2',
                  'cc2_t2b',
                  'cc4_t2a',
                  'cf7_t2b',
                  'cfr1_t2',
                  'cbc1_t2b'],
     'kaalakiota': ['ci2_t2',
                    'cf2_t2a',
                    'cde1_t2',
                    'cbc2_t2',
                    'cc2_t2a',
                    'cc4_t2b',
                    'cb2_t2'],
     'khanid': ['af7_t2',
                'ac1_t2a',
                'abc1_t2a',
                'ade1_t2',
                'ai1_t2',
                'af4_t2a',
                'ac2_t2a',
                'af3_t2a'],
     'laidai': ['cc1_t2',
                'ci3_t2',
                'cc3_t2',
                'cb1_t2',
                'cf7_t2a',
                'cf4_t2',
                'cf6_t2',
                'cf2_t2b',
                'cdh1_t2',
                'cdl1_t2',
                'cdm1_t2',
                'csd1_t2'],
     'orebase': ['oredh1_t2'],
     'prospecting': ['oreba3_t2', 'oreba2_t2', 'oreba1_t2'],
     'roden': ['gf6_t2a',
               'gf4_t2b',
               'gde1_t2',
               'gc1_t2b',
               'gi2_t2',
               'gc2_t2',
               'gc4_t2b'],
     'sarum': ['abc_t2',
               'afr1_t2',
               'af4_t2b',
               'ac3_t2',
               'ab1_t2',
               'ac1_t2b',
               'af3_t2b',
               'adh1_t2',
               'adl1_t2',
               'adm1_t2',
               'asd1_t2'],
     'sebiestor': ['mc2_t2c',
                   'mi3_t2c',
                   'mc3_t2c',
                   'mde1_t2c',
                   'mc4_t2c',
                   'mf1_t2c'],
     'thukker': ['mf2_t2b',
                 'mf4_t2b',
                 'mi2_t2b',
                 'mfr1_t2',
                 'mb1_t2b',
                 'mc1_t2b']}
    MULTI_HULL_SPECIFICATION_REGEX = re.compile('_s\\d')
    MULTI_HULL_VARIATION_REGEX = re.compile('v\\d')
    MULTI_HULL_REGEX = re.compile('_s\\dv\\d')
    MAX_MULTI_HULLS = 4
