#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\shared\fleet\fleetBroadcastConst.py
import evefleet
import eveicon
from eve.client.script.parklife import states as state
from evefleet import BROADCAST_LOCATION, BROADCAST_JUMP_BEACON, BROADCAST_HOLD_POSITION, BROADCAST_TRAVEL_TO, BROADCAST_JUMP_TO, BROADCAST_ALIGN_TO, BROADCAST_NEED_BACKUP, BROADCAST_WARP_TO, BROADCAST_HEAL_CAPACITOR, BROADCAST_HEAL_SHIELD, BROADCAST_HEAL_ARMOR, BROADCAST_TARGET, BROADCAST_ENEMY_SPOTTED, BROADCAST_IN_POSITION, BROADCAST_SHOW_OWN, BROADCAST_REP_TARGET
activeBroadcastColor = 'ddffffff'
flagToName = {state.gbEnemySpotted: BROADCAST_ENEMY_SPOTTED,
 state.gbTarget: BROADCAST_TARGET,
 state.gbHealTarget: BROADCAST_REP_TARGET,
 state.gbHealShield: BROADCAST_HEAL_SHIELD,
 state.gbHealArmor: BROADCAST_HEAL_ARMOR,
 state.gbHealCapacitor: BROADCAST_HEAL_CAPACITOR,
 state.gbWarpTo: BROADCAST_WARP_TO,
 state.gbNeedBackup: BROADCAST_NEED_BACKUP,
 state.gbAlignTo: BROADCAST_ALIGN_TO,
 state.gbJumpTo: BROADCAST_JUMP_TO,
 state.gbInPosition: BROADCAST_IN_POSITION,
 state.gbHoldPosition: BROADCAST_HOLD_POSITION,
 state.gbTravelTo: BROADCAST_TRAVEL_TO,
 state.gbJumpBeacon: BROADCAST_JUMP_BEACON,
 state.gbLocation: BROADCAST_LOCATION,
 -1: 'Event'}
iconsByBroadcastType = {BROADCAST_ENEMY_SPOTTED: 'res:/UI/Texture/classes/Fleet/Broadcast/16/enemySpotted.png',
 BROADCAST_TARGET: 'res:/UI/Texture/classes/Fleet/Broadcast/16/target.png',
 BROADCAST_REP_TARGET: eveicon.heal_first_aid,
 BROADCAST_HEAL_ARMOR: 'res:/UI/Texture/classes/Fleet/Broadcast/16/needArmor.png',
 BROADCAST_HEAL_SHIELD: 'res:/UI/Texture/classes/Fleet/Broadcast/16/needShield.png',
 BROADCAST_HEAL_CAPACITOR: 'res:/UI/Texture/classes/Fleet/Broadcast/16/needCapacitor.png',
 BROADCAST_WARP_TO: 'res:/UI/Texture/classes/Fleet/Broadcast/16/warpTo.png',
 BROADCAST_NEED_BACKUP: 'res:/UI/Texture/classes/Fleet/Broadcast/16/needBackup.png',
 BROADCAST_ALIGN_TO: 'res:/UI/Texture/classes/Fleet/Broadcast/16/alignTo.png',
 BROADCAST_JUMP_TO: 'res:/UI/Texture/classes/Fleet/Broadcast/16/jumpTo.png',
 BROADCAST_TRAVEL_TO: 'res:/UI/Texture/classes/Fleet/Broadcast/16/travelTo.png',
 BROADCAST_IN_POSITION: 'res:/UI/Texture/classes/Fleet/Broadcast/16/inPosition.png',
 BROADCAST_HOLD_POSITION: 'res:/UI/Texture/classes/Fleet/Broadcast/16/holdPosition.png',
 BROADCAST_JUMP_BEACON: 'res:/UI/Texture/classes/Fleet/Broadcast/16/jumpBeacon.png',
 BROADCAST_LOCATION: 'res:/UI/Texture/classes/Fleet/Broadcast/16/locationPin.png'}
iconsLargeByBroadcastType = {BROADCAST_ENEMY_SPOTTED: 'res:/UI/Texture/classes/Fleet/Broadcast/32/enemySpotted.png',
 BROADCAST_TARGET: 'res:/UI/Texture/classes/Fleet/Broadcast/32/target.png',
 BROADCAST_REP_TARGET: eveicon.heal_first_aid,
 BROADCAST_HEAL_ARMOR: 'res:/UI/Texture/classes/Fleet/Broadcast/32/needArmor.png',
 BROADCAST_HEAL_SHIELD: 'res:/UI/Texture/classes/Fleet/Broadcast/32/needShield.png',
 BROADCAST_HEAL_CAPACITOR: 'res:/UI/Texture/classes/Fleet/Broadcast/32/needCapacitor.png',
 BROADCAST_WARP_TO: 'res:/UI/Texture/classes/Fleet/Broadcast/32/warpTo.png',
 BROADCAST_NEED_BACKUP: 'res:/UI/Texture/classes/Fleet/Broadcast/32/needBackup.png',
 BROADCAST_ALIGN_TO: 'res:/UI/Texture/classes/Fleet/Broadcast/32/alignTo.png',
 BROADCAST_JUMP_TO: 'res:/UI/Texture/classes/Fleet/Broadcast/32/jumpTo.png',
 BROADCAST_TRAVEL_TO: 'res:/UI/Texture/classes/Fleet/Broadcast/32/travelTo.png',
 BROADCAST_IN_POSITION: 'res:/UI/Texture/classes/Fleet/Broadcast/32/inPosition.png',
 BROADCAST_HOLD_POSITION: 'res:/UI/Texture/classes/Fleet/Broadcast/32/holdPosition.png',
 BROADCAST_JUMP_BEACON: 'res:/UI/Texture/classes/Fleet/Broadcast/32/jumpBeacon.png',
 BROADCAST_LOCATION: 'res:/UI/Texture/classes/Fleet/Broadcast/32/locationPin.png'}
broadcastNames = {BROADCAST_ENEMY_SPOTTED: 'UI/Fleet/FleetBroadcast/Commands/EnemySpotted',
 BROADCAST_TARGET: 'UI/Fleet/FleetBroadcast/Commands/BroadcastTarget',
 BROADCAST_REP_TARGET: 'UI/Fleet/FleetBroadcast/Commands/BroadcastHealTarget',
 BROADCAST_HEAL_ARMOR: 'UI/Fleet/FleetBroadcast/Commands/HealArmor',
 BROADCAST_HEAL_SHIELD: 'UI/Fleet/FleetBroadcast/Commands/HealShield',
 BROADCAST_HEAL_CAPACITOR: 'UI/Fleet/FleetBroadcast/Commands/HealCapacitor',
 BROADCAST_WARP_TO: 'UI/Fleet/FleetBroadcast/Commands/BroadcastWarpTo',
 BROADCAST_NEED_BACKUP: 'UI/Fleet/FleetBroadcast/Commands/NeedBackup',
 BROADCAST_ALIGN_TO: 'UI/Fleet/FleetBroadcast/Commands/BroadcastAlignTo',
 BROADCAST_JUMP_TO: 'UI/Fleet/FleetBroadcast/Commands/BroadcastJumpTo',
 BROADCAST_TRAVEL_TO: 'UI/Fleet/FleetBroadcast/Commands/BroadcastTravelTo',
 BROADCAST_IN_POSITION: 'UI/Fleet/FleetBroadcast/Commands/InPosition',
 BROADCAST_HOLD_POSITION: 'UI/Fleet/FleetBroadcast/Commands/HoldPosition',
 BROADCAST_JUMP_BEACON: 'UI/Fleet/FleetBroadcast/Commands/JumpBeacon',
 BROADCAST_LOCATION: 'UI/Fleet/FleetBroadcast/Commands/Location',
 BROADCAST_SHOW_OWN: 'UI/Fleet/FleetBroadcast/Commands/ShowOwnBroadcasts',
 'Event': 'UI/Fleet/FleetBroadcast/FleetEvent'}
LISTEN_BROADCAST_SETTING = 'listenBroadcast_%s'
BROADCAST_COLOR_SETTING = 'fleet_broadcastcolor_%s'
broadcastScopes = {evefleet.BROADCAST_DOWN: {evefleet.BROADCAST_UNIVERSE: 'UI/Fleet/FleetBroadcast/BroadcastRangeDown',
                           evefleet.BROADCAST_SYSTEM: 'UI/Fleet/FleetBroadcast/BroadcastRangeDownSystem',
                           evefleet.BROADCAST_BUBBLE: 'UI/Fleet/FleetBroadcast/BroadcastRangeDownBubble'},
 evefleet.BROADCAST_UP: {evefleet.BROADCAST_UNIVERSE: 'UI/Fleet/FleetBroadcast/BroadcastRangeUp',
                         evefleet.BROADCAST_SYSTEM: 'UI/Fleet/FleetBroadcast/BroadcastRangeUpSystem',
                         evefleet.BROADCAST_BUBBLE: 'UI/Fleet/FleetBroadcast/BroadcastRangeUpBubble'},
 evefleet.BROADCAST_ALL: {evefleet.BROADCAST_UNIVERSE: 'UI/Fleet/FleetBroadcast/BroadcastRangeAll',
                          evefleet.BROADCAST_SYSTEM: 'UI/Fleet/FleetBroadcast/BroadcastRangeAllSystem',
                          evefleet.BROADCAST_BUBBLE: 'UI/Fleet/FleetBroadcast/BroadcastRangeAllBubble'}}
broadcastRanges = {BROADCAST_TARGET: evefleet.BROADCAST_BUBBLE,
 BROADCAST_REP_TARGET: evefleet.BROADCAST_BUBBLE,
 BROADCAST_HEAL_ARMOR: evefleet.BROADCAST_BUBBLE,
 BROADCAST_HEAL_SHIELD: evefleet.BROADCAST_BUBBLE,
 BROADCAST_HEAL_CAPACITOR: evefleet.BROADCAST_BUBBLE,
 BROADCAST_WARP_TO: evefleet.BROADCAST_SYSTEM,
 BROADCAST_ALIGN_TO: evefleet.BROADCAST_SYSTEM,
 BROADCAST_JUMP_TO: evefleet.BROADCAST_SYSTEM}
defaultBroadcastRange = evefleet.BROADCAST_UNIVERSE
broadcastRangeNames = {evefleet.BROADCAST_UNIVERSE: 'UI/Fleet/FleetBroadcast/BroadcastRangeGlobal',
 evefleet.BROADCAST_SYSTEM: 'UI/Fleet/FleetBroadcast/BroadcastRangeSystem',
 evefleet.BROADCAST_BUBBLE: 'UI/Fleet/FleetBroadcast/BroadcastRangeBubble'}
broadcastButtonIDs = (BROADCAST_ENEMY_SPOTTED,
 BROADCAST_HEAL_ARMOR,
 BROADCAST_HEAL_SHIELD,
 BROADCAST_HEAL_CAPACITOR,
 BROADCAST_IN_POSITION,
 BROADCAST_NEED_BACKUP,
 BROADCAST_HOLD_POSITION,
 BROADCAST_LOCATION)
