#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\station\loyaltyPointStore\lpStoreConst.py
from appConst import factionAmarrEmpire, factionAngelCartel, factionCONCORDAssembly, factionCaldariState, factionGallenteFederation, factionGuristasPirates, factionInterBus, factionKhanidKingdom, factionMinmatarRepublic, factionORE, factionSanshasNation, factionSerpentis, factionTheBloodRaiderCovenant, factionTheServantSistersofEVE, factionTheSyndicate, factionThukkerTribe, factionMordusLegionCommand, factionAmmatarMandate, factionTriglavian
FACTION_BACKGROUNDS = {factionAmarrEmpire: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Amarr_LPBackground.png',
 factionAngelCartel: 'res:/ui/texture/classes/lpstore/factionbackgrounds/AngelCartel_LPBackground.png',
 factionCONCORDAssembly: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Concord_LPBackground.png',
 factionCaldariState: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Caldari_LPBackground.png',
 factionGallenteFederation: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Gallente_LPBackground.png',
 factionGuristasPirates: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Guristas_LPBackground.png',
 factionInterBus: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Guristas_LPBackground.png',
 factionKhanidKingdom: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Khanid Kingdom_LPBackground.png',
 factionMinmatarRepublic: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Minmatar_LPBackground.png',
 factionORE: 'res:/ui/texture/classes/lpstore/factionbackgrounds/ORE_LPBackground.png',
 factionSanshasNation: 'res:/ui/texture/classes/lpstore/factionbackgrounds/SanshasNation_LPBackground.png',
 factionSerpentis: 'res:/ui/texture/classes/lpstore/factionbackgrounds/Serpentis_LPBackground.png',
 factionTheBloodRaiderCovenant: 'res:/ui/texture/classes/lpstore/factionbackgrounds/BloodRaider_LPBackground.png',
 factionTheServantSistersofEVE: 'res:/ui/texture/classes/lpstore/factionbackgrounds/ServantSistersEVE_LPBackground.png',
 factionTheSyndicate: 'res:/ui/texture/classes/lpstore/factionbackgrounds/TheSyndacate_LPBackground.png',
 factionThukkerTribe: 'res:/ui/texture/classes/lpstore/factionbackgrounds/ThukkerTribe_LPBackground.png',
 factionMordusLegionCommand: 'res:/ui/texture/classes/lpstore/factionbackgrounds/MordusLegionCommand_LPBackground.png',
 factionAmmatarMandate: 'res:/ui/texture/classes/lpstore/factionbackgrounds/AmmatarMandate_LPBackground.png',
 factionTriglavian: 'res:/ui/texture/classes/lpstore/factionbackgrounds/TriglavianCollective_LPBackground.png'}
