#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\station\loyaltyPointStore\paragonLpStoreConst.py
from eve.common.lib import appConst
FILTER_ALL_FACTIONS = 0
FILTER_OTHER_FACTIONS = 1
FILTER_EMPIRE_FACTIONS = appConst.factionByRace.values()
FILTER_ALL_HULLS = 0
FILTER_FACTION = 'faction'
FILTER_HULL = 'hull'
FILTER_CORP_EMBLEMS = 'corp'
FILTER_ALLIANCE_EMBLEMS = 'alliance'
FILTER_ACQUIRED = 'acquired'
DEFAULT_FILTER_FACTION = FILTER_ALL_FACTIONS
DEFAULT_FILTER_HULL = FILTER_ALL_HULLS
DEFAULT_FILTER_CORP_EMBLEMS = True
DEFAULT_FILTER_ALLIANCE_EMBLEMS = True
DEFAULT_FILTER_ACQUIRED = False
DEFAULT_PARAGON_FILTERS = {FILTER_FACTION: FILTER_ALL_FACTIONS,
 FILTER_HULL: FILTER_ALL_HULLS,
 FILTER_CORP_EMBLEMS: True,
 FILTER_ALLIANCE_EMBLEMS: True,
 FILTER_ACQUIRED: False}
