#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\localization\const.py
LOCALE_SHORT_ENGLISH = 'en-us'
LOCALE_SHORT_GERMAN = 'de'
LOCALE_SHORT_FRENCH = 'fr'
LOCALE_SHORT_SPANISH = 'es'
LOCALE_SHORT_RUSSIAN = 'ru'
LOCALE_SHORT_CHINESE = 'zh'
LOCALE_SHORT_JAPANESE = 'ja'
LOCALE_SHORT_ITALIAN = 'it'
LOCALE_SHORT_KOREAN = 'ko'
LANGUAGE_BY_LANGUAGE_ID = {LOCALE_SHORT_ENGLISH: 'English',
 LOCALE_SHORT_FRENCH: 'French',
 LOCALE_SHORT_GERMAN: 'German',
 LOCALE_SHORT_SPANISH: 'Spanish',
 LOCALE_SHORT_ITALIAN: 'Italian',
 LOCALE_SHORT_RUSSIAN: 'Russian',
 LOCALE_SHORT_CHINESE: 'Chinese',
 LOCALE_SHORT_JAPANESE: 'Japanese',
 LOCALE_SHORT_KOREAN: 'Korean'}
PRIMARY_LANGUAGE_ID = 'en-us'
DATATYPE_FSD = 0
CODE_UNIVERSAL = 'Universal'
GENDER_MALE = 0
GENDER_FEMALE = 1
GENDER_NEUTER = 2
GENDERS_EXACTLY_ONE_MALE = 0
GENDERS_EXACTLY_ONE_FEMALE = 1
GENDERS_AT_LEAST_ONE_MALE = 2
GENDERS_ALL_FEMALE = 3
GENDERS_UNDEFINED = 4
DEFAULT_MAXIMUM_DECIMAL_PLACES = 12
DEFAULT_LEADING_ZEROES = 0
PICKLE_LABELS_MESSAGEID = 'messageID'
PICKLE_LABELS_FULLPATH = 'FullPath'
PICKLE_LABELS_LABEL = 'label'
SYSTEM_LANGUAGE = ''
IMPORTANT_EN_OVERRIDE = 1
HIGHLIGHT_IMPORTANT_MARKER = '*'
