#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\shared\agencyNew\ui\contentGroupCards\contentGroupCardConstants.py
VERTICAL_CARD_HEIGHT = 333
VERTICAL_CARD_WIDTH = 200
HORIZONTAL_CARD_WIDTH = 400
HORIZONTAL_CARD_HEIGHT = 86
CLIPPING_PARENT_HEIGHT = 452
MAX_VISIBLE_VERTICAL_CARDS = 5
MAX_CONTENT_GROUP_WIDTH = MAX_VISIBLE_VERTICAL_CARDS * (VERTICAL_CARD_WIDTH + 20)
VERTICAL_CARD_FOOTER_CONTAINER_HEIGHT = 82
VERTICAL_CARD_BOTTOM_CONTAINER_HEIGHT = 44
EDGE_GRADIENT_WIDTH = 178
EDGE_GRADIENT_HEIGHT = CLIPPING_PARENT_HEIGHT
