#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\environment\effects\effectConsts.py
FX_MERGE_GUID = 1
FX_MERGE_SHIP = 2
FX_MERGE_MODULE = 3
FX_MERGE_TARGET = 4
FX_TF_NONE = 0
FX_TF_POSITION_BALL = 1
FX_TF_POSITION_MODEL = 7
FX_TF_POSITION_TARGET = 2
FX_TF_ROTATION_BALL = 3
FX_TF_SCALE_SYMMETRIC = 4
FX_TF_SCALE_BOUNDING = 5
FX_TF_SCALE_RADIUS = 6
FX_TF_ELLIPSOID = 8
