#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\inflight\overview\overviewConst.py
from collections import OrderedDict
from carbonui import uiconst
from eve.common.lib import appConst as const
HTML_ENTITIES = '&gt;|&lt;|&amp;|&GT;|&LT;|&AMP;'
HTML_ENTITY_REPLACEMENTS = {'&gt;': u'>',
 '&lt;': u'<',
 '&amp;': u'&',
 '&GT;': u'>',
 '&LT;': u'<',
 '&AMP;': u'&'}
COLUMN_VELOCITY = 'VELOCITY'
COLUMN_RADIALVELOCITY = 'RADIALVELOCITY'
COLUMN_ANGULARVELOCITY = 'ANGULARVELOCITY'
COLUMN_TRANSVERSALVELOCITY = 'TRANSVERSALVELOCITY'
COLUMN_DISTANCE = 'DISTANCE'
COLUMN_SIZE = 'SIZE'
COLUMN_MILITIA = 'MILITIA'
COLUMN_FACTION = 'FACTION'
COLUMN_CORPORATION = 'CORPORATION'
COLUMN_TAG = 'TAG'
COLUMN_TYPE = 'TYPE'
COLUMN_NAME = 'NAME'
COLUMN_ICON = 'ICON'
COLUMN_ALLIANCE = 'ALLIANCE'
DEFAULT_COLUMNS = [COLUMN_ICON,
 COLUMN_DISTANCE,
 COLUMN_NAME,
 COLUMN_TYPE,
 COLUMN_VELOCITY]
NAME_BY_COLUMN = OrderedDict([(COLUMN_ICON, 'UI/Generic/Icon'),
 (COLUMN_DISTANCE, 'UI/Common/Distance'),
 (COLUMN_NAME, 'UI/Common/Name'),
 (COLUMN_TYPE, 'UI/Common/Type'),
 (COLUMN_TAG, 'UI/Common/Tag'),
 (COLUMN_CORPORATION, 'UI/Common/Corporation'),
 (COLUMN_ALLIANCE, 'UI/Common/Alliance'),
 (COLUMN_FACTION, 'UI/Common/Faction'),
 (COLUMN_MILITIA, 'UI/Common/Militia'),
 (COLUMN_SIZE, 'UI/Inventory/ItemSize'),
 (COLUMN_VELOCITY, 'UI/Overview/Velocity'),
 (COLUMN_RADIALVELOCITY, 'UI/Overview/RadialVelocity'),
 (COLUMN_TRANSVERSALVELOCITY, 'UI/Overview/TraversalVelocity'),
 (COLUMN_ANGULARVELOCITY, 'UI/Generic/AngularVelocity')])
ALL_COLUMNS = NAME_BY_COLUMN.keys()
COLUMN_UNITS = {COLUMN_VELOCITY: 'UI/Overview/MetersPerSecondUnitShort',
 COLUMN_RADIALVELOCITY: 'UI/Overview/MetersPerSecondUnitShort',
 COLUMN_TRANSVERSALVELOCITY: 'UI/Overview/MetersPerSecondUnitShort',
 COLUMN_ANGULARVELOCITY: 'UI/Overview/DegreesPerSecondUnitShort'}
COLUMN_DESCRIPTIONS = {COLUMN_VELOCITY: 'UI/Overview/VelocityDescription',
 COLUMN_RADIALVELOCITY: 'UI/Overview/RadialVelocityDescription',
 COLUMN_TRANSVERSALVELOCITY: 'UI/Overview/TraversalVelocityDescription',
 COLUMN_ANGULARVELOCITY: 'UI/Overview/AngularVelocityDescription',
 COLUMN_TAG: 'UI/Overview/TagDescription',
 COLUMN_MILITIA: 'UI/Overview/MilitiaDescription',
 COLUMN_SIZE: 'UI/Overview/SizeDescription'}
COLUMNFADESIZE = 20
COLUMNMARGIN = uiconst.LABELTABMARGIN
COLUMNMINSIZE = 24
COLUMNMINDEFAULTSIZE = 80
FIXEDCOLUMNS = {COLUMN_ICON: 22}
COLUMN_DEFAULTSIZE = {COLUMN_NAME: 112,
 COLUMN_TYPE: 112,
 COLUMN_VELOCITY: 58,
 COLUMN_ANGULARVELOCITY: 58}
COLUMN_DO_NOT_EXPAND_FOR_LABEL = [COLUMN_VELOCITY, COLUMN_ANGULARVELOCITY]
ALLCOLUMNS = [COLUMN_VELOCITY,
 COLUMN_RADIALVELOCITY,
 COLUMN_ANGULARVELOCITY,
 COLUMN_TRANSVERSALVELOCITY,
 COLUMN_DISTANCE,
 COLUMN_SIZE,
 COLUMN_MILITIA,
 COLUMN_FACTION,
 COLUMN_CORPORATION,
 COLUMN_TAG,
 COLUMN_TYPE,
 COLUMN_NAME,
 COLUMN_ICON,
 COLUMN_ALLIANCE]
RIGHTALIGNEDCOLUMNS = [COLUMN_DISTANCE,
 COLUMN_SIZE,
 COLUMN_VELOCITY,
 COLUMN_RADIALVELOCITY,
 COLUMN_ANGULARVELOCITY,
 COLUMN_TRANSVERSALVELOCITY]
CURVE_HOSTILE = 2
CURVE_ATTACKING = 3
INVISIBLE_SPACEOBJECT_ICON = 'res:/UI/Texture/Icons/38_16_241.png'
LABEL_STATE = 'state'
LABEL_TYPE = 'type'
PRE = 'pre'
POST = 'post'
LABEL_BOLD = 'bold'
LABEL_ITALIC = 'italic'
LABEL_UNDERLINE = 'underline'
LABEL_COLOR = 'color'
LABEL_SIZE = 'fontsize'
CHAR_LT = '<'
CODE_LT = '&lt;'
CHAR_GT = '>'
CODE_GT = '&gt;'
APOSTROPHE = "'"
L_BRACKET = '('
R_BRACKET = ')'
L_SQ_BRACKET = '['
R_SQ_BRACKET = ']'
CHAR_SPACE = ' '
CHAR_NONE = ''
CHAR_COMMA = ','
CHAR_BR = '<br>'
LABEL_TYPE_NONE = None
LABEL_TYPE_SHIP_TYPE = 'ship type'
LABEL_TYPE_PILOT = 'pilot name'
LABEL_TYPE_CORP = 'corporation'
LABEL_TYPE_ALLIANCE = 'alliance'
LABEL_TYPE_SHIP_NAME = 'ship name'
LABEL_TYPE_LINEBREAK = 'linebreak'
BASIC_LABEL_TYPES = [LABEL_TYPE_NONE,
 LABEL_TYPE_SHIP_TYPE,
 LABEL_TYPE_PILOT,
 LABEL_TYPE_CORP,
 LABEL_TYPE_ALLIANCE,
 LABEL_TYPE_SHIP_NAME]
EXTRA_LABEL_TYPES = [LABEL_TYPE_LINEBREAK]
BASIC_VARIBLES = [LABEL_STATE,
 LABEL_TYPE,
 PRE,
 POST]
FORMATTING_VARIBLES = [LABEL_BOLD,
 LABEL_ITALIC,
 LABEL_UNDERLINE,
 LABEL_COLOR,
 LABEL_SIZE]
WINDOW_ID = 'overview'
KILOMETERS10 = 10000.0
KILOMETERS10000000 = 10000000000.0
FAINT_ENTRY_CATEGORIES = [const.categoryStructure, const.categorySovereigntyStructure]
VISIBLE_ENTRY_UPDATE_SLEEP = 0.5
ENTRY_ORDER_UPDATE_SLEEP_MIN = 0.5
ENTRY_ORDER_UPDATE_SLEEP = 1.0
