#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\orbitalSkyhook\const.py
STATE_UNKNOWN = 0
STATE_SHIELD_VULNERABLE = 210
STATE_ARMOR_REINFORCE = 211
STATE_ARMOR_VULNERABLE = 212
STATE_HULL_REINFORCE = 213
STATE_HULL_VULNERABLE = 214
DEFAULT_REPAIR_TIMER = 900
REINFORCE_DURATION_ARMOR_DEFAULT = 129600
LIMIT_WINDOW_LENGTH = 20
DEFAULT_EXIT_HOUR = 12
STATES = {STATE_UNKNOWN: 'unknown',
 STATE_SHIELD_VULNERABLE: 'shield_vulnerable',
 STATE_ARMOR_REINFORCE: 'armor_reinforce',
 STATE_ARMOR_VULNERABLE: 'armor_vulnerable',
 STATE_HULL_REINFORCE: 'hull_reinforce',
 STATE_HULL_VULNERABLE: 'hull_vulnerable'}
STATE_VULNERABILITY = {STATE_SHIELD_VULNERABLE: True,
 STATE_ARMOR_REINFORCE: False,
 STATE_ARMOR_VULNERABLE: True,
 STATE_HULL_REINFORCE: False,
 STATE_HULL_VULNERABLE: True}
STATE_SHIELD_ARMOR_HULL = {STATE_SHIELD_VULNERABLE: (1, 1, 1),
 STATE_ARMOR_REINFORCE: (0, 1, 1),
 STATE_ARMOR_VULNERABLE: (0, 1, 1),
 STATE_HULL_REINFORCE: (0, 0, 1),
 STATE_HULL_VULNERABLE: (0, 0, 1)}
OFFLINE_STATES = {STATE_UNKNOWN}
DISABLED_STATES = {STATE_UNKNOWN, STATE_HULL_REINFORCE, STATE_HULL_VULNERABLE}
STATE_LABELS = {STATE_SHIELD_VULNERABLE: 'UI/Structures/States/Vulnerable',
 STATE_ARMOR_REINFORCE: 'UI/Structures/States/Reinforced',
 STATE_ARMOR_VULNERABLE: 'UI/Structures/States/Vulnerable',
 STATE_HULL_REINFORCE: 'UI/Structures/States/Reinforced',
 STATE_HULL_VULNERABLE: 'UI/Structures/States/Vulnerable'}
YELLOW_TIMER_COLOR = (249 / 255.0,
 179 / 255.0,
 56 / 255.0,
 1.0)
BLUE_TIMER_COLOR = (0.0, 1.0, 1.0, 1.0)
STATE_COLOR = {STATE_UNKNOWN: BLUE_TIMER_COLOR,
 STATE_SHIELD_VULNERABLE: YELLOW_TIMER_COLOR,
 STATE_ARMOR_REINFORCE: BLUE_TIMER_COLOR,
 STATE_ARMOR_VULNERABLE: YELLOW_TIMER_COLOR,
 STATE_HULL_REINFORCE: BLUE_TIMER_COLOR,
 STATE_HULL_VULNERABLE: YELLOW_TIMER_COLOR}
STATE_CTRL_MAPPING = [STATE_SHIELD_VULNERABLE,
 STATE_ARMOR_REINFORCE,
 STATE_ARMOR_VULNERABLE,
 STATE_HULL_REINFORCE,
 STATE_HULL_VULNERABLE]
WORKFORCE = 0.0
ICE = 1.0
LAVA = 2.0
POWER = 3.0
SMALL_SIZE_CLASS = {WORKFORCE: 2000000,
 ICE: 1048577,
 LAVA: 1460000,
 POWER: 348200}
MEDIUM_SIZE_CLASS = {WORKFORCE: 3550000,
 ICE: 11700000,
 LAVA: 2720000,
 POWER: 14830000}
LARGE_SIZE_CLASS = {WORKFORCE: 5880000,
 ICE: 18900000,
 LAVA: 4160000,
 POWER: 28750000}
SMALL = 0.0
MEDIUM = 1.0
LARGE = 2.0
EXTRA_SMALL = 3.0
REAGENTS_VFX_NAME = 'Reagents'
ENERGY_VFX_NAME = 'Energy'
CTRL_ON = 1.0
CTRL_OFF = 0.0
RAIDING_STATE_INVULNERABLE = 0.0
RAIDING_STATE_VULNERABLE = 1.0
RAIDING_STATE_RAIDED = 2.0
PLANET_SIZE = 'Planet_Size'
TRANSPORT_TYPE = 'Transport_type'
SILO_VALUE = 'siloValue'
PLANET_RADIUS = 'Planet_Radius'
RAIDING_STATE = 'Raiding_state'
