#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\shared\mapView\mapViewSettings.py
from eve.client.script.ui.shared.mapView.mapViewConst import VIEWMODE_LAYOUT_REGIONS, VIEWMODE_LAYOUT_CONSTELLATIONS, VIEWMODE_LAYOUT_SETTINGS, DEFAULT_MAPVIEW_SETTINGS, VIEWMODE_LAYOUT_SHOW_ABSTRACT_SETTINGS, VIEWMODE_LINES_ALL, VIEWMODE_LINES_SELECTION_REGION, VIEWMODE_LINES_SELECTION, VIEWMODE_LINES_SETTINGS, VIEWMODE_LAYOUT_SOLARSYSTEM, VIEWMODE_LINES_SHOW_JUMP_BRIDGES_MY, VIEWMODE_LINES_SHOW_JUMP_BRIDGES_ALL, VIEWMODE_LINES_SHOW_JUMP_BRIDGES_SETTINGS
from localization import GetByLabel
ICON_ROOT = 'res:/UI/Texture/classes/MapView/'
SETTINGS_COG_ICON = 'res:/UI/Texture/Icons/44_32_4.png'
ICON_MAP_BY_ID = {VIEWMODE_LINES_ALL: ICON_ROOT + 'icon_all_lines.png',
 VIEWMODE_LINES_SELECTION: ICON_ROOT + 'icon_selectiononly_lines.png',
 VIEWMODE_LINES_SELECTION_REGION: ICON_ROOT + 'icon_region_lines.png',
 VIEWMODE_LAYOUT_SOLARSYSTEM: ICON_ROOT + 'icon_no_group.png',
 VIEWMODE_LAYOUT_CONSTELLATIONS: ICON_ROOT + 'icon_const_group.png',
 VIEWMODE_LAYOUT_REGIONS: ICON_ROOT + 'icon_reg_group.png'}
LABEL_MAP_BY_ID = {(VIEWMODE_LINES_SETTINGS, VIEWMODE_LINES_ALL): GetByLabel('UI/Map/MapPallet/cbAllLinesOnly'),
 (VIEWMODE_LINES_SETTINGS, VIEWMODE_LINES_SELECTION): GetByLabel('UI/Map/MapPallet/cbSelectionLinesOnly'),
 (VIEWMODE_LINES_SETTINGS, VIEWMODE_LINES_SELECTION_REGION): GetByLabel('UI/Map/MapPallet/cbSelectionRegionLinesOnly'),
 (VIEWMODE_LAYOUT_SETTINGS, VIEWMODE_LAYOUT_SOLARSYSTEM): GetByLabel('UI/Map/Layout/NoGrouping'),
 (VIEWMODE_LAYOUT_SETTINGS, VIEWMODE_LAYOUT_CONSTELLATIONS): GetByLabel('UI/Map/Layout/GroupByConstellations'),
 (VIEWMODE_LAYOUT_SETTINGS, VIEWMODE_LAYOUT_REGIONS): GetByLabel('UI/Map/Layout/GroupByRegions'),
 VIEWMODE_LAYOUT_SHOW_ABSTRACT_SETTINGS: GetByLabel('UI/Map/Layout/AbstractLayout'),
 (VIEWMODE_LINES_SHOW_JUMP_BRIDGES_SETTINGS, VIEWMODE_LINES_SHOW_JUMP_BRIDGES_ALL): GetByLabel('UI/Map/MapPallet/cbAllJumpBridges'),
 (VIEWMODE_LINES_SHOW_JUMP_BRIDGES_SETTINGS, VIEWMODE_LINES_SHOW_JUMP_BRIDGES_MY): GetByLabel('UI/Map/MapPallet/cbMyJumpBridges')}
MV_GROUPS_BY_ID = {VIEWMODE_LAYOUT_SETTINGS: [VIEWMODE_LAYOUT_SOLARSYSTEM, VIEWMODE_LAYOUT_CONSTELLATIONS, VIEWMODE_LAYOUT_REGIONS],
 VIEWMODE_LINES_SETTINGS: [VIEWMODE_LINES_ALL, VIEWMODE_LINES_SELECTION_REGION, VIEWMODE_LINES_SELECTION],
 VIEWMODE_LINES_SHOW_JUMP_BRIDGES_SETTINGS: [VIEWMODE_LINES_SHOW_JUMP_BRIDGES_MY, VIEWMODE_LINES_SHOW_JUMP_BRIDGES_ALL]}

def GetMapViewSetting(settingGroupKey, mapViewID):
    key = '%s_%s' % (settingGroupKey, mapViewID)
    return settings.char.ui.Get(key, DEFAULT_MAPVIEW_SETTINGS[settingGroupKey])


def SetMapViewSetting(settingGroupKey, settingValue, mapViewID):
    settings.char.ui.Set('%s_%s' % (settingGroupKey, mapViewID), settingValue)


def IsAbstractModeActive(mapViewID):
    return GetMapViewSetting(VIEWMODE_LAYOUT_SHOW_ABSTRACT_SETTINGS, mapViewID)


COLORMODE_MENU_WIDTH = 200
COLORMODE_MENU_HEIGHT = 220
