#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\eveui\keyboard.py
import carbonui.uiconst
import enum
import platform
import trinity

class Key(int, enum.Enum):

    @property
    def is_down(self):
        return trinity.app.Key(self.value)

    @staticmethod
    def ctrl_or_cmd():
        if platform.system() == 'Darwin':
            return Key.cmd
        else:
            return Key.control

    a = carbonui.uiconst.VK_A
    b = carbonui.uiconst.VK_B
    c = carbonui.uiconst.VK_C
    d = carbonui.uiconst.VK_D
    e = carbonui.uiconst.VK_E
    f = carbonui.uiconst.VK_F
    g = carbonui.uiconst.VK_G
    h = carbonui.uiconst.VK_H
    i = carbonui.uiconst.VK_I
    j = carbonui.uiconst.VK_J
    k = carbonui.uiconst.VK_K
    l = carbonui.uiconst.VK_L
    m = carbonui.uiconst.VK_M
    n = carbonui.uiconst.VK_N
    o = carbonui.uiconst.VK_O
    p = carbonui.uiconst.VK_P
    q = carbonui.uiconst.VK_Q
    r = carbonui.uiconst.VK_R
    s = carbonui.uiconst.VK_S
    t = carbonui.uiconst.VK_T
    u = carbonui.uiconst.VK_U
    v = carbonui.uiconst.VK_V
    w = carbonui.uiconst.VK_W
    x = carbonui.uiconst.VK_X
    y = carbonui.uiconst.VK_Y
    z = carbonui.uiconst.VK_Z
    one = carbonui.uiconst.VK_1
    two = carbonui.uiconst.VK_2
    three = carbonui.uiconst.VK_3
    four = carbonui.uiconst.VK_4
    five = carbonui.uiconst.VK_5
    six = carbonui.uiconst.VK_6
    seven = carbonui.uiconst.VK_7
    eight = carbonui.uiconst.VK_8
    nine = carbonui.uiconst.VK_9
    zero = carbonui.uiconst.VK_0
    f1 = carbonui.uiconst.VK_F1
    f2 = carbonui.uiconst.VK_F2
    f3 = carbonui.uiconst.VK_F3
    f4 = carbonui.uiconst.VK_F4
    f5 = carbonui.uiconst.VK_F5
    f6 = carbonui.uiconst.VK_F6
    f7 = carbonui.uiconst.VK_F7
    f8 = carbonui.uiconst.VK_F8
    f9 = carbonui.uiconst.VK_F9
    f10 = carbonui.uiconst.VK_F10
    f11 = carbonui.uiconst.VK_F11
    f12 = carbonui.uiconst.VK_F12
    f13 = carbonui.uiconst.VK_F13
    f14 = carbonui.uiconst.VK_F14
    f15 = carbonui.uiconst.VK_F15
    f16 = carbonui.uiconst.VK_F16
    f17 = carbonui.uiconst.VK_F17
    f18 = carbonui.uiconst.VK_F18
    f19 = carbonui.uiconst.VK_F19
    f20 = carbonui.uiconst.VK_F20
    f21 = carbonui.uiconst.VK_F21
    f22 = carbonui.uiconst.VK_F22
    f23 = carbonui.uiconst.VK_F23
    f24 = carbonui.uiconst.VK_F24
    space = carbonui.uiconst.VK_SPACE
    enter = carbonui.uiconst.VK_RETURN
    backspace = carbonui.uiconst.VK_BACK
    down = carbonui.uiconst.VK_DOWN
    left = carbonui.uiconst.VK_LEFT
    right = carbonui.uiconst.VK_RIGHT
    up = carbonui.uiconst.VK_UP
    control = carbonui.uiconst.VK_CONTROL
    menu = carbonui.uiconst.VK_MENU
    shift = carbonui.uiconst.VK_SHIFT
    control_left = carbonui.uiconst.VK_LCONTROL
    menu_left = carbonui.uiconst.VK_LMENU
    menu_right = carbonui.uiconst.VK_RMENU
    shift_left = carbonui.uiconst.VK_LSHIFT
    shift_right = carbonui.uiconst.VK_RSHIFT
    win_right = carbonui.uiconst.VK_RWIN
    control_right = carbonui.uiconst.VK_RCONTROL
    win_left = carbonui.uiconst.VK_LWIN
    cmd = carbonui.uiconst.VK_LWIN
    escape = carbonui.uiconst.VK_ESCAPE
    tab = carbonui.uiconst.VK_TAB
    scroll_lock = carbonui.uiconst.VK_SCROLL
    delete = carbonui.uiconst.VK_DELETE
    end = carbonui.uiconst.VK_END
    home = carbonui.uiconst.VK_HOME
    insert = carbonui.uiconst.VK_INSERT
    page_down = carbonui.uiconst.VK_NEXT
    page_up = carbonui.uiconst.VK_PRIOR
    add = carbonui.uiconst.VK_ADD
    decimal = carbonui.uiconst.VK_DECIMAL
    divide = carbonui.uiconst.VK_DIVIDE
    multiply = carbonui.uiconst.VK_MULTIPLY
    numlock = carbonui.uiconst.VK_NUMLOCK
    numpad_0 = carbonui.uiconst.VK_NUMPAD0
    numpad_1 = carbonui.uiconst.VK_NUMPAD1
    numpad_2 = carbonui.uiconst.VK_NUMPAD2
    numpad_3 = carbonui.uiconst.VK_NUMPAD3
    numpad_4 = carbonui.uiconst.VK_NUMPAD4
    numpad_5 = carbonui.uiconst.VK_NUMPAD5
    numpad_6 = carbonui.uiconst.VK_NUMPAD6
    numpad_7 = carbonui.uiconst.VK_NUMPAD7
    numpad_8 = carbonui.uiconst.VK_NUMPAD8
    numpad_9 = carbonui.uiconst.VK_NUMPAD9
    subtract = carbonui.uiconst.VK_SUBTRACT
    mouse_left = carbonui.uiconst.VK_LBUTTON
    mouse_middle = carbonui.uiconst.VK_MBUTTON
    mouse_right = carbonui.uiconst.VK_RBUTTON
    mouse_back = carbonui.uiconst.VK_XBUTTON1
    mouse_forward = carbonui.uiconst.VK_XBUTTON2
    volume_mute = carbonui.uiconst.VK_VOLUME_MUTE
    volume_down = carbonui.uiconst.VK_VOLUME_DOWN
    volume_up = carbonui.uiconst.VK_VOLUME_UP
    media_next_track = carbonui.uiconst.VK_MEDIA_NEXT_TRACK
    media_play_pause = carbonui.uiconst.VK_MEDIA_PLAY_PAUSE
    media_prev_track = carbonui.uiconst.VK_MEDIA_PREV_TRACK
    media_stop = carbonui.uiconst.VK_MEDIA_STOP
    play = carbonui.uiconst.VK_PLAY
    oem_1 = carbonui.uiconst.VK_OEM_1
    oem_102 = carbonui.uiconst.VK_OEM_102
    oem_2 = carbonui.uiconst.VK_OEM_2
    oem_3 = carbonui.uiconst.VK_OEM_3
    oem_4 = carbonui.uiconst.VK_OEM_4
    oem_5 = carbonui.uiconst.VK_OEM_5
    oem_6 = carbonui.uiconst.VK_OEM_6
    oem_7 = carbonui.uiconst.VK_OEM_7
    oem_8 = carbonui.uiconst.VK_OEM_8
    oem_clear = carbonui.uiconst.VK_OEM_CLEAR
    oem_comma = carbonui.uiconst.VK_OEM_COMMA
    oem_period = carbonui.uiconst.VK_OEM_PERIOD
    oem_plus = carbonui.uiconst.VK_OEM_PLUS
    oem_minus = carbonui.uiconst.VK_OEM_MINUS
    launch_app_1 = carbonui.uiconst.VK_LAUNCH_APP1
    launch_app_2 = carbonui.uiconst.VK_LAUNCH_APP2
    launch_mail = carbonui.uiconst.VK_LAUNCH_MAIL
    launch_media_select = carbonui.uiconst.VK_LAUNCH_MEDIA_SELECT
    browser_back = carbonui.uiconst.VK_BROWSER_BACK
    browser_favorites = carbonui.uiconst.VK_BROWSER_FAVORITES
    browser_forward = carbonui.uiconst.VK_BROWSER_FORWARD
    browser_home = carbonui.uiconst.VK_BROWSER_HOME
    browser_refresh = carbonui.uiconst.VK_BROWSER_REFRESH
    browser_search = carbonui.uiconst.VK_BROWSER_SEARCH
    browser_stop = carbonui.uiconst.VK_BROWSER_STOP
    pause_break = carbonui.uiconst.VK_PAUSE
    print_screen = carbonui.uiconst.VK_PRINT
    sleep = carbonui.uiconst.VK_SLEEP
    kana = carbonui.uiconst.VK_KANA
    hanja = carbonui.uiconst.VK_HANJA
    junja = carbonui.uiconst.VK_JUNJA
    kanji = carbonui.uiconst.VK_KANJI
    hangul = carbonui.uiconst.VK_HANGUL
    pa_1 = carbonui.uiconst.VK_PA1
    accept = carbonui.uiconst.VK_ACCEPT
    apps = carbonui.uiconst.VK_APPS
    help_key = carbonui.uiconst.VK_HELP
    select = carbonui.uiconst.VK_SELECT
    ex_sel = carbonui.uiconst.VK_EXSEL
    zoom = carbonui.uiconst.VK_ZOOM
    cancel = carbonui.uiconst.VK_CANCEL
    clear = carbonui.uiconst.VK_CLEAR
    noname = carbonui.uiconst.VK_NONAME
    attn = carbonui.uiconst.VK_ATTN
    nonconvert = carbonui.uiconst.VK_NONCONVERT
    process_key = carbonui.uiconst.VK_PROCESSKEY
    separator = carbonui.uiconst.VK_SEPARATOR
    mode_change = carbonui.uiconst.VK_MODECHANGE
    crsel = carbonui.uiconst.VK_CRSEL
    ereof = carbonui.uiconst.VK_EREOF
    packet = carbonui.uiconst.VK_PACKET
    execute = carbonui.uiconst.VK_EXECUTE
    final = carbonui.uiconst.VK_FINAL
    convert = carbonui.uiconst.VK_CONVERT
    capital = carbonui.uiconst.VK_CAPITAL
    snapshot = carbonui.uiconst.VK_SNAPSHOT
