#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\jumpFatigue\const.py
ADDITIONAL_DISTANCE = 1.0
ACTIVATION_SECONDS_PER_DISTANCE = 60
FATIGUE_SECONDS_PER_DISTANCE = 600
FATIGUE_MAX_SECONDS = 18000
FATIGUE_RATIO = float(ACTIVATION_SECONDS_PER_DISTANCE) / FATIGUE_SECONDS_PER_DISTANCE
