#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\voidspace\common\constants.py
from carbon.common.lib.const import MIN
FILAMENT_PROXIMITY_RESTRICTION_RANGE = 1000000
FILAMENT_PROXIMITY_RESTRICTION_LIST_ID = 50
VOID_SPACE_COLLAPSE_NOTIFICATION_TIMERS_SECONDS = [300, 120, 30]
ACTIVATION_ERROR_DELAY = 4000
ACTIVATION_PICKUP_DISTANCE = 6000
VOID_SPACE_JUMP_DELAY_SECONDS = 8
VOID_SPACE_JUMP_DELAY = VOID_SPACE_JUMP_DELAY_SECONDS * 1000
VOID_SPACE_ENCOUNTER_LIFE_TIME = 30 * MIN
CONTENT_EXPIRY_DURATION_SLEEP_SECONDS = VOID_SPACE_JUMP_DELAY_SECONDS
