#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\menuUtil.py
from brennivin.itertoolsext import Bundle
from eve.client.script.ui import eveColor
CONTACTSGROUP = (1, 0)
TRADEGROUP = (2, 0)
CONTAINERGROUPS = (3, 0)
CHANGESGROUP = (4, 0)
DESTRUCTIVEGROUP = (5, 0)
SELECTIONGROUP = (6, 0)
SHOWINFOGROUP = (7, 0)
GMWMEXTRAS = (8, 0)
SUBGROUP1 = (9, 0)
ACTIONSGROUP = (11, 0)
CORPGROUP = (12, 0)
RAGEQUITGROUP = (13, 0)
FLEETGROUP = (14, 0)
CONFIGGROUP = (16, 0)
NAVIGATIONGROUP2 = (15, 0)
SHIPSPECIALGROUP = (17, 0)
CONTACTSGROUP2 = (18, 0)
ACTIONSGROUP2 = (19, 0)
BLUEPRINTGROUP = (20, 0)
BOTTOMGROUP = (21, 0)
RED_WARNING = 4291559424L
YELLOW_WARNING = 4291611648L
menuGroupsFromCaption = {'UI/PeopleAndPlaces/AddAllianceContact': CONTACTSGROUP,
 'UI/PeopleAndPlaces/AddContact': CONTACTSGROUP,
 'UI/PeopleAndPlaces/AddCorpContact': CONTACTSGROUP,
 'UI/PeopleAndPlaces/AddToAddressbook': CONTACTSGROUP,
 'UI/PeopleAndPlaces/BlockContact': CONTACTSGROUP,
 'UI/PeopleAndPlaces/Blocked': CONTACTSGROUP,
 'UI/PeopleAndPlaces/RemoveCorpContact': CONTACTSGROUP,
 'UI/PeopleAndPlaces/RemoveAllianceContact': CONTACTSGROUP,
 'UI/PeopleAndPlaces/RemoveFromAddressbook': CONTACTSGROUP,
 'UI/PeopleAndPlaces/RemoveContact': CONTACTSGROUP,
 'UI/Mail/LabelRemove': CONTACTSGROUP,
 'UI/Mail/AssignLabel': CONTACTSGROUP,
 'UI/PeopleAndPlaces/EditAllianceContact': CONTACTSGROUP,
 'UI/PeopleAndPlaces/EditContact': CONTACTSGROUP,
 'UI/PeopleAndPlaces/EditCorpContact': CONTACTSGROUP,
 'UI/Fleet/FormFleetWith': CONTACTSGROUP2,
 'UI/Commands/CapturePortrait': CONTACTSGROUP2,
 'UI/Chat/StartConversation': CONTACTSGROUP2,
 'UI/Chat/InviteToChat': CONTACTSGROUP2,
 'UI/EVEMail/SendPilotEVEMail': CONTACTSGROUP2,
 'UI/Inventory/ItemActions/BuyThisType': TRADEGROUP,
 'UI/Market/Marketbase/CommandPlaceBuyOrder': TRADEGROUP,
 'UI/Contracts/ContractEntry/IgnoreFromThisIssuer': TRADEGROUP,
 'UI/Inventory/ItemActions/SellThisItem': TRADEGROUP,
 'UI/Inventory/ItemActions/MultiSell': TRADEGROUP,
 'UI/Market/MarketQuote/BuyAll': TRADEGROUP,
 'UI/Market/TradeWithCharacter': TRADEGROUP,
 'UI/Wallet/WalletWindow/MenuTransferFromCorp': TRADEGROUP,
 'UI/Wallet/WalletWindow/MenuTransferToCorp': TRADEGROUP,
 'UI/Inflight/POS/TransferSovStructureOwnership': TRADEGROUP,
 'UI/Inventory/ItemActions/ViewTypesMarketDetails': TRADEGROUP,
 'UI/Inventory/ItemActions/FindInContracts': TRADEGROUP,
 'UI/Inventory/ItemActions/FindPersonalAssets': TRADEGROUP,
 'UI/Corporations/Common/ViewCorpMemberDetails': TRADEGROUP,
 'UI/Wallet/WalletWindow/MenuViewTransactions': TRADEGROUP,
 'UI/Inventory/ItemActions/AddTypeToMarketQuickbar': TRADEGROUP,
 'UI/Inventory/ItemActions/CreateContract': TRADEGROUP,
 'UI/Inventory/ItemActions/DeliverTo': TRADEGROUP,
 'UI/Commands/GiveMoney': TRADEGROUP,
 'UI/Inflight/POS/AccessPOSActiveCrystal': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSAmmo': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSCrystalStorage': CONTAINERGROUPS,
 'UI/PI/Common/AccessCustomOffice': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSFuelBay': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSRefinery': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSCompression': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSResources': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSStorage': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSStrontiumBay': CONTAINERGROUPS,
 'UI/Inflight/POS/AccessPOSVessels': CONTAINERGROUPS,
 'UI/Commands/OpenAmmoHold': CONTAINERGROUPS,
 'UI/Commands/OpenCargo': CONTAINERGROUPS,
 'UI/Commands/OpenCargoHold': CONTAINERGROUPS,
 'UI/Inventory/ItemActions/OpenContainer': CONTAINERGROUPS,
 'UI/Commands/OpenFleetHangar': CONTAINERGROUPS,
 'UI/Commands/OpenDescription': CONTAINERGROUPS,
 'UI/Commands/OpenDroneBay': CONTAINERGROUPS,
 'UI/Commands/OpenFighterBay': CONTAINERGROUPS,
 'UI/Commands/OpenFrigateEscapeBay': CONTAINERGROUPS,
 'UI/Commands/OpenFuelBay': CONTAINERGROUPS,
 'UI/Commands/OpenGasHold': CONTAINERGROUPS,
 'UI/Commands/OpenIndustrialShipHold': CONTAINERGROUPS,
 'UI/Commands/OpenLargeShipHold': CONTAINERGROUPS,
 'UI/Commands/OpenMediumShipHold': CONTAINERGROUPS,
 'UI/Commands/OpenMineralHold': CONTAINERGROUPS,
 'UI/Commands/OpenMyCargo': CONTAINERGROUPS,
 'UI/Commands/OpenGeneralMiningHold': CONTAINERGROUPS,
 'UI/PI/Common/OpenPlanetaryCommoditiesHold': CONTAINERGROUPS,
 'UI/Commands/OpenSalvageHold': CONTAINERGROUPS,
 'UI/Commands/OpenShipHold': CONTAINERGROUPS,
 'UI/Commands/OpenShipMaintenanceBay': CONTAINERGROUPS,
 'UI/Commands/OpenSmallShipHold': CONTAINERGROUPS,
 'UI/Commands/OpenQuafeBay': CONTAINERGROUPS,
 'UI/Commands/OpenCorpseBay': CONTAINERGROUPS,
 'UI/Commands/OpenBoosterBay': CONTAINERGROUPS,
 'UI/Commands/OpenSubsystemBay': CONTAINERGROUPS,
 'UI/Commands/OpenMobileDepotHold': CONTAINERGROUPS,
 'UI/Commands/OpenInfrastructureHold': CONTAINERGROUPS,
 'UI/Inflight/POS/StoreVesselInSMA': CONTAINERGROUPS,
 'UI/Inventory/ItemActions/ViewContents': CONTAINERGROUPS,
 'UI/Commands/OpenCommandCenterHold': CONTAINERGROUPS,
 'UI/Corporations/BaseCorporationUI/Take': CONTAINERGROUPS,
 'UI/Inflight/SpaceComponents/ItemTrader/Access': CONTAINERGROUPS,
 'UI/Inflight/SpaceComponents/UnderConstruction/Access': CONTAINERGROUPS,
 'UI/OrbitalSkyhook/SkyhookWnd/AccessOrbitalSkyhookOffice': CONTAINERGROUPS,
 'UI/Sovereignty/SovHub/ReagentBay/DepositReagents': CONTAINERGROUPS,
 'UI/Sovereignty/MercenaryDen/ConfigurationWindow/ConfigureMercenaryDen': CONTAINERGROUPS,
 'UI/Inflight/POS/CancelAnchoring': CHANGESGROUP,
 'UI/Corporations/CorporationWindow/Wars/CancelMutualMenuOption': CHANGESGROUP,
 'UI/Market/Orders/CancelOrder': CHANGESGROUP,
 'UI/Neocom/Petition/CancelPetition': CHANGESGROUP,
 'UI/Inflight/menuCancelRepair': CHANGESGROUP,
 'UI/Inflight/menuCancelAllRepairs': CHANGESGROUP,
 'UI/Inflight/MoonMining/Processes/ChangeHarvestedMaterial': CHANGESGROUP,
 '/Carbon/UI/Controls/ScrollEntries/ChangeLabel': CHANGESGROUP,
 'UI/Market/TickerRemoveAsMarketTickerFolder': CHANGESGROUP,
 'UI/Market/TickerSetAsMarketTickerFolder': CHANGESGROUP,
 'UI/Commands/ChangeName': CHANGESGROUP,
 'UI/Inflight/MoonMining/Processes/ChangeSiloType': CHANGESGROUP,
 'UI/Corporations/CorporationWindow/Wars/DeclareMutualMenuOption': CHANGESGROUP,
 'UI/Drones/DelegateDroneControl': CHANGESGROUP,
 'UI/Fleet/FleetWindow/EditAdvert': CHANGESGROUP,
 'UI/Inflight/Scanner/EditCurrentFilter': CHANGESGROUP,
 'UI/Neocom/Petition/Escalate': CHANGESGROUP,
 'UI/Chat/ChannelWindow/ForgetChannel': CHANGESGROUP,
 'UI/Chat/ChannelWindow/ForgetList': CHANGESGROUP,
 'UI/Inflight/Scanner/IgnoreOtherResults': CHANGESGROUP,
 'UI/Inflight/Scanner/IngoreResult': CHANGESGROUP,
 'UI/Chat/LeaveAudio': CHANGESGROUP,
 'UI/Chat/ChannelWindow/LeaveChannel': CHANGESGROUP,
 'UI/Mail/LeaveMailingList': CHANGESGROUP,
 'UI/Fleet/Watchlist/LeavePrivateVoiceChannel': CHANGESGROUP,
 'UI/Inventory/ItemActions/LeaveShip': CHANGESGROUP,
 'UI/Commands/MoveDrone': CHANGESGROUP,
 'UI/Drones/MoveToDroneBay': CHANGESGROUP,
 'UI/PeopleAndPlaces/LabelsRename': CHANGESGROUP,
 'UI/Notepad/RenameNote': CHANGESGROUP,
 'UI/Corporations/CorporationWindow/Wars/RetractMenuOption': CHANGESGROUP,
 'UI/Drones/ReturnDroneAndOrbit': CHANGESGROUP,
 'UI/Drones/ReturnDroneControl': CHANGESGROUP,
 'UI/Drones/ReturnDroneToBay': CHANGESGROUP,
 'UI/Inflight/ScoopToCargoHold': CHANGESGROUP,
 'UI/Inflight/ScoopToFleetHangar': CHANGESGROUP,
 'UI/Drones/ScoopDroneToBay': CHANGESGROUP,
 'UI/Inflight/POS/ScoopToShipMaintenanceBay': CHANGESGROUP,
 'UI/Neocom/Petition/ClosePetition': CHANGESGROUP,
 'UI/Neocom/Petition/Delete': CHANGESGROUP,
 'UI/PeopleAndPlaces/UnblockContact': CHANGESGROUP,
 'UI/Inflight/EditBookmark': CHANGESGROUP,
 'UI/Overview/RemoveGroupFromOverview': CHANGESGROUP,
 'UI/Station/BountyOffice/PlaceBounty': CHANGESGROUP,
 'UI/Inflight/ScoopToFighterBay': CHANGESGROUP,
 'UI/Inflight/AbandonAllCargo': DESTRUCTIVEGROUP,
 'UI/Inflight/AbandonAllWrecks': DESTRUCTIVEGROUP,
 'UI/Inflight/AbandonCargo': DESTRUCTIVEGROUP,
 'UI/Drones/AbandonDrone': DESTRUCTIVEGROUP,
 'UI/Inflight/AbandonWreack': DESTRUCTIVEGROUP,
 'UI/Inventory/Fighters/AbandonFighter': DESTRUCTIVEGROUP,
 'UI/Accessories/Calculator/Clear': DESTRUCTIVEGROUP,
 'UI/Inflight/Scanner/ClearAllIgnoredResults': DESTRUCTIVEGROUP,
 'UI/Map/Navigation/menuClearWaypoints': DESTRUCTIVEGROUP,
 'UI/Fitting/ClearGroup': DESTRUCTIVEGROUP,
 'UI/Inflight/Scanner/ClearIgnoredResult': DESTRUCTIVEGROUP,
 'UI/Inflight/Scanner/ClearResult': DESTRUCTIVEGROUP,
 'UI/Map/Navigation/menuClearRoute': DESTRUCTIVEGROUP,
 '/Carbon/UI/Common/Close': DESTRUCTIVEGROUP,
 'UI/Mail/EmptyTrash': DESTRUCTIVEGROUP,
 'UI/CharacterSelection/RemoveFromBiomass': DESTRUCTIVEGROUP,
 'UI/Generic/RemoveItem': DESTRUCTIVEGROUP,
 'UI/Notepad/RemoveNote': DESTRUCTIVEGROUP,
 'UI/Agents/Commands/RemoveOffer': DESTRUCTIVEGROUP,
 'UI/Inventory/ItemActions/Repackage': DESTRUCTIVEGROUP,
 'UI/Chat/ReportIskSpammer': DESTRUCTIVEGROUP,
 'UI/Corporations/Assets/TrashItemsAtLocation': DESTRUCTIVEGROUP,
 'UI/Chat/ChannelWindow/UnsubscribeFromList': DESTRUCTIVEGROUP,
 'UI/Inventory/ItemActions/Jettison': DESTRUCTIVEGROUP,
 'UI/Fleet/Ranks/Boss': DESTRUCTIVEGROUP,
 'UI/Inflight/JumpToFleetMember': DESTRUCTIVEGROUP,
 'UI/Fleet/ConduitJumpToFleetMember': DESTRUCTIVEGROUP,
 'UI/Inventory/ItemActions/LaunchShip': DESTRUCTIVEGROUP,
 'UI/Inventory/ItemActions/LaunchShipFromBay': DESTRUCTIVEGROUP,
 'UI/Inventory/ItemActions/LaunchForCorp': DESTRUCTIVEGROUP,
 'UI/Inventory/ItemActions/LaunchForSelf': DESTRUCTIVEGROUP,
 'UI/Commands/UndockFromStation': DESTRUCTIVEGROUP,
 'UI/Inventory/ItemActions/StripFitting': DESTRUCTIVEGROUP,
 'UI/InfoWindow/ReportBot': DESTRUCTIVEGROUP,
 'UI/Corporations/CorpApplications/WithdrawApplication': DESTRUCTIVEGROUP,
 'UI/CharacterSheet/CharacterSheetWindow/JumpCloneScroll/Destroy': DESTRUCTIVEGROUP,
 'UI/Chat/ClearAllContent': DESTRUCTIVEGROUP,
 'UI/Inflight/SafeLogoff': DESTRUCTIVEGROUP,
 'UI/Inflight/ModuleRacks/PutModuleOffline': DESTRUCTIVEGROUP,
 'UI/AclBookmarks/DeleteBookmarkFolder': DESTRUCTIVEGROUP,
 'UI/AclBookmarks/ForgetBookmarkFolder': DESTRUCTIVEGROUP,
 'UI/AclBookmarks/DeleteSubfolder': DESTRUCTIVEGROUP,
 'UI/Overview/DeleteTab': DESTRUCTIVEGROUP,
 'UI/Overview/DeletePreset': DESTRUCTIVEGROUP,
 'UI/Inflight/RemoveWaypoint': DESTRUCTIVEGROUP,
 'UI/Sovereignty/SovHub/TransitionToSovHub': DESTRUCTIVEGROUP,
 'UI/CharacterSelection/CompleteTermination': RAGEQUITGROUP,
 'UI/Fleet/MakeFleetLeader': RAGEQUITGROUP,
 'UI/PeopleAndPlaces/DeleteNotification': RAGEQUITGROUP,
 'UI/Notepad/DeleteNote': RAGEQUITGROUP,
 'UI/Chat/ChannelWindow/DeleteChannel': RAGEQUITGROUP,
 'UI/Mail/Delete': RAGEQUITGROUP,
 '/Carbon/UI/Controls/ScrollEntries/DeleteFolder': RAGEQUITGROUP,
 'UI/Commands/DeleteGroup': RAGEQUITGROUP,
 'UI/Chat/ChannelWindow/DeleteList': RAGEQUITGROUP,
 'UI/Mail/DeleteMailingList': RAGEQUITGROUP,
 'UI/Mail/Notifications/DeleteAll': RAGEQUITGROUP,
 'UI/Common/Delete': RAGEQUITGROUP,
 'UI/Contracts/ContractEntry/Delete': RAGEQUITGROUP,
 'UI/Contracts/ContractEntry/Dismiss': RAGEQUITGROUP,
 'UI/Corporations/Common/ExpelCorpMember': RAGEQUITGROUP,
 'UI/Fleet/KickFleetMember': RAGEQUITGROUP,
 'UI/Inflight/PutStructureOffline': RAGEQUITGROUP,
 'UI/Corporations/Common/QuitCorp': RAGEQUITGROUP,
 'UI/Inflight/POS/RelinquishPOSControl': RAGEQUITGROUP,
 'UI/Commands/Remove': RAGEQUITGROUP,
 'UI/Fleet/FleetWindow/RemoveAdvert': RAGEQUITGROUP,
 'UI/Inflight/MoonMining/Processes/RemoveConnection': RAGEQUITGROUP,
 'UI/Inventory/ItemActions/RemoveTypeFromMarketQuickbar': RAGEQUITGROUP,
 'UI/Fleet/RemovePilotFromWatchlist': RAGEQUITGROUP,
 'UI/Inventory/ItemActions/Reprocess': RAGEQUITGROUP,
 'UI/Corporations/Common/ResignAsCEO': RAGEQUITGROUP,
 'UI/Inflight/SelfDestructShipOrPod': RAGEQUITGROUP,
 'UI/Inflight/AbortSelfDestruct': RAGEQUITGROUP,
 'UI/CharacterSelection/Terminate': RAGEQUITGROUP,
 'UI/Mail/Trash': RAGEQUITGROUP,
 'UI/Mail/TrashAll': RAGEQUITGROUP,
 'UI/Inventory/ItemActions/TrashIt': RAGEQUITGROUP,
 'UI/Inflight/UnanchorObject': RAGEQUITGROUP,
 'UI/Inflight/POS/UnanchorStructure': RAGEQUITGROUP,
 'UI/Control/Entries/ImplantUnplug': RAGEQUITGROUP,
 'UI/Inflight/EjectFromShip': RAGEQUITGROUP,
 'UI/Contracts/BreakContract': RAGEQUITGROUP,
 'Remove from Selection': RAGEQUITGROUP,
 'UI/Crimewatch/Duel/DuelMenuEntry': RAGEQUITGROUP,
 'UI/StructureBrowser/DeleteProfile': RAGEQUITGROUP,
 'UI/HelpPointers/Wnd/DeleteGroup': RAGEQUITGROUP,
 'UI/CharacterSheet/CharacterSheetWindow/ExpertSystems/RemoveExpertSystem': RAGEQUITGROUP,
 'UI/Commands/CmdUnlockTargetItems': RAGEQUITGROUP,
 'UI/Fleet/Watchlist/ClearWatchList': RAGEQUITGROUP,
 '/Carbon/UI/Controls/Common/ClearHistory': RAGEQUITGROUP,
 'UI/Fitting/FittingWindow/FittingManagement/DeleteFitting': RAGEQUITGROUP,
 'UI/Fleet/LeaveMyFleet': RAGEQUITGROUP,
 'UI/Fleet/DisbandFleet': RAGEQUITGROUP,
 'UI/Inflight/RemoveBookmark': RAGEQUITGROUP,
 'UI/Common/Copy': SELECTIONGROUP,
 'UI/Common/CopyTooltip': SELECTIONGROUP,
 '/Carbon/UI/Controls/Common/Copy': SELECTIONGROUP,
 'UI/Common/CopyAll': SELECTIONGROUP,
 'UI/Browser/CopyImageLocation': SELECTIONGROUP,
 'UI/Browser/CopyLinkLocation': SELECTIONGROUP,
 '/Carbon/UI/Controls/Common/CopySelected': SELECTIONGROUP,
 '/Carbon/UI/Controls/Common/CopySelectedWithoutFormatting': SELECTIONGROUP,
 '/Carbon/UI/Controls/Common/CopySelectedWithFormatting': SELECTIONGROUP,
 '/Carbon/UI/Commands/CopyURL': SELECTIONGROUP,
 'UI/Common/Cut': SELECTIONGROUP,
 '/Carbon/UI/Controls/Common/Cut': SELECTIONGROUP,
 '/Carbon/UI/Controls/Common/CutSelected': SELECTIONGROUP,
 '/Carbon/UI/Controls/Common/Paste': SELECTIONGROUP,
 'UI/Common/SelectAll': SELECTIONGROUP,
 'UI/Inventory/StackAll': SELECTIONGROUP,
 'UI/Common/SortBy': SELECTIONGROUP,
 'UI/Inventory/InvertSelection': SELECTIONGROUP,
 'UI/Chat/ToggleTimestamp': SELECTIONGROUP,
 'UI/Inflight/MoonMiningPoint': BOTTOMGROUP,
 'gm / wm extras': GMWMEXTRAS,
 'refresh': GMWMEXTRAS,
 'inactive': GMWMEXTRAS,
 'UI/Commands/Refresh': GMWMEXTRAS,
 'UI/Commands/ShowInfo': SHOWINFOGROUP,
 'UI/Common/Character': SUBGROUP1,
 'UI/Common/Planets': SUBGROUP1,
 'UI/Common/LocationTypes/Planets': SUBGROUP1,
 'UI/Common/LocationTypes/Stargates': SUBGROUP1,
 'UI/Common/LocationTypes/Stations': SUBGROUP1,
 'UI/Common/LocationTypes/AsteroidBelts': SUBGROUP1,
 'UI/Common/Pilot': SUBGROUP1,
 'UI/Fleet/Fleet': SUBGROUP1,
 'UI/Common/Location': SUBGROUP1,
 'UI/Common/LocationTypes/Structures': SUBGROUP1,
 'UI/Inflight/Scanner/AnomalySiteFilterLabel': SUBGROUP1,
 'UI/Menusvc/MoonsMenuOption': SUBGROUP1,
 'UI/PI/Common/CustomsOffice': SUBGROUP1,
 'UI/Common/LocationTypes/MercenaryTacticalOperations': SUBGROUP1,
 'UI/Inflight/OrbitObject': ACTIONSGROUP,
 'UI/Inflight/Submenus/WarpToWithin': ACTIONSGROUP,
 'UI/Inflight/Submenus/KeepAtRange': ACTIONSGROUP,
 'UI/Inflight/ApproachObject': ACTIONSGROUP,
 'UI/Inflight/LookAtObject': ACTIONSGROUP,
 'UI/Inflight/SetAsCameraInterest': ACTIONSGROUP,
 'UI/Inflight/ActivateAutopilot': ACTIONSGROUP,
 'UI/Inflight/DeactivateAutopilot': ACTIONSGROUP,
 'UI/Inflight/StopMyShip': ACTIONSGROUP,
 'UI/Inflight/AlignTo': ACTIONSGROUP,
 'UI/Inflight/ResetCamera': ACTIONSGROUP,
 'UI/Inflight/BoardShip': ACTIONSGROUP,
 'UI/Inventory/ItemActions/AssembleShip': ACTIONSGROUP,
 'UI/Fleet/WarpToMember': ACTIONSGROUP,
 'UI/Inflight/Jump': ACTIONSGROUP,
 'UI/Inflight/JumpUsingBridge': ACTIONSGROUP,
 'UI/Inflight/JumpThroughStargate': ACTIONSGROUP,
 'UI/Inflight/JumpThroughJumpgate': ACTIONSGROUP,
 'UI/Inflight/JumpByShipcaster': ACTIONSGROUP,
 'UI/Inflight/JumpByShipcasterToSystem': ACTIONSGROUP,
 'UI/Inflight/DockInStation': ACTIONSGROUP,
 'UI/Fleet/WarpToMemberSubmenuOption': ACTIONSGROUP,
 'UI/Inflight/ModuleRacks/ReloadAll': ACTIONSGROUP,
 'UI/Drones/EngageTarget': ACTIONSGROUP,
 'UI/Drones/Salvage': ACTIONSGROUP,
 'UI/Drones/MineWithDrone': ACTIONSGROUP,
 'UI/Inflight/LockTarget': ACTIONSGROUP,
 'UI/Inflight/UnlockTarget': ACTIONSGROUP,
 'UI/Market/Marketbase/BuyThis': ACTIONSGROUP,
 'UI/VirtualGoodsStore/BuyItem': ACTIONSGROUP,
 'UI/Market/Orders/ModifyOrder': ACTIONSGROUP,
 'UI/Inflight/ActivateGate': ACTIONSGROUP,
 'UI/Contracts/ContractEntry/ViewContract': ACTIONSGROUP,
 'UI/Inflight/ApproachLocationActionGroup': ACTIONSGROUP,
 'UI/Inflight/WarpToBookmarkWithinDistance': ACTIONSGROUP,
 'UI/Inflight/WarpToBookmark': ACTIONSGROUP,
 'UI/Inflight/WarpToWithinDistance': ACTIONSGROUP,
 'UI/Inflight/WarpToMoonMiningPoint': ACTIONSGROUP,
 'UI/Inflight/ModuleRacks/ReloadUsed': ACTIONSGROUP,
 'UI/Inflight/ModuleRacks/AmmoTypeAndStatus': ACTIONSGROUP,
 'UI/Inflight/ModuleRacks/AmmoTypeAndQuantity': ACTIONSGROUP,
 'UI/Drones/LaunchDrones': ACTIONSGROUP,
 'UI/Drones/LaunchDrone': ACTIONSGROUP,
 'UI/Fitting/FittingWindow/SimulateShipFitting': ACTIONSGROUP,
 'UI/Fitting/FittingWindow/SimulateShip': ACTIONSGROUP,
 'UI/Inventory/ItemActions/FitToActiveShip': ACTIONSGROUP2,
 'UI/Inflight/PutStructureOnline': ACTIONSGROUP2,
 'UI/Inflight/POS/AssumeStructureControl': ACTIONSGROUP2,
 'UI/Inventory/ItemActions/AssembleContainer': ACTIONSGROUP2,
 'UI/Commands/EnterHangar': ACTIONSGROUP2,
 'UI/Neocom/CqBtn': ACTIONSGROUP2,
 'UI/Inventory/ItemActions/GetRepairQuote': ACTIONSGROUP2,
 'UI/Insurance/InsuranceWindow/Commands/Insure': ACTIONSGROUP2,
 'UI/Inventory/ItemActions/ConsumeBooster': ACTIONSGROUP2,
 'UI/Inventory/ItemActions/PlugInImplant': ACTIONSGROUP2,
 'UI/Inflight/Scanner/ProbeScanner': ACTIONSGROUP2,
 'UI/Inflight/ModuleRacks/Reload': ACTIONSGROUP,
 'UI/Inventory/Fighters/LaunchToSpace': ACTIONSGROUP2,
 'UI/Inventory/Fighters/UnloadFromLaunchTube': ACTIONSGROUP2,
 'UI/Inventory/Fighters/RecallToLaunchTube': ACTIONSGROUP2,
 'UI/Inflight/BoardStructure': ACTIONSGROUP2,
 'UI/HelpPointers/Wnd/AddGroup': ACTIONSGROUP2,
 'UI/Inflight/SpaceComponents/LinkWithShip/BeginLink': ACTIONSGROUP2,
 'UI/Inflight/SpaceComponents/LinkWithShip/BeginLinkSkyhook': ACTIONSGROUP2,
 'UI/Chat/StartConversationAgent': ACTIONSGROUP2,
 'UI/PI/Common/ViewInPlanetMode': NAVIGATIONGROUP2,
 'UI/Inflight/AddWaypoint': NAVIGATIONGROUP2,
 'UI/Inflight/AddFirstWaypoint': NAVIGATIONGROUP2,
 'UI/Inflight/BookmarkLocation': NAVIGATIONGROUP2,
 'UI/Inflight/ApproachLocation': NAVIGATIONGROUP2,
 'UI/PeopleAndPlaces/EditViewLocation': NAVIGATIONGROUP2,
 'UI/Inflight/ShowSystemInMapBrowser': NAVIGATIONGROUP2,
 'UI/Commands/ShowLocationOnMap': NAVIGATIONGROUP2,
 'UI/Inflight/SetDestination': NAVIGATIONGROUP2,
 'UI/Inflight/SetDestinationToSystem': NAVIGATIONGROUP2,
 'UI/Overview/AddGroupToOverview': NAVIGATIONGROUP2,
 'UI/Overview/ToggleOverviewVisibilty': NAVIGATIONGROUP2,
 'UI/Inflight/ShowInMapBrowser': NAVIGATIONGROUP2,
 'UI/Inflight/StopAvoidingLocation': NAVIGATIONGROUP2,
 'UI/Inflight/AvoidLocation': NAVIGATIONGROUP2,
 'UI/Corporations/Common/EditCorpMember': CORPGROUP,
 'UI/Corporations/Common/TransferCorpCash': CORPGROUP,
 'UI/Corporations/Common/AwardCorpMemberDecoration': CORPGROUP,
 'UI/Corporations/Common/SendInvite': CORPGROUP,
 'UI/Commands/SetName': CONFIGGROUP,
 'UI/Commands/ConfigureShipCloneFacility': CONFIGGROUP,
 'UI/Inflight/Submenus/BridgeTo': CONFIGGROUP,
 'UI/Fleet/BridgeToMember': CONFIGGROUP,
 'UI/Inventory/ItemActions/SetNewPasswordForContainer': CONFIGGROUP,
 'UI/Inflight/POS/SetNewPasswordForForceField': CONFIGGROUP,
 'UI/Inventory/ItemActions/SetNewConfigPasswordForContainer': CONFIGGROUP,
 'UI/Inventory/ItemActions/ConfigureALSContainer': CONFIGGROUP,
 'UI/Commands/RetrievePassword': CONFIGGROUP,
 'UI/Inflight/POS/ManageControlTower': CONFIGGROUP,
 'UI/Commands/EditProfileForStructure': CONFIGGROUP,
 'UI/StructureBrowser/SetReinforcementTime': CONFIGGROUP,
 'UI/StructureBrowser/SetReinforcementTimeDockable': CONFIGGROUP,
 'UI/StructureBrowser/SetReinforcementTimeNonDockable': CONFIGGROUP,
 'UI/StructureBrowser/SetProfileMany': CONFIGGROUP,
 'UI/StructureBrowser/SetProfile': CONFIGGROUP,
 'UI/StructureBrowser/SetStructureDescription': CONFIGGROUP,
 'UI/Menusvc/OpenSovHubConfigWindow': CONFIGGROUP,
 'UI/Fitting/UseFittingService': SHIPSPECIALGROUP,
 'UI/Inflight/Submenus/JumpTo': SHIPSPECIALGROUP,
 'UI/Inflight/Submenus/ConduitJumpTo': SHIPSPECIALGROUP,
 'UI/Inflight/POS/EnterStarbasePassword': SHIPSPECIALGROUP,
 'UI/CapitalNavigation/CapitalNavigationWindow/OpenJumpNavigation': SHIPSPECIALGROUP,
 'UI/Fleet/WarpFleet': FLEETGROUP,
 'UI/Fleet/WarpFleetToLocation': FLEETGROUP,
 'UI/Fleet/WarpFleetToMember': FLEETGROUP,
 'UI/Fleet/WarpSquad': FLEETGROUP,
 'UI/Fleet/WarpSquadToLocation': FLEETGROUP,
 'UI/Fleet/WarpSquadToMember': FLEETGROUP,
 'UI/Fleet/WarpWing': FLEETGROUP,
 'UI/Fleet/WarpWingToLocation': FLEETGROUP,
 'UI/Fleet/WarpWingToMember': FLEETGROUP,
 'UI/Fleet/FleetSubmenus/WarpWingToMember': FLEETGROUP,
 'UI/Fleet/FleetSubmenus/WarpWingToWithin': FLEETGROUP,
 'UI/Fleet/FleetSubmenus/WarpSquadToMember': FLEETGROUP,
 'UI/Fleet/FleetSubmenus/WarpSquadToWithin': FLEETGROUP,
 'UI/Fleet/FleetSubmenus/WarpSquadToLocationWithin': FLEETGROUP,
 'UI/Fleet/FleetSubmenus/WarpFleetToMember': FLEETGROUP,
 'UI/Fleet/FleetSubmenus/WarpFleetToWithin': FLEETGROUP,
 'UI/Fleet/FleetSubmenus/WarpFleetToLocationWithin': FLEETGROUP,
 'UI/Fleet/JumpThroughToSystem': FLEETGROUP,
 'UI/Fleet/WarpWingToLocationWithinDistance': FLEETGROUP,
 'UI/Fleet/WarpSquadToLocationWithinDistance': FLEETGROUP,
 'UI/Fleet/WarpFleetToLocationWithinDistance': FLEETGROUP,
 'UI/Inflight/JumpThroughError': FLEETGROUP,
 'UI/ScienceAndIndustry/ScienceAndIndustryWindow/Filters/AllActivities': BLUEPRINTGROUP,
 'UI/ScienceAndIndustry/ScienceAndIndustryWindow/Filters/Manufacturing': BLUEPRINTGROUP,
 'UI/ScienceAndIndustry/ScienceAndIndustryWindow/Filters/MaterialResearch': BLUEPRINTGROUP,
 'UI/ScienceAndIndustry/ScienceAndIndustryWindow/Filters/TimeEfficiencyResearch': BLUEPRINTGROUP,
 'UI/ScienceAndIndustry/ScienceAndIndustryWindow/Filters/Copying': BLUEPRINTGROUP,
 'UI/ScienceAndIndustry/ScienceAndIndustryWindow/Filters/Duplicating': BLUEPRINTGROUP,
 'UI/ScienceAndIndustry/ScienceAndIndustryWindow/Filters/Technology': BLUEPRINTGROUP,
 'UI/ScienceAndIndustry/ScienceAndIndustryWindow/Filters/Invention': BLUEPRINTGROUP}
menuHierarchy = [GMWMEXTRAS,
 ACTIONSGROUP,
 SHOWINFOGROUP,
 ACTIONSGROUP2,
 FLEETGROUP,
 SHIPSPECIALGROUP,
 NAVIGATIONGROUP2,
 SUBGROUP1,
 CONFIGGROUP,
 CONTAINERGROUPS,
 TRADEGROUP,
 CHANGESGROUP,
 CONTACTSGROUP,
 CONTACTSGROUP2,
 None,
 BLUEPRINTGROUP,
 CORPGROUP,
 DESTRUCTIVEGROUP,
 RAGEQUITGROUP,
 SELECTIONGROUP,
 BOTTOMGROUP]
ICON_DATA_BY_MENUGROUPID = {SHOWINFOGROUP: ('res:/UI/Texture/classes/Menu/Icons/info.png', 'res:/UI/Texture/classes/Menu/Icons/circleBG.png', eveColor.CRYO_BLUE),
 RAGEQUITGROUP: ('res:/UI/Texture/classes/Menu/Icons/exclamationMark.png', 'res:/UI/Texture/classes/Menu/Icons/triangleBG.png', eveColor.HOT_RED),
 DESTRUCTIVEGROUP: ('res:/UI/Texture/classes/Menu/Icons/exclamationMark.png', 'res:/UI/Texture/classes/Menu/Icons/circleBG.png', eveColor.WARNING_ORANGE),
 GMWMEXTRAS: ('res:/UI/Texture/classes/Menu/Icons/play.png', 'res:/UI/Texture/classes/Menu/Icons/circleBG.png', eveColor.GUNMETAL_GREY)}

def GetGroupIconData(menuGroupID):
    iconTexturePath, bgTexturePath, bgColor = ICON_DATA_BY_MENUGROUPID[menuGroupID]
    return (iconTexturePath, bgTexturePath, bgColor)


def GetMenuGroup(caption, *args):
    group = menuGroupsFromCaption.get(caption, None)
    return group


def GetInfoForMenuGroupMarker(groupID):
    if groupID == RAGEQUITGROUP:
        return Bundle(marker='! ', color=RED_WARNING)
    if groupID == DESTRUCTIVEGROUP:
        return Bundle(marker='! ', color=YELLOW_WARNING)


import carbon.common.script.util.autoexport as autoexport
exports = autoexport.AutoExports('menu', locals())
