#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\shipfitting\errorConst.py
CANT_FIT_MODULE_TO_SHIP = 1
MODULE_TOO_BIG = 2
CANT_FIT_TOO_MANY_BY_GROUP = 3
CANT_FIT_TOO_MANY_BY_TYPE = 4
NOT_ENOUGH_LAUNCHER_SLOTS = 5
NOT_ENOUGH_TURRET_SLOTS = 6
NOT_ENOUGH_RIG_SLOTS = 7
RIG_WRONG_SIZE = 8
SLOT_NOT_PRESENT = 9
WRONG_SLOT = 10
SLOT_IN_USE = 11
MODULE_NOT_POWERED = 12
MODULE_NOT_APPROPRIATE_FOR_CATEGORY = 13
