#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\projectdiscovery\common\projects\exoplanets\classes.py
from localization import GetByLabel
CLASSES = [{'id': 100,
  'name': GetByLabel('UI/ProjectDiscovery/exoplanets/CategoryDescriptions/PulsatingStarName'),
  'description': GetByLabel('UI/ProjectDiscovery/exoplanets/CategoryDescriptions/PulsatingStarDescription'),
  'url': 'pulsatingStar.png',
  'conceptUrl': 'PulsatingStarConcept.png',
  'excludes': [],
  'selected': False},
 {'id': 200,
  'name': GetByLabel('UI/ProjectDiscovery/exoplanets/CategoryDescriptions/EruptiveStarName'),
  'description': GetByLabel('UI/ProjectDiscovery/exoplanets/CategoryDescriptions/EruptiveStarDescription'),
  'url': 'eruptiveStar.png',
  'conceptUrl': 'EruptiveStarConcept.png',
  'excludes': [],
  'selected': False},
 {'id': 300,
  'name': GetByLabel('UI/ProjectDiscovery/exoplanets/CategoryDescriptions/RotatingStarName'),
  'description': GetByLabel('UI/ProjectDiscovery/exoplanets/CategoryDescriptions/RotatingStarDescription'),
  'url': 'rotatingStar.png',
  'conceptUrl': 'RotatingStarConcept.png',
  'excludes': [],
  'selected': False},
 {'id': 400,
  'name': GetByLabel('UI/ProjectDiscovery/exoplanets/CategoryDescriptions/EclipsingBinaryName'),
  'description': GetByLabel('UI/ProjectDiscovery/exoplanets/CategoryDescriptions/EclipsingBinaryDescription'),
  'url': 'binaryStar.png',
  'conceptUrl': 'BinaryStarConcept.png',
  'excludes': [],
  'selected': False}]
