#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\projectdiscovery\common\projects\exoplanets\tiers.py
from localization import GetByLabel
TIERS = [{'level': 10,
  'url': 'cap_temp.png',
  'types': (45739, 45740),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsCapLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsCapDescription')},
 {'level': 25,
  'url': 'T_shirt_m.png',
  'types': (45734, 45743),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsTShirtLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsTShirtDescription')},
 {'level': 50,
  'url': 'reward3.png',
  'types': (45486,),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/PacifierBPCLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/PacifierBPCDescription')},
 {'level': 75,
  'url': 'reward5.png',
  'types': (45991,),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/PacifierExoplanetsSkinLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/PacifierExoplanetsSkinDescription')},
 {'level': 100,
  'url': 'lab_coat_f.png',
  'types': (45737, 45744),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsLabCoatLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsLabCoatDescription')},
 {'level': 125,
  'url': 'military_jacket_m.png',
  'types': (45738, 45742),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsJacketLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsJacketDescription')},
 {'level': 150,
  'url': 'reward5.png',
  'types': (45487,),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/EnforcerBPCLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/EnforcerBPCDescription')},
 {'level': 175,
  'url': 'reward5.png',
  'types': (45992,),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/EnforcerExoplanetsSkinLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/EnforcerExoplanetsSkinDescription')},
 {'level': 200,
  'url': 'exploration_suit_m.png',
  'types': (45735, 45741),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsExplorationSuitLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/ExoplanetsExplorationSuitDescription')},
 {'level': 250,
  'url': 'reward5.png',
  'types': (45736, 45745),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/MichelMayorGlassesLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/MichelMayorGlassesDescription')},
 {'level': 500,
  'types': (45528,),
  'rewardLabel': 'UI/ProjectDiscovery/exoplanets/rewards/MarshalBPCLabel',
  'rewardDescription': GetByLabel('UI/ProjectDiscovery/exoplanets/rewards/MarshalBPCDescription')}]
