#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\solarsysteminterference\const.py
DEFAULT_DECREASE_PER_DECAY_TICK = 2800.0
DEFAULT_DECAY_TICK_PERIOD = 25200
DEFAULT_MAX_INTERFERENCE_LEVEL = 10000.0
DEFAULT_QUIESCENT_INTERFERENCE_LEVEL = 0.0
if DEFAULT_MAX_INTERFERENCE_LEVEL <= DEFAULT_QUIESCENT_INTERFERENCE_LEVEL:
    raise RuntimeError('DEFAULT_MAX_INTERFERENCE_LEVEL must be greater than DEFAULT_QUIESCENT_INTERFERENCE_LEVEL')
INTERFERENCE_BAND_NONE = 'N'
INTERFERENCE_BAND_LOW = 'L'
INTERFERENCE_BAND_MEDIUM = 'M'
INTERFERENCE_BAND_HIGH = 'H'
INTERFERENCE_BAND_MEDIUM_THRESHOLD = 0.33
INTERFERENCE_BAND_HIGH_THRESHOLD = 0.66
INTERFERENCE_BAND_LABEL_NAMES = {INTERFERENCE_BAND_NONE: 'UI/InfoWindow/InterferenceNone',
 INTERFERENCE_BAND_LOW: 'UI/InfoWindow/InterferenceLow',
 INTERFERENCE_BAND_MEDIUM: 'UI/InfoWindow/InterferenceMedium',
 INTERFERENCE_BAND_HIGH: 'UI/InfoWindow/InterferenceHigh'}
