#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\dailygoals\client\goalSignals.py
from signals import Signal
on_availability_changed = Signal('dailyGoalSignals.on_availability_changed')
on_payment_availability_changed = Signal('dailyGoalSignals.on_payment_availability_changed')
on_cache_invalidated = Signal('dailyGoalSignals.on_cache_invalidated')
on_progress_changed = Signal('dailyGoalSignals.on_progress_changed')
on_state_changed = Signal('dailyGoalSignals.on_state_changed')
on_created = Signal('dailyGoalSignals.on_created')
on_deleted = Signal('dailyGoalSignals.on_deleted')
on_closed = Signal('dailyGoalSignals.on_closed')
on_completed = Signal('dailyGoalSignals.on_completed')
on_goal_data_fetched = Signal('dailyGoalSignals.on_goal_data_fetched')
on_goal_payment_redeemed = Signal('dailyGoalSignals.on_goal_payment_redeemed')
on_goal_payment_earned = Signal('dailyGoalSignals.on_goal_payment_earned')
on_goal_payment_failed = Signal('dailyGoalSignals.on_goal_payment_failed')
on_goal_payment_complete = Signal('dailyGoalSignals.on_goal_payment_complete')
on_unclaimed_goals_fetched = Signal('dailyGoalSignals.on_unclaimed_goals_fetched')
on_unclaimed_goal_ids_changed = Signal('dailyGoalSignals.on_unclaimed_goal_ids_changed')
on_failed_to_redeem_goal = Signal('dailyGoalSignals.on_failed_to_redeem_goal')
on_failed_to_redeem_all_goals = Signal('dailyGoalSignals.on_failed_to_redeem_all_goals')
on_pay_for_completion_successful = Signal('dailyGoalSignals.on_pay_for_completion_successful')
on_pay_for_completion_failed = Signal('dailyGoalSignals.on_pay_for_completion_failed')
