#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\monolithhoneycomb_events\events.py
CHAT_CLIENT_LOGIN = 'xmppchatsvc.login'
CHAT_CLIENT_HANDLE_CONNECTION_LOST = 'xmppchatsvc.connection.lost'
CHAT_CLIENT_HANDLE_LOGGED_IN = 'xmppchatsvc.connection.established'
CHAT_CLIENT_CONNECTION_OBJECT_CREATED = 'xmppchatsvc.connection_object.created'
CHAT_CONNECTION_CREATED = 'xmppConnection.created'
CHAT_CONNECTION_DELETED = 'xmppConnection.deleted'
CHAT_CONNECTION_CONNECTED = 'xmppConnection.connected'
CHAT_CONNECTION_DISCONNECTED = 'xmppConnection.disconnected'
CHAT_MEMBERSHIP_DELTA_CALCULATED = 'eve.chat.local.membership_list_delta_calculated'
DESTINY_DO_DESTINY_UPDATE_NARROWCASTS = 'destiny.DoDestinyUpdate.narrowcasts'
DESTINY_DO_DESTINY_UPDATE_SINGLECASTS = 'destiny.DoDestinyUpdate.singlecasts'
DESTINY_ADD_TO_USER_HISTORY = 'destiny.AddToUserHistory'
DESTINY_ADD_TO_BUBBLE_HISTORY = 'destiny.AddToBubbleHistory'
DESTINY_ADD_TO_SYSTEM_HISTORY = 'destiny.AddToSystemHistory'
DESTINY_UPDATE_SLIM_ITEM_FIELD_MULTI = 'destiny.UpdateSlimItemFieldMulti'
DESTINY_UPDATE_SLIM_ITEM_FIELD = 'destiny.UpdateSlimItemField'
