#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\behaviors\const\combat.py
BASIC_TARGET_EVALUATOR = 'zero'
COST_TARGET_EVALUATOR = 'cost'
RANDOM_TARGET_EVALUATOR = 'random'
FITTED_MODULE_GROUP_TARGET_EVALUATOR = 'module'
SIZE_TARGET_EVALUATOR = 'size'
THREAT_TARGET_EVALUATOR = 'threat'
RANGE_TARGET_EVALUATOR = 'range'
SIGNATURE_RADIUS_AND_VELOCITY_EVALUATOR = 'sigRadius & velocity'
TOWING_TOW_OBJECTIVE_EVALUATOR = 'towing tow game objective'
ALL_TARGET_EVALUATORS = [RANDOM_TARGET_EVALUATOR,
 SIZE_TARGET_EVALUATOR,
 THREAT_TARGET_EVALUATOR,
 COST_TARGET_EVALUATOR,
 BASIC_TARGET_EVALUATOR,
 FITTED_MODULE_GROUP_TARGET_EVALUATOR,
 RANGE_TARGET_EVALUATOR,
 SIGNATURE_RADIUS_AND_VELOCITY_EVALUATOR,
 TOWING_TOW_OBJECTIVE_EVALUATOR]
FW_ATTACK_NONE = 'None'
FW_ATTACK_NOT_SAME_FACTION = 'attackFwNotSameFaction'
FW_ATTACK_ALL_ENEMIES = 'attackFwAllEnemies'
FW_ATTACK_INSURGENCY_ENEMIES = 'attackFwInsurgencyEnemies'
COMBAT_ORBIT_MWD_DISTANCE_FACTOR_SHORT_DISTANCE = 1.5
COMBAT_ORBIT_MWD_DISTANCE_FACTOR_LONG_DISTANCE = 2.0
COMBAT_ORBIT_MWD_DISTANCE_THRESHOLD = 5000
COMBAT_ORBIT_MWD_DISTANCE_MINIMUM = 1500
COMBAT_ORBIT_MWD_DISTANCE_MAXIMUM = 20000
COMBAT_ORBIT_COMMANDER_VELOCITY_FACTOR = 0.75
COMBAT_MAX_EFFECTIVE_FALLOFF_DISTANCE_FACTOR = 0.75
COMBAT_MIN_EFFECTIVE_COMBAT_RANGE_FACTOR = 0.3
COMBAT_MAX_EFFECTIVE_DISTANCE_FACTOR = 1.5
COMBAT_MIN_EFFECTIVE_RANGE = 30000
THREAT_MAX_DISTANCE_FROM_GUARD_OBJECT = 1500000
