#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\kiring\common\const.py
KIRING_GAME_ID = 'aecfu6bgiuaaaal2-g-ma79'
KIRING_GAME_ID_SHORT = KIRING_GAME_ID[-4:]
KIRING_PLATFORM = 'pc'
KIRING_SDK_VERSION = '1.0.0'
KIRING_MODE_DEBUG = 1
KIRING_MODE_RELEASE = 2
KIRING_SUCCESS_CODES = (0, 200)
KIRING_VALIDATION_CODES = {201: None,
 202: 'CNYPurchaseFailUnder8',
 203: 'CNYPurchaseFailUnder16TooHigh',
 204: 'CNYPurchaseFailUnder16MonthlyTooHigh',
 205: 'CNYPurchaseFailUnder18TooHigh',
 206: 'CNYPurchaseFailUnder18MontlyTooHigh'}
ANTI_ADDICTION_PASS_CODE = 201
ANTI_ADDICTION_CHECK_FAIL_JUVENILES_BLOCK_AFTER_22_AND_BEFORE_8 = 202
ANTI_ADDICTION_CHECK_FAIL_JUVENILES_PLAY_TIME_OVERFLOW = 203
ANTI_ADDICTION_CHECK_FAIL_JUVENILES_PLAY_TIME_OVERFLOW_HOLIDAY = 204
SAUTH_SUCCESS_CODE = 201
SAUTH_FAIL_CODE = 500
SAUTH_FAIL_DEFAULT_AID = 1
