#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\notifications\common\formatting\notificationFormatMapping.py
import eve.common.script.util.notificationconst as notificationConst
import notifications.common.formatters.moonmining as moonminingNotifications
from notifications.common.formatters.addictionWarning import AddictionWarningFormatter
from notifications.common.formatters.boosterConsumedFormatter import BoosterConsumedFormatter
from notifications.common.formatters.calendar import CalendarNotificationFormatter
from notifications.common.formatters.ccpDevNews import CCPDevNewsFormatter
from notifications.common.formatters.ccpGameNews import CCPGameNewsFormatter
from notifications.common.formatters.ccpOutOfGameNews import CCPOutOfGameNewsFormatter
from notifications.common.formatters.ccpServerNews import CCPServerNewsFormatter
from notifications.common.formatters.contactFormatters import ContactAddFormatter, ContactEditFormatter, BuddyContactAddFormatter
from notifications.common.formatters.contextualOffers import ContextualOfferNotification
from notifications.common.formatters.contractAccepted import ContractAcceptedFormatter
from notifications.common.formatters.contractAssigned import ContractAssignedFormatter
from notifications.common.formatters.contractAttention import ContractNeedsAttentionFormatter
from notifications.common.formatters.contractRegionChangedToPochven import ContractRegionChangedToPochvenFormatter
from notifications.common.formatters.dailyGoals import DailyGoalCompleted, MilestoneCompleted, RewardTrackCompleted
from notifications.common.formatters.essInventoryFull import EssInventoryFull
from notifications.common.formatters.essReserveBankUnlocked import EssReserveBankUnlocked
from notifications.common.formatters.insurgencies import InsurgencyStarted, InsurgencyStarting, InsurgencyEndedPiratesWin, InsurgencyEndedAntiPiratesWin, InsurgencyEndedNoOneWins, InsurgencyStage5Corruption, InsurgencyStage5Suppression
from notifications.common.formatters.officeleases import OfficeLeaseCanceledInsufficientStandings
from notifications.common.formatters.implantPluggedInFormatter import ImplantPluggedInFormatter
from notifications.common.formatters.invasionSystem import InvasionSystemLoginNotification, InvasionSystemStartNotification
from notifications.common.formatters.killMailFinalBlow import KillMailFinalBlowFormatter
from notifications.common.formatters.killMailVictim import KillMailVictimFormatter
from notifications.common.formatters.mailsummary import MailSummaryFormatter
from notifications.common.formatters.mercenaryDen import MercenaryDenReinforced, MercenaryDenAttacked, MercenaryDenNewMTO
from notifications.common.formatters.newMail import NewMailFormatter
from notifications.common.formatters.npcStandingChangedNotificationFormatter import NPCStandingChangedNotificationFormatter
from notifications.common.formatters.plexDonation import OmegaTimeDonationReceivedFormatter, PlexDonationSentFormatter, OmegaTimeAddedFormatter
from notifications.common.formatters.seasons import SeasonalChallengeCompletedFormatter
from notifications.common.formatters.shipGroupUnlocked import ShipGroupUnlocked
from notifications.common.formatters.skillInjected import SkillInjectedFormatter
from notifications.common.formatters.skillPoints import UnusedSkillPointsFormatter
from notifications.common.formatters.skyhook import SkyhookLinkStarted, SkyhookOnline, SkyhookLostShield, SkyhookUnderAttack, SkyhookDestroyed, SkyhookDeployed, SkyhookTheftVulnerabilityStarted
from notifications.common.formatters.sovAllianceCapitalChange import SovAllianceCapitalChanged
from notifications.common.formatters.sovBase import SovIHubDestroyedByBillFailure
from notifications.common.formatters.sovBase import SovStructureDestroyed, SovEntosisCaptureStarted, SovStationServiceEnabled, SovStationServiceDisabled, SovStationServiceHalfCaptured, SovStructureDestructFinished
from notifications.common.formatters.sovCommandNodeEvent import SovCommandNodeEventStarted
from notifications.common.formatters.sovIHubBillAboutToExpire import IHubBillAboutToExpire
from notifications.common.formatters.sovStationEnteredFreeport import SovStationEnteredFreeport
from notifications.common.formatters.sovStructureReinforced import SovStructureReinforced
from notifications.common.formatters.structureDestructCancel import StructureDestructCancel
from notifications.common.formatters.structureDestructRequested import StructureDestructRequested
from notifications.common.formatters.structures import StructureFuelAlert, StructureAnchoring, StructureUnanchoring, StructureUnderAttack, StructureOnline, StructureLostShield, StructureLostArmor, StructureDestroyed, StructureItemsMovedToSafety, StructureItemsNeedAttention, StructureMarketOrdersCancelled, StructureLostDockingAccess, StructureServicesOffline, StructureOwnershipTransferred, StructureItemsDelivered, StructureCourierContractDestinationChanged, StructureWentLowPower, StructureWentHighPower, StructuresReinforcementChanged, StructureIndustryJobsPaused, StructureIndustryJobsCancelled, StructureImpendingAbandonmentAssetsAtRisk, StructurePaintPurchased, StructureNoReagentsAlert, StructureLowReagentsAlert
from notifications.common.formatters.ticketReply import TicketReplyFormatter
from notifications.common.formatters.war import WarInvalidateMsg, WarHQRemovedFromSpace, WarMutualWarInviteSent, WarMutualWarInviteRejected, WarMutualWarInviteAccepted, WarAdopted, MutualWarExpired, WarInherited, WarAllyInherited, MutualWarRetracted, ConcordRetractsWar, WarEndedHqSystemSecurityDropMsg, WarInvalid
from notifications.common.formatters.warPermit import CorpBecameWarEligible, CorpNoLongerWarEligible
from notifications.common.formatters.essMainBankTheft import EssMainBankTheft
from notifications.common.formatters.essLinkDisconnected import EssLinkDisconnected
formatterByNotificationType = {notificationConst.notificationTypeMailSummary: MailSummaryFormatter,
 notificationConst.notificationTypeNewMailFrom: NewMailFormatter,
 notificationConst.notificationTypeUnusedSkillPoints: UnusedSkillPointsFormatter,
 notificationConst.notificationTypeContractNeedsAttention: ContractNeedsAttentionFormatter,
 notificationConst.notificationTypeContractAssigned: ContractAssignedFormatter,
 notificationConst.notificationTypeContractAccepted: ContractAcceptedFormatter,
 notificationConst.notificationTypeContractRegionChangedToPochven: ContractRegionChangedToPochvenFormatter,
 notificationConst.notificationTypeKillReportVictim: KillMailVictimFormatter,
 notificationConst.notificationTypeKillReportFinalBlow: KillMailFinalBlowFormatter,
 notificationConst.notificationTypeGameTimeReceived: OmegaTimeDonationReceivedFormatter,
 notificationConst.notificationTypeGameTimeSent: PlexDonationSentFormatter,
 notificationConst.notificationTypeGameTimeAdded: OmegaTimeAddedFormatter,
 notificationConst.notificationTypeEntosisCaptureStarted: SovEntosisCaptureStarted,
 notificationConst.notificationTypeStationServiceEnabled: SovStationServiceEnabled,
 notificationConst.notificationTypeStationServiceDisabled: SovStationServiceDisabled,
 notificationConst.notificationTypeStationServiceHalfCaptured: SovStationServiceHalfCaptured,
 notificationConst.notificationTypeSovStructureDestroyed: SovStructureDestroyed,
 notificationConst.notificationTypeSovStructureSelfDestructRequested: StructureDestructRequested,
 notificationConst.notificationTypeSovStructureSelfDestructCancel: StructureDestructCancel,
 notificationConst.notificationTypeSovStructureSelfDestructFinished: SovStructureDestructFinished,
 notificationConst.notificationTypeIHubDestroyedByBillFailure: SovIHubDestroyedByBillFailure,
 notificationConst.notificationTypeSovStationEnteredFreeport: SovStationEnteredFreeport,
 notificationConst.notificationTypeAllianceCapitalChanged: SovAllianceCapitalChanged,
 notificationConst.notificationTypeSovCommandNodeEventStarted: SovCommandNodeEventStarted,
 notificationConst.notificationTypeSovStructureReinforced: SovStructureReinforced,
 notificationConst.notificationTypeInfrastructureHubBillAboutToExpire: IHubBillAboutToExpire,
 notificationConst.notificationTypeContactAdd: ContactAddFormatter,
 notificationConst.notificationTypeContactEdit: ContactEditFormatter,
 notificationConst.notificationTypeBuddyConnectContactAdd: BuddyContactAddFormatter,
 notificationConst.notificationTypeStructureFuelAlert: StructureFuelAlert,
 notificationConst.notificationTypeStructureAnchoring: StructureAnchoring,
 notificationConst.notificationTypeStructureUnanchoring: StructureUnanchoring,
 notificationConst.notificationTypeStructureUnderAttack: StructureUnderAttack,
 notificationConst.notificationTypeStructureOnline: StructureOnline,
 notificationConst.notificationTypeStructureLostShields: StructureLostShield,
 notificationConst.notificationTypeStructureLostArmor: StructureLostArmor,
 notificationConst.notificationTypeStructureDestroyed: StructureDestroyed,
 notificationConst.notificationTypeStructureItemsToAssetSafety: StructureItemsMovedToSafety,
 notificationConst.notificationTypeStructureItemsNeedAttention: StructureItemsNeedAttention,
 notificationConst.notificationTypeStructureMarketOrdersCancelled: StructureMarketOrdersCancelled,
 notificationConst.notificationTypeStructureLostDockingAccess: StructureLostDockingAccess,
 notificationConst.notificationTypeStructureServicesOffline: StructureServicesOffline,
 notificationConst.notificationTypeOwnershipTransferred: StructureOwnershipTransferred,
 notificationConst.notificationTypeStructureItemsDelivered: StructureItemsDelivered,
 notificationConst.notificationTypeStructureWentLowPower: StructureWentLowPower,
 notificationConst.notificationTypeStructureWentHighPower: StructureWentHighPower,
 notificationConst.notificationTypeStructuresReinforcementChanged: StructuresReinforcementChanged,
 notificationConst.notificationTypeStructureCourierContractChanged: StructureCourierContractDestinationChanged,
 notificationConst.notificationTypeStructuresJobsPaused: StructureIndustryJobsPaused,
 notificationConst.notificationTypeStructuresJobsCancelled: StructureIndustryJobsCancelled,
 notificationConst.notificationTypeStructureImpendingAbandonmentAssetsAtRisk: StructureImpendingAbandonmentAssetsAtRisk,
 notificationConst.notificationTypeStructureLowReagentsAlert: StructureLowReagentsAlert,
 notificationConst.notificationTypeStructureNoReagentsAlert: StructureNoReagentsAlert,
 notificationConst.notificationTypeSeasonalChallengeCompleted: SeasonalChallengeCompletedFormatter,
 notificationConst.notificationTypeCalendarEvent: CalendarNotificationFormatter,
 notificationConst.notificationTypeNPCStandingsChanged: NPCStandingChangedNotificationFormatter,
 notificationConst.notificationTypeNPCStandingsGained: NPCStandingChangedNotificationFormatter,
 notificationConst.notificationTypeMoonminingExtractionStarted: moonminingNotifications.MoonminingExtractionStartedNotificationFormatter,
 notificationConst.notificationTypeMoonminingExtractionCancelled: moonminingNotifications.MoonminingExtractionCancelledNotificationFormatter,
 notificationConst.notificationTypeMoonminingExtractionFinished: moonminingNotifications.MoonminingExtractionFinishedNotificationFormatter,
 notificationConst.notificationTypeMoonminingLaserFired: moonminingNotifications.MoonminingLaserFiredNotificationFormatter,
 notificationConst.notificationTypeMoonminingAutomaticFracture: moonminingNotifications.MoonminingAutomaticFractureNotificationFormatter,
 notificationConst.notificationTypeCCPDevNews: CCPDevNewsFormatter,
 notificationConst.notificationTypeCCPServerNews: CCPServerNewsFormatter,
 notificationConst.notificationTypeCCPGameNews: CCPGameNewsFormatter,
 notificationConst.notificationTypeCCPOutOfGameNews: CCPOutOfGameNewsFormatter,
 notificationConst.notificationTypeTicketReply: TicketReplyFormatter,
 notificationConst.notificationTypeSkillInjected: SkillInjectedFormatter,
 notificationConst.notificationTypeImplantPluggedIn: ImplantPluggedInFormatter,
 notificationConst.notificationTypeBoosterConsumed: BoosterConsumedFormatter,
 notificationConst.notificationTypeCorpBecameWarEligible: CorpBecameWarEligible,
 notificationConst.notificationTypeCorpNotLongerWarEligible: CorpNoLongerWarEligible,
 notificationConst.notificationTypeCorpWarInvalidatedMsg: WarInvalidateMsg,
 notificationConst.notificationTypeWarHQRemovedFromSpace: WarHQRemovedFromSpace,
 notificationConst.notificationTypeInvasionSystemLogin: InvasionSystemLoginNotification,
 notificationConst.notificationTypeInvasionSystemStart: InvasionSystemStartNotification,
 notificationConst.notificationTypeWarMutualWarInviteSent: WarMutualWarInviteSent,
 notificationConst.notificationTypeWarMutualWarInviteRejected: WarMutualWarInviteRejected,
 notificationConst.notificationTypeWarMutualWarInviteAccepted: WarMutualWarInviteAccepted,
 notificationConst.notificationTypeWarAdopted: WarAdopted,
 notificationConst.notificationTypeWarMutualWarExpired: MutualWarExpired,
 notificationConst.notificationTypeWarInherited: WarInherited,
 notificationConst.notificationTypeWarAllyInherited: WarAllyInherited,
 notificationConst.notificationTypeWarConcordInvalidates: WarInvalidateMsg,
 notificationConst.notificationTypeWarRetracted: MutualWarRetracted,
 notificationConst.notificationTypeWarEndedHqSecurityDrop: WarEndedHqSystemSecurityDropMsg,
 notificationConst.notificationTypeWarRetractedByConcord: ConcordRetractsWar,
 notificationConst.notificationTypeWarInvalid: WarInvalid,
 notificationConst.notificationTypeNewOfferAvailable: ContextualOfferNotification,
 notificationConst.notificationTypeOfferPurchased: ContextualOfferNotification,
 notificationConst.notificationTypeAddictionWarning: AddictionWarningFormatter,
 notificationConst.notificationTypeOfficeLeaseCanceledInsufficientStandings: OfficeLeaseCanceledInsufficientStandings,
 notificationConst.notificationTypeEssMainBankLink: EssMainBankTheft,
 notificationConst.notificationTypeEssLinkDisconnected: EssLinkDisconnected,
 notificationConst.notificationTypeEssReserveBankUnlocked: EssReserveBankUnlocked,
 notificationConst.notificationTypeEssInventoryFull: EssInventoryFull,
 notificationConst.notificationTypeStructurePaintPurchased: StructurePaintPurchased,
 notificationConst.notificationTypeInsurgencyStarted: InsurgencyStarted,
 notificationConst.notificationTypeInsurgencyStarting: InsurgencyStarting,
 notificationConst.notificationTypeInsurgencyEndedPiratesWin: InsurgencyEndedPiratesWin,
 notificationConst.notificationTypeInsurgencyEndedAntiPiratesWin: InsurgencyEndedAntiPiratesWin,
 notificationConst.notificationTypeInsurgencyEndedNoOneWins: InsurgencyEndedNoOneWins,
 notificationConst.notificationTypeInsurgencyStage5Corruption: InsurgencyStage5Corruption,
 notificationConst.notificationTypeInsurgencyStage5Suppression: InsurgencyStage5Suppression,
 notificationConst.notificationTypeDailyGoalCompleted: DailyGoalCompleted,
 notificationConst.notificationTypeShipGroupUnlocked: ShipGroupUnlocked,
 notificationConst.notificationTypeDailyMilestoneCompleted: MilestoneCompleted,
 notificationConst.notificationTypeDailyRewardTrackCompleted: RewardTrackCompleted,
 notificationConst.notificationTypeSkyhookLinkStarted: SkyhookLinkStarted,
 notificationConst.notificationTypeSkyhookTheftVulnerabilityStarted: SkyhookTheftVulnerabilityStarted,
 notificationConst.notificationTypeSkyhookOnline: SkyhookOnline,
 notificationConst.notificationTypeSkyhookLostShields: SkyhookLostShield,
 notificationConst.notificationTypeSkyhookUnderAttack: SkyhookUnderAttack,
 notificationConst.notificationTypeSkyhookDestroyed: SkyhookDestroyed,
 notificationConst.notificationTypeSkyhookDeployed: SkyhookDeployed,
 notificationConst.notificationTypeMercenaryDenReinforced: MercenaryDenReinforced,
 notificationConst.notificationTypeMercDenAttacked: MercenaryDenAttacked,
 notificationConst.notificationTypeMercDenNewMTO: MercenaryDenNewMTO}

def GetFormatterForType(typeID):
    formatterCls = formatterByNotificationType.get(typeID, None)
    if formatterCls:
        return formatterCls()
