#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\qtyTooltip\qtyConst.py
ABOUT_CHAR = u'\u2248'
MIN_AMOUNT_TO_DISPLAY_FULL_TEXT = 10000
EDIT_INPUT_TYPE_ISK = 'ISK'
EDIT_INPUT_TYPE_INT = 'INT'
EDIT_INPUT_TYPE_FLOAT = 'FLOAT'
EDIT_INPUT_TYPE_NO_NUMBERHINT = 'NOHINT'
EDIT_INPUT_TYPES = (EDIT_INPUT_TYPE_ISK, EDIT_INPUT_TYPE_INT, EDIT_INPUT_TYPE_FLOAT)
