#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\cluster\__init__.py
SERVICE_BEYONCE = 2
SERVICE_STATION = 3
SERVICE_CONSTELLATION = 7
SERVICE_MARKET = 9
SERVICE_AGENTMGR = 12
SERVICE_CHATX = 14
SERVICE_XIAOYU = 17
SERVICE_CONTRACTS = 22
SERVICE_PLANETMGR = 23
SERVICE_BATTLEINSTANCEMANAGER = 25
SERVICE_BATTLEQUICKMATCHER = 26
SERVICE_POLARIS = 40
SERVICE_CHARACTER = 43
SERVICE_VOICEADMINMGR = 46
SERVICE_COMMUNITYSERVICE = 47
SERVICE_WORLDSPACE = 48
SERVICE_ZONE = 49
SERVICE_LSC = 51
SERVICE_CLUSTERSINGLETON = 52
SERVICE_USER = 53
SERVICE_BATTLE = SERVICE_BATTLEINSTANCEMANAGER
SERVICE_BATTLE_DIRECTORY = SERVICE_BATTLEINSTANCEMANAGER
SERVICE_BATTLE_SERVER = SERVICE_BATTLEINSTANCEMANAGER
SERVICE_BATTLE_QUEUE = SERVICE_BATTLEINSTANCEMANAGER
SERVICE_SQUAD = SERVICE_BATTLEINSTANCEMANAGER
SERVICE_SQUAD_DIRECTORY = SERVICE_BATTLEINSTANCEMANAGER
SERVICE_DISTRICT = SERVICE_BATTLEINSTANCEMANAGER
SERVICE_CORPORATION = SERVICE_CHATX
SERVICE_TALEDISTRIBUTIONMGR = SERVICE_CLUSTERSINGLETON
SERVICE_FLEETFINDER = SERVICE_CLUSTERSINGLETON
SERVICE_CORPRECRUITMENTMGR = SERVICE_CLUSTERSINGLETON
SERVICE_PETITIONWORK = SERVICE_CLUSTERSINGLETON
SERVICE_FACWARZONE = SERVICE_CLUSTERSINGLETON
SERVICE_TOURNEYSINGLETON = SERVICE_CLUSTERSINGLETON
SERVICE_CCPNOTIFICATION = SERVICE_CLUSTERSINGLETON
SERVICE_DYNAMICRSCCACHEMGR = SERVICE_CLUSTERSINGLETON
SERVICE_JUMPBEACON = SERVICE_CLUSTERSINGLETON
SERVICE_LSCGETMEMBERCOUNTS = SERVICE_CLUSTERSINGLETON
SERVICE_OVERVIEWPRESETMGR = SERVICE_CLUSTERSINGLETON
SERVICE_ASSETSAFETY = SERVICE_CLUSTERSINGLETON
SERVICE_DUNGEONCACHE = SERVICE_CLUSTERSINGLETON
SERVICE_RAFFLES = SERVICE_CLUSTERSINGLETON
SERVICE_BOOKMARK_PERSISTENCE = SERVICE_CLUSTERSINGLETON
SERVICE_BOUNTYMGR = SERVICE_CLUSTERSINGLETON
MACHORESOLVE_BY_SINGLETON_BUCKET = {0: 'clustersingleton_0',
 1: 'clustersingleton_1',
 2: 'clustersingleton_2',
 3: 'clustersingleton_3',
 4: 'clustersingleton_4',
 5: 'clustersingleton_5',
 6: 'clustersingleton_6',
 7: 'clustersingleton_7'}
SINGLETON_BUCKET_FW_BROKER = 0
SINGLETON_BUCKET_SHIP_CASTER = 0
SINGLETON_BUCKET_INSURGENCY = 6
SERVICE_ALL = 18446744073709551615L
SERVICE_NONE = 0
SERVICE_MOD_DEFAULT = 128
SERVICE_MODS = {SERVICE_BEYONCE: 18446744073709551615L,
 SERVICE_CHATX: 200}
MACHONETMSG_TYPE_AUTHENTICATION_REQ = 0
MACHONETMSG_TYPE_AUTHENTICATION_RSP = 1
MACHONETMSG_TYPE_IDENTIFICATION_REQ = 2
MACHONETMSG_TYPE_IDENTIFICATION_RSP = 3
MACHONETMSG_TYPE_CALL_REQ = 6
MACHONETMSG_TYPE_CALL_RSP = 7
MACHONETMSG_TYPE_TRANSPORTCLOSED = 8
MACHONETMSG_TYPE_RESOLVE_REQ = 10
MACHONETMSG_TYPE_RESOLVE_RSP = 11
MACHONETMSG_TYPE_NOTIFICATION = 12
MACHONETMSG_TYPE_ERRORRESPONSE = 15
MACHONETMSG_TYPE_SESSIONCHANGENOTIFICATION = 16
MACHONETMSG_TYPE_SESSIONINITIALSTATENOTIFICATION = 18
MACHONETMSG_TYPE_PING_REQ = 20
MACHONETMSG_TYPE_PING_RSP = 21
MACHONETMSG_TYPE_MOVEMENTNOTIFICATION = 100
MACHONETERR_UNMACHODESTINATION = 0
MACHONETERR_UNMACHOCHANNEL = 1
MACHONETERR_WRAPPEDEXCEPTION = 2
CLUSTER_INGRESS_ORIGIN_CLIENT = 0
CLUSTER_INGRESS_ORIGIN_QUASAR = 1
CLUSTER_INGRESS_ORIGIN_NAME = {CLUSTER_INGRESS_ORIGIN_CLIENT: 'client',
 CLUSTER_INGRESS_ORIGIN_QUASAR: 'quasar'}
NODE_ANY = 0
NODE_ANY_PROXY = 1
NODE_ANY_SERVER = 2
NODE_ALL = 3
NODE_ALL_PROXY = 4
NODE_ALL_SERVER = 5
NODES = [NODE_ANY,
 NODE_ANY_PROXY,
 NODE_ANY_SERVER,
 NODE_ALL,
 NODE_ALL_PROXY,
 NODE_ALL_SERVER]
