#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\grouprewards\__init__.py
REWARD_TYPE_LP = 1
REWARD_TYPE_ISK = 2
REWARD_TYPE_CORP_STANDINGS = 3
REWARD_TYPE_FACTION_STANDINGS = 4
REWARD_TYPE_INTERNAL_NAME = {REWARD_TYPE_LP: 'lp',
 REWARD_TYPE_ISK: 'isk',
 REWARD_TYPE_CORP_STANDINGS: 'corporation standings',
 REWARD_TYPE_FACTION_STANDINGS: 'faction standings'}
SECURITY_CRITERIA_ALL_SECURITY_BANDS = 0
SECURITY_CRITERIA_HIGH_SECURITY = 1
SECURITY_CRITERIA_LOW_SECURITY = 2
SECURITY_CRITERIA_NULL_SECURITY = 3
