#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\abyss\client\constants.py
from abyss.common import TIER_0_DEMO
from abyss.common.constants import TIER_1, TIER_2, TIER_3, TIER_4, TIER_5, TIER_0, TIER_6
from inventorycommon.const import typeDemoGammaFilament
from inventorycommon.const import typeElectricAbyss, typeCausticAbyss, typeInfernalAbyss, typeXenonAbyss, typeDarkAbyss, typeCalmElectricalFilament, typeCalmFirestormFilament, typeCalmExoticFilament, typeCalmGammaFilament, typeCalmDarkFilament, typeAgitatedElectricalFilament, typeAgitatedFirestormFilament, typeAgitatedExoticFilament, typeAgitatedGammaFilament, typeAgitatedDarkFilament, typeFierceElectricalFilament, typeFierceFirestormFilament, typeFierceExoticFilament, typeFierceGammaFilament, typeFierceDarkFilament, typeRagingElectricalFilament, typeRagingFirestormFilament, typeRagingExoticFilament, typeRagingGammaFilament, typeRagingDarkFilament, typeChaoticElectricalFilament, typeChaoticFirestormFilament, typeChaoticExoticFilament, typeChaoticGammaFilament, typeChaoticDarkFilament, typeTranquilElectricalFilament, typeTranquilFirestormFilament, typeTranquilExoticFilament, typeTranquilGammaFilament, typeTranquilDarkFilament, typeCataclysmicElectricalFilament, typeCataclysmicFirestormFilament, typeCataclysmicExoticFilament, typeCataclysmicGammaFilament, typeCataclysmicDarkFilament
WEATHER_NAMES_BY_ID = {typeElectricAbyss: 'UI/Abyss/WeatherNames/Electrical',
 typeCausticAbyss: 'UI/Abyss/WeatherNames/Exotic',
 typeInfernalAbyss: 'UI/Abyss/WeatherNames/Firestorm',
 typeXenonAbyss: 'UI/Abyss/WeatherNames/Gamma',
 typeDarkAbyss: 'UI/Abyss/WeatherNames/Dark'}
WEATHER_HINTS_BY_ID = {typeElectricAbyss: 'UI/Agency/Tooltips/Encounters/AbyssalDeadspace/Electrical',
 typeCausticAbyss: 'UI/Agency/Tooltips/Encounters/AbyssalDeadspace/Exotic',
 typeInfernalAbyss: 'UI/Agency/Tooltips/Encounters/AbyssalDeadspace/Firestorm',
 typeXenonAbyss: 'UI/Agency/Tooltips/Encounters/AbyssalDeadspace/Gamma',
 typeDarkAbyss: 'UI/Agency/Tooltips/Encounters/AbyssalDeadspace/Dark'}
WEATHER_TEXTURE_PATHS_BY_ID = {typeElectricAbyss: 'res:/UI/Texture/Icons/StatusEffects/weatherLightning.png',
 typeCausticAbyss: 'res:/UI/Texture/Icons/StatusEffects/weatherCaustic.png',
 typeInfernalAbyss: 'res:/UI/Texture/Icons/StatusEffects/weatherInfernal.png',
 typeXenonAbyss: 'res:/UI/Texture/Icons/StatusEffects/weatherXenonGas.png',
 typeDarkAbyss: 'res:/UI/Texture/Icons/StatusEffects/weatherDarkness.png'}
NAME_LABEL_PATH_BY_TIER = {TIER_0: 'UI/Abyss/TierNames/Tier0',
 TIER_0_DEMO: 'UI/Abyss/TierNames/Tier0',
 TIER_1: 'UI/Abyss/TierNames/Tier1',
 TIER_2: 'UI/Abyss/TierNames/Tier2',
 TIER_3: 'UI/Abyss/TierNames/Tier3',
 TIER_4: 'UI/Abyss/TierNames/Tier4',
 TIER_5: 'UI/Abyss/TierNames/Tier5',
 TIER_6: 'UI/Abyss/TierNames/Tier6'}
DIFFICULTY_LABEL_PATH_BY_TIER = {TIER_0: 'UI/Abyss/TierDifficulties/Tier0',
 TIER_0_DEMO: 'UI/Abyss/TierDifficulties/Tier0',
 TIER_1: 'UI/Abyss/TierDifficulties/Tier1',
 TIER_2: 'UI/Abyss/TierDifficulties/Tier2',
 TIER_3: 'UI/Abyss/TierDifficulties/Tier3',
 TIER_4: 'UI/Abyss/TierDifficulties/Tier4',
 TIER_5: 'UI/Abyss/TierDifficulties/Tier5',
 TIER_6: 'UI/Abyss/TierDifficulties/Tier6'}
TIER_TEXTURE_PATH_BY_TIER = {TIER_0: 'res:/UI/Texture/Icons/Inventory/abyssalFilamentL0.png',
 TIER_0_DEMO: 'res:/UI/Texture/Icons/Inventory/abyssalFilamentL0.png',
 TIER_1: 'res:/UI/Texture/Icons/Inventory/abyssalFilamentL1.png',
 TIER_2: 'res:/UI/Texture/Icons/Inventory/abyssalFilamentL2.png',
 TIER_3: 'res:/UI/Texture/Icons/Inventory/abyssalFilamentL3.png',
 TIER_4: 'res:/UI/Texture/Icons/Inventory/abyssalFilamentL4.png',
 TIER_5: 'res:/UI/Texture/Icons/Inventory/abyssalFilamentL5.png',
 TIER_6: 'res:/UI/Texture/Icons/Inventory/abyssalFilamentL6.png'}
KEY_TYPE_BY_TIER_AND_WEATHER = {(TIER_0, typeElectricAbyss): typeTranquilElectricalFilament,
 (TIER_0, typeInfernalAbyss): typeTranquilFirestormFilament,
 (TIER_0, typeCausticAbyss): typeTranquilExoticFilament,
 (TIER_0, typeXenonAbyss): typeTranquilGammaFilament,
 (TIER_0, typeDarkAbyss): typeTranquilDarkFilament,
 (TIER_0_DEMO, typeXenonAbyss): typeDemoGammaFilament,
 (TIER_1, typeElectricAbyss): typeCalmElectricalFilament,
 (TIER_1, typeInfernalAbyss): typeCalmFirestormFilament,
 (TIER_1, typeCausticAbyss): typeCalmExoticFilament,
 (TIER_1, typeXenonAbyss): typeCalmGammaFilament,
 (TIER_1, typeDarkAbyss): typeCalmDarkFilament,
 (TIER_2, typeElectricAbyss): typeAgitatedElectricalFilament,
 (TIER_2, typeInfernalAbyss): typeAgitatedFirestormFilament,
 (TIER_2, typeCausticAbyss): typeAgitatedExoticFilament,
 (TIER_2, typeXenonAbyss): typeAgitatedGammaFilament,
 (TIER_2, typeDarkAbyss): typeAgitatedDarkFilament,
 (TIER_3, typeElectricAbyss): typeFierceElectricalFilament,
 (TIER_3, typeInfernalAbyss): typeFierceFirestormFilament,
 (TIER_3, typeCausticAbyss): typeFierceExoticFilament,
 (TIER_3, typeXenonAbyss): typeFierceGammaFilament,
 (TIER_3, typeDarkAbyss): typeFierceDarkFilament,
 (TIER_4, typeElectricAbyss): typeRagingElectricalFilament,
 (TIER_4, typeInfernalAbyss): typeRagingFirestormFilament,
 (TIER_4, typeCausticAbyss): typeRagingExoticFilament,
 (TIER_4, typeXenonAbyss): typeRagingGammaFilament,
 (TIER_4, typeDarkAbyss): typeRagingDarkFilament,
 (TIER_5, typeElectricAbyss): typeChaoticElectricalFilament,
 (TIER_5, typeInfernalAbyss): typeChaoticFirestormFilament,
 (TIER_5, typeCausticAbyss): typeChaoticExoticFilament,
 (TIER_5, typeXenonAbyss): typeChaoticGammaFilament,
 (TIER_5, typeDarkAbyss): typeChaoticDarkFilament,
 (TIER_6, typeElectricAbyss): typeCataclysmicElectricalFilament,
 (TIER_6, typeInfernalAbyss): typeCataclysmicFirestormFilament,
 (TIER_6, typeCausticAbyss): typeCataclysmicExoticFilament,
 (TIER_6, typeXenonAbyss): typeCataclysmicGammaFilament,
 (TIER_6, typeDarkAbyss): typeCataclysmicDarkFilament}
