#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\ui\shared\activities\activitiesUIConst.py
SCALE = 1
OPACITY_HOVER = 0.2
OPACITY_SELECTED = 0.15
OPACITY_IDLE = 0.1
SPRITE_OPACITY = 0.2
IMG_HEIGHT = 400
DURATION = 0.3
SECOND_DURATION = 0.3
OUT_DURATION = 0.2
OUT_SECOND_DURATION = 0.2
MOUSE_ENTER_EXIT_DURATION = 0.3
EDGE_FRAME_SIZE = 2
WIDTH = 1222
HEIGHT = 680
HEADER_HEIGHT = 45
FOOTER_HEIGHT = 51
BG_WIDTH = WIDTH - EDGE_FRAME_SIZE * 2
BG_HEIGHT = HEIGHT - EDGE_FRAME_SIZE * 2 - HEADER_HEIGHT
MAIN_SPRITE_WIDTH = BG_WIDTH
MAIN_SPRITE_HEIGHT = BG_HEIGHT - FOOTER_HEIGHT
BANNER_SPRITE_WIDTH = MAIN_SPRITE_WIDTH
BANNER_SPRITE_HEIGHT = MAIN_SPRITE_HEIGHT
SCROLL_SECTION_RIGHT_PADDING = 50
SCROLL_SECTION_WIDTH = 315
SCROLL_SECTION_HEIGHT = 510
SCROLL_SECTION_HEADER_HEIGHT = 30
SCROLL_SECTION_REST_HEIGHT = SCROLL_SECTION_HEIGHT - SCROLL_SECTION_HEADER_HEIGHT
SCROLL_PADDING_HEIGHT = 18
SCROLL_WIDTH = SCROLL_SECTION_WIDTH
SCROLL_HEIGHT = SCROLL_SECTION_REST_HEIGHT - SCROLL_PADDING_HEIGHT
SCROLL_ELEMENT_LEFT_PADDING = 30
SCROLL_ELEMENT_RIGHT_PADDING = 29
SCROLL_ELEMENT_BOTTOM_PADDING = 16
ACTIVITY_ENTRY_HEIGHT = 84
SCROLL_ELEMENT_TITLE_WIDTH = 169
SCROLL_ELEMENT_TITLE_HEIGHT = 20
SCROLL_ELEMENT_TITLE_TOP_PADDING = 12
SCROLL_ELEMENT_INTRODUCE_WIDTH = 169
SCROLL_ELEMENT_INTRODUCE_HEIGHT = 37
SCROLL_ELEMENT_INTRODUCE_BOTTOM_PADDING = 7
SCROLL_ELEMENT_INTRODUCE_RIGHT_PADDING = 7
SCROLL_ELEMENT_INTRODUCE_DISPLAY_WIDTH = SCROLL_ELEMENT_INTRODUCE_WIDTH - 6
SCROLL_ELEMENT_INTRODUCE_DISPLAY_HEIGHT = SCROLL_ELEMENT_INTRODUCE_HEIGHT
SCROLL_ELEMENT_ICON_PARENT_WIDTH = 70
SCROLL_ELEMENT_ICON_HEIGHT = 70
SCROLL_ELEMENT_ICON_WIDTH = 70
ACTIVITIES_WINDOW_ID = 'activities'
OPEN_ACTIVITIES_WINDOW_COMMAND_NAME = 'ToggleActivities'
ACTIVITIES_ICON_PATH = 'res:/ui/texture/WindowIcons/loudspeaker_Icon58.png'
ACTIVITIES_NOTIFICATION_ID = 'newActivitiesNotification'
ACTIVITIES_HIGHLIGHT = 2276
BADGE_COLOR = (203 / 255.0,
 10 / 255.0,
 4 / 255.0,
 1.0)
SCROLL_LAYER_COLOR = (0 / 255.0,
 0 / 255.0,
 0 / 255.0,
 0.5)
ACTIVITY_COUNT_LAYER_COLOR = (64 / 255.0,
 64 / 255.0,
 64 / 255.0,
 1.0)
DEFAULT_DIAMETER = 16
ONE_MINUTE = 60
ONE_HOUR = 3600
ONE_DAY = 86400
SHOW_LEFT_TIME_TEXT_SECONDS = ONE_DAY * 3
LABEL_LEFT_DAYS = 'UI/NewActivitiesNotify/LeftDays'
LABEL_LEFT_HOURS = 'UI/NewActivitiesNotify/LeftHours'
LABEL_LESS_HOURS = 'UI/NewActivitiesNotify/LeftLessThanHours'
LABEL_ACTIVITY_COUNT = 'UI/NewActivitiesNotify/ActivityCount'
CHOICE_TOGGLE_AURUM_STORE_BY_CATEGORY_ID = 1
CHOICE_TOGGLE_AURUM_STORE_BY_TYPE_IDS = 2
CHOICE_OPEN_SEASON = 3
CHOICE_URL = 4
ACTIVITY_INFO_BUTTON_BACKGROUND = 'res:/UI/Texture/activities/Btn_Events_Notification_OpenWindow.png'
ACTIVITY_INFO_BUTTON_WIDTH = 185
ACTIVITY_INFO_BUTTON_HEIGHT = 35
ACTIVITY_INFO_BUTTON_FONT_SIZE = 25
ACTIVITY_INFO_CLOSE_BUTTON_POS = (-120,
 0,
 ACTIVITY_INFO_BUTTON_WIDTH,
 ACTIVITY_INFO_BUTTON_HEIGHT)
ACTIVITY_INFO_OPEN_STORE_BUTTON_POS = (120,
 0,
 ACTIVITY_INFO_BUTTON_WIDTH,
 ACTIVITY_INFO_BUTTON_HEIGHT)
ACTIVITY_INFO_FOOTER_HEIGHT = 75
ACTIVITY_INFO_MAIN_CONTAINER_HEIGHT = BG_HEIGHT - ACTIVITY_INFO_FOOTER_HEIGHT
