#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\sovereignty\mercenaryden\client\ui\qa_settings.py
from carbonui.services.setting import UserSettingBool
SETTING_SHOULD_FORCE_MMP_VERSION = UserSettingBool(settings_key='should_force_MMP_version', default_value=False)
SETTING_SHOULD_FORCE_MLP_VERSION = UserSettingBool(settings_key='should_force_MLP_version', default_value=False)
SETTING_SHOULD_FORCE_DATA_FAILURE = UserSettingBool(settings_key='should_force_data_failure', default_value=False)
SETTING_SHOULD_FORCE_DISABLED_STATE = UserSettingBool(settings_key='should_force_disabled_state', default_value=False)
SETTING_SHOULD_FORCE_SKILLS_MISSING = UserSettingBool(settings_key='should_force_skills_missing', default_value=False)
SETTING_SHOULD_FORCE_LEVELS_MAXED_OUT = UserSettingBool(settings_key='should_force_levels_maxed_out', default_value=False)
SETTING_SHOULD_FORCE_INFORMORPH_EXTRACTION_SUCCESS = UserSettingBool(settings_key='should_force_infomorph_extraction_success', default_value=False)
