#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\evedungeons\client\gasTypesInDungeons\const.py
import inventorycommon.const as invConst
GAS_TYPES_BY_VALUE = (invConst.typeVermillionCytoserocin,
 invConst.typeFulleriteC320,
 invConst.typeCeladonCytoserocin,
 invConst.typeGoldenCytoserocin,
 invConst.typeAmberCytoserocin,
 invConst.typeMalachiteCytoserocin,
 invConst.typeLimeCytoserocin,
 invConst.typeAzureCytoserocin,
 invConst.typeViridianCytoserocin,
 invConst.typeFulleriteC72,
 invConst.typeFulleriteC540,
 invConst.typeFulleriteC50,
 invConst.typeFulleriteC28,
 invConst.typeFulleriteC32,
 invConst.typeFulleriteC84,
 invConst.typeFulleriteC70,
 invConst.typeFulleriteC60,
 invConst.typeAzureMykoserocin,
 invConst.typeVermillionMykoserocin,
 invConst.typeCeladonMykoserocin,
 invConst.typeLimeMykoserocin,
 invConst.typeMalachiteMykoserocin,
 invConst.typeGoldenMykoserocin,
 invConst.typeAmberMykoserocin,
 invConst.typeChartreuseCytoserocin,
 invConst.typeGambogeCytoserocin)
