#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\agency\common\reward_types.py
REWARDTYPE_ISK1 = 1
REWARDTYPE_ISK2 = 2
REWARDTYPE_ISK3 = 3
REWARDTYPE_LP1 = 4
REWARDTYPE_LP2 = 5
REWARDTYPE_LP3 = 6
REWARDTYPE_LOOT = 7
REWARDTYPE_ASTEROID = 8
REWARDTYPE_GAS = 9
REWARDTYPE_ICE = 10
REWARDTYPE_SKILLPOINTS = 11
REWARDTYPE_SKILLPOINTSCLAIMED = 12
