#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\metadata\common\content_tags\content_tags_enum.py


class ContentTags:
    activity_combat = 'activity_combat'
    activity_donation = 'activity_donation'
    activity_fleet = 'activity_fleet'
    activity_gas_harvesting = 'activity_gas_harvesting'
    activity_hacking = 'activity_hacking'
    activity_hauling = 'activity_hauling'
    activity_ice_harvesting = 'activity_ice_harvesting'
    activity_logistics = 'activity_logistics'
    activity_manufacturing = 'activity_manufacturing'
    activity_mining = 'activity_mining'
    activity_salvaging = 'activity_salvaging'
    activity_trading = 'activity_trading'
    activity_travel = 'activity_travel'
    career_path_enforcer = 'career_path_enforcer'
    career_path_explorer = 'career_path_explorer'
    career_path_industrialist = 'career_path_industrialist'
    career_path_soldier_of_fortune = 'career_path_soldier_of_fortune'
    feature_acp = 'feature_acp'
    feature_agent_missions = 'feature_agent_missions'
    feature_capsuleer_day = 'feature_capsuleer_day'
    feature_combat_anomalies = 'feature_combat_anomalies'
    feature_corporation_projects = 'feature_corporation_projects'
    feature_cosmic_anomalies = 'feature_cosmic_anomalies'
    feature_cosmic_signatures = 'feature_cosmic_signatures'
    feature_daily_goals = 'feature_daily_goals'
    feature_dungeons = 'feature_dungeons'
    feature_epic_arcs = 'feature_epic_arcs'
    feature_escalation_dungeon = 'feature_escalation_dungeon'
    feature_ess = 'feature_ess'
    feature_factional_warfare = 'feature_factional_warfare'
    feature_homefront_operations = 'feature_homefront_operations'
    feature_ice_belts = 'feature_ice_belts'
    feature_introductions = 'feature_introductions'
    feature_landmarks = 'feature_landmarks'
    feature_mercenary_tactical_ops = 'feature_mercenary_tactical_ops'
    feature_ore_anomalies = 'feature_ore_anomalies'
    feature_paragon_missions = 'feature_paragon_missions'
    feature_pirate_insurgencies = 'feature_pirate_insurgencies'
    feature_sansha_incursions = 'feature_sansha_incursions'
    feature_seasons = 'feature_seasons'
    feature_triglavian = 'feature_triglavian'
    feature_winter_nexus = 'feature_winter_nexus'
    feature_world_events = 'feature_world_events'


class ContentTagTypes:
    activity = 'activity'
    career_path = 'career_path'
    feature = 'feature'
