#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\corporation\client\goals\goalSignals.py
from signals import Signal
on_availability_changed = Signal('goalSignals.on_availability_changed')
on_payment_availability_changed = Signal('goalSignals.on_payment_availability_changed')
on_cache_invalidated = Signal('goalSignals.on_cache_invalidated')
on_progress_changed = Signal('goalSignals.on_progress_changed')
on_state_changed = Signal('goalSignals.on_state_changed')
on_view_details = Signal('goalSignals.on_view_details')
on_created = Signal('goalSignals.on_created')
on_deleted = Signal('goalSignals.on_deleted')
on_closed = Signal('goalSignals.on_closed')
on_completed = Signal('goalSignals.on_completed')
on_expired = Signal('goalSignals.on_expired')
on_goal_data_fetched = Signal('goalSignals.on_goal_data_fetched')
on_goal_reward_redeemed = Signal('goalSignals.on_goal_reward_redeemed')
on_goal_reward_earned = Signal('goalSignals.on_goal_reward_earned')
on_goal_redeem_failed = Signal('goalSignals.on_goal_redeem_failed')
on_goal_name_changed = Signal('goalSignals.on_goal_name_changed')
on_goal_description_changed = Signal('goalSignals.on_goal_description_changed')
on_unclaimed_goal_ids_changed = Signal('on_unclaimed_goal_ids_changed')
on_closest_solar_system_changed = Signal('on_closest_solar_system_changed')
