#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\itemcompression\client\ui\label_paths.py
compression_window_caption_label_path = 'UI/Compression/CompressionWindowCaption'
compression_completed_label_path = 'UI/Compression/CompressionCompleted'
compress_action_label_path = 'UI/Compression/CompressAction'
decompress_action_label_path = 'UI/Compression/DecompressAction'
cancel_action_label_path = 'UI/Compression/CancelAction'
input_materials_label_path = 'UI/Compression/InputMaterialsLabel'
output_materials_label_path = 'UI/Compression/OutputMaterialsLabel'
no_facility_label_path = 'UI/Compression/NoFacilityTooltip'
compressed_by_label_path = 'UI/Compression/CompressedBy'
reprocessing_facility_unavailable_tooltip_label_path = 'UI/Compression/reprocessingFacilityUnavailable'
decompression_window_caption_label_path = 'UI/Compression/DecompressionWindowCaption'
decompression_window_tooltip_yield_title = 'UI/decompression/TooltipYieldTitle'
decompression_window_tooltip_decompression_calculations_title = 'UI/decompression/TooltipDecompressionCalculationsTitle'
decompression_window_tooltip_structure_efficiency = 'UI/decompression/TooltipStructureEfficiency'
decompression_window_tooltip_character_skills = 'UI/decompression/TooltipCharacterSkills'
decompression_window_lossy_warning = 'UI/decompression/DecompressionLossyWarning'
