#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\eve\client\script\parklife\overview\test\presets.py
from copy import deepcopy
PRESETS = {'--- PvX: Basic (-Neut +NPC)': {'alwaysShownStates': [],
                                 'groups': [6, 10],
                                 'filteredStates': [11, 12]},
 '-- Ships only': {'alwaysShownStates': [],
                   'groups': [25, 26],
                   'filteredStates': [11, 12]},
 u'<color=0xFF66CCFF>\u272a --- Friendly: All</color>': {'alwaysShownStates': [11,
                                                                               12,
                                                                               14,
                                                                               15,
                                                                               16,
                                                                               45,
                                                                               49],
                                                         'groups': [6,
                                                                    10,
                                                                    15,
                                                                    25,
                                                                    26,
                                                                    27,
                                                                    28,
                                                                    29,
                                                                    30,
                                                                    31,
                                                                    90,
                                                                    237,
                                                                    310,
                                                                    324,
                                                                    358,
                                                                    361,
                                                                    366,
                                                                    380,
                                                                    381,
                                                                    419,
                                                                    420,
                                                                    463,
                                                                    479,
                                                                    485,
                                                                    492,
                                                                    513,
                                                                    540,
                                                                    541,
                                                                    543,
                                                                    547,
                                                                    548,
                                                                    659,
                                                                    830,
                                                                    831,
                                                                    832,
                                                                    833,
                                                                    834,
                                                                    835,
                                                                    836,
                                                                    863,
                                                                    864,
                                                                    883,
                                                                    893,
                                                                    894,
                                                                    897,
                                                                    898,
                                                                    900,
                                                                    902,
                                                                    906,
                                                                    920,
                                                                    925,
                                                                    941,
                                                                    963,
                                                                    988,
                                                                    1003,
                                                                    1005,
                                                                    1012,
                                                                    1022,
                                                                    1149,
                                                                    1201,
                                                                    1202,
                                                                    1246,
                                                                    1249,
                                                                    1273,
                                                                    1274,
                                                                    1275,
                                                                    1276,
                                                                    1283,
                                                                    1305,
                                                                    1316,
                                                                    1404,
                                                                    1406,
                                                                    1408,
                                                                    1527,
                                                                    1534,
                                                                    1538,
                                                                    1548,
                                                                    1657,
                                                                    1704,
                                                                    1972,
                                                                    2016,
                                                                    2017,
                                                                    2020],
                                                         'filteredStates': [9,
                                                                            10,
                                                                            13,
                                                                            17,
                                                                            18,
                                                                            19,
                                                                            20,
                                                                            21,
                                                                            36,
                                                                            37,
                                                                            44,
                                                                            48,
                                                                            50,
                                                                            51,
                                                                            52,
                                                                            53]}}
PRESETS_2 = {u'<color=0xFF66FF66>\u27b2 Extra: Podsaver (!)</color>': {'alwaysShownStates': [],
                                                           'groups': [6,
                                                                      7,
                                                                      8,
                                                                      9,
                                                                      10,
                                                                      988,
                                                                      1081,
                                                                      1082],
                                                           'filteredStates': []},
 'Travel (+Ship -Sta)': {'alwaysShownStates': [],
                         'groups': [6, 10],
                         'filteredStates': [11, 12]}}
PRESETS_3 = {'= Structures': {'alwaysShownStates': [],
                  'groups': [6, 10],
                  'filteredStates': [11, 12]},
 'Brackets: Warpout (!)': {'alwaysShownStates': [],
                           'groups': [6, 7],
                           'filteredStates': []}}
PRESETS_WITH_EWAR_FILTERS = deepcopy(PRESETS)
PRESETS_WITH_EWAR_FILTERS['-- Ships only']['ewarFilters'] = [1,
 2,
 3,
 4,
 5]
PRESETS_2_DISORDERED = {u'<color=0xFF66FF66>\u27b2 Extra: Podsaver (!)</color>': {'alwaysShownStates': [],
                                                           'groups': [1082,
                                                                      6,
                                                                      7,
                                                                      9,
                                                                      8,
                                                                      10,
                                                                      988,
                                                                      1081],
                                                           'filteredStates': []},
 'Travel (+Ship -Sta)': {'alwaysShownStates': [],
                         'groups': [10, 6],
                         'filteredStates': [12, 11]}}
