#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\jobboard\client\job_board_signals.py
from signals import Signal
on_job_board_feature_availability_changed = Signal('job_signals.on_job_board_feature_availability_changed')
on_job_board_open_on_startup_changed = Signal('job_signals.on_job_board_open_on_startup_changed')
on_missions_feature_availability_changed = Signal('job_signals.on_missions_feature_availability_changed')
on_goals_feature_availability_changed = Signal('job_signals.on_goals_feature_availability_changed')
on_dungeons_feature_availability_changed = Signal('job_signals.on_dungeons_feature_availability_changed')
on_combat_anomalies_feature_availability_changed = Signal('job_signals.on_combat_anomalies_feature_availability_changed')
on_homefront_operations_feature_availability_changed = Signal('job_signals.on_homefront_operations_feature_availability_changed')
on_factional_warfare_feature_availability_changed = Signal('job_signals.on_factional_warfare_feature_availability_changed')
on_escalation_sites_feature_availability_changed = Signal('job_signals.on_escalation_sites_feature_availability_changed')
on_ore_anomalies_feature_availability_changed = Signal('job_signals.on_ore_anomalies_feature_availability_changed')
on_ice_belts_feature_availability_changed = Signal('job_signals.on_ice_belts_feature_availability_changed')
on_pirate_insurgency_feature_availability_changed = Signal('job_signals.on_pirate_insurgency_feature_availability_changed')
on_job_added = Signal('on_job_added')
on_job_removed = Signal('on_job_removed')
on_job_state_changed = Signal('on_job_state_changed')
on_job_completed = Signal('on_job_completed')
on_tracked_jobs_changed = Signal('on_tracked_jobs_changed')
on_job_window_initializing = Signal('on_job_window_initializing')
on_job_window_maximized = Signal('on_job_window_maximized')
on_job_viewed = Signal('on_job_viewed')
on_content_tag_count_updated = Signal('on_content_tag_count_updated')
on_job_provider_state_changed = Signal('on_job_provider_state_changed')
