#Embedded file name: C:\BuildAgent\work\ba3dced9a47cf95a\eve\release\V22.02\packages\projectdiscovery\client\projects\covid\sounds.py


class Sounds(object):
    SAMPLE_START = 'covid_background_main_play'
    SAMPLE_END = 'covid_background_main_stop'
    WELCOME_START = 'covid_init_play'
    DOCTOR_START = 'covid_info_screen_loop_play'
    DOCTOR_END = 'covid_info_screen_loop_stop'
    TUTORIAL_START = 'covid_tutorial_play'
    TUTORIAL_END = 'covid_tutorial_stop'
    POLYGON_SELECT = 'covid_polygon_highlight_play'
    POLYGON_DELETE = 'covid_polygon_del_play'
    POLYGON_COMPLETE = 'covid_polygon_complete_play'
    WIP_DELETE = 'covid_point_delete_play'
    POINT_ADD = 'covid_point_select_play'
    RESULTS_SUCCESS = 'covid_success_play'
    RESULTS_FAILURE = 'covid_failure_play'
    CALCULATE = 'covid_calculate_play'
    FLOW_CYTOMETER_1_INTRO = 'covid_intro_segment1_play'
    FLOW_CYTOMETER_2_INTRO = 'covid_intro_segment2_play'
    FLOW_CYTOMETER_3_INTRO = 'covid_intro_segment3_play'
    FLOW_CYTOMETER_4_INTRO = 'covid_intro_segment4_play'
    FLOW_CYTOMETER_1_INTRO_STOP = 'covid_intro_segment1_stop'
    FLOW_CYTOMETER_2_INTRO_STOP = 'covid_intro_segment2_stop'
    FLOW_CYTOMETER_3_INTRO_STOP = 'covid_intro_segment3_stop'
    FLOW_CYTOMETER_4_INTRO_STOP = 'covid_intro_segment4_stop'
    FLOW_CYTOMETER_LOOP = 'covid_intro_segment_loop1_2_3_play'
    FLOW_CYTOMETER_LOOP_STOP = 'covid_intro_segment_loop1_2_3_stop'
    REWARDS_BACKGROUND_PLAY = 'covid_info_screen_loop_play'
    REWARDS_BACKGROUND_STOP = 'covid_info_screen_loop_stop'
    REWARDS_LEVEL_UP = 'covid_levelup_play'
    REWARDS_MILESTONE_REWARD = 'covid_rewards_play'
